### ISSUE TITLE
Extension Proposal: support `UNIQUE NULLS NOT DISTINCT` in identities (Postgres 15+)

### ISSUE THREAD

**Issue by ibarakaiev** [ash-project/ash#1001]
I recently found out that Postgres treats `NULL != NULL` as true by default. Because of this, as soon as one of the fields in an `identity` is nullable, all identical records (with at least one nullable field being `NULL`) will be considered different. This leads to, for example, duplicate records when upserting based on identities—and this behavior is not trivial to debug.

The way to get around this limitation is to set `UNIQUE NULLS NOT DISTINCT` on the index, which is only available in Postgres 15+. I currently just manually created a migration to change the index to include it, but it'd be great if it was possible to instruct the migration generator to do automatically. I'm not totally sure what's the best way to approach this would be, since it's specific to Postgres-based resources (so it's probably not worth doing directly on `identity`'s DSL) and it is only supported starting from Postgres 15; just wanted to flag it as a potential area for improvement so that the auto-generated migrations and resource definitions stay in sync.

**Comment by nallwhy** [comment]
@ibarakaiev Is this issue can be resolved by https://github.com/ash-project/ash_postgres/pull/221?

**Comment by zachdaniel** [comment]
We also need this to be configurable in the resource itself, so that the index behaves the same in memory as it does in the db
