### ISSUE TITLE
skip_unknown_inputs not working on nested forms

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash#1028]
**Describe the bug**
It's unclear how to use skip_unknown_inputs on nested forms. It is not a valid option of add_form and when used on Ash.Phoenix.for_create it doesn't get applied to nested forms added later.  Workaround is to include an argument on the nested resources for the inputs that you want to skip.

**To Reproduce**
Create a form, use `add_form` for a nested form with the `skip_unknown_inputs` option. The option will be invalid.

**Expected behavior**
Should be able to use `skip_unknown_inputs` on nested forms.

**Runtime**
Ash 3.0.0-rc.21

**Additional context**

**Comment by zachdaniel** [comment]
`AshPhoenix.Form` actually automatically skips all inputs if they are unknown, since often we send. I think perhaps this was deviated from some of our documentation, so I think this may just need to be updated somewhere.

**Comment by zachdaniel** [comment]
Updated the docs
