### ISSUE TITLE
 Code interface args problem when the arg is a map

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash#1034]
**Describe the bug**
If I want to pass a map as an argument to a code interface, the map is treated like a set of params, even if the arg is defined in the code interface.

Say I have an attribute like:

```elixir
attribute :value, :map, default: %{}
```

and a code interface on the domain for an update like:

```elixir
define :update_session, action: :update, args: [:value]
```

If I call the update on the code interface with something like:

```elixir
Baseline.Accounts.update_session(session, %{"something" => "blah"})
```

I get a no such input error on "something" even though it is just a key on :value which is an input:

```elixir
{:error,
 %Ash.Error.Invalid{
   errors: [
     %Ash.Error.Invalid.NoSuchInput{
       calculation: nil,
       resource: Baseline.Accounts.Session,
       action: :update,
       input: "something",
       inputs: MapSet.new([:value, "value"]),
       splode: Ash.Error,
       bread_crumbs: [],
       vars: [],
       path: [],
       stacktrace: #Splode.Stacktrace<>,
       class: :invalid
     }
...
```

**Comment by zachdaniel** [comment]
I'm not able to reproduce this in tests in core. It is possible that it's only related to `ash_postgres`. Would it be possible to add a test there or create a small reproduction project?

**Comment by totaltrash** [comment]
Thank you and sorry, this was my mistake. I'd messed up the update action, I had `create :update do`, which for some reason worked in ash 2.0 (but i was using the code interface differently).
