### ISSUE TITLE
Changset.add_error not working inside destroy action

### ISSUE THREAD

**Issue by puruzio** [ash-project/ash#1037]
**Describe the bug**
Ash.Changeset.add_error is not adding error to the changeset when called inside a destroy action.

**To Reproduce**
Include the following codes in a destroy (soft?: true) action.
```
  change fn changeset, _ ->
    Ash.Changeset.before_action(changeset, fn changeset ->
      if Ash.Changeset.get_argument(changeset, :confirm_word) == "DELETE" do
        changeset
      else
        changeset
        |> Ash.Changeset.add_error(
          field: :confirm_word,
          message: "Type DELETE to confirm"
        )
      end
    end)
  end
```

**Expected behavior**
Ash.Changeset.add_error adds an error to the changeset and mark it invalid (valid?: false) when called inside a destroy action.

**Runtime**
 - Elixir version
 - Erlang version
 - OS
 - Ash version
 - any related extension versions

**Additional context**

**Comment by puruzio** [comment]
In comparison, the same code inside an update action adds an error as expected. Here is an example.

```
  errors: [
    %Ash.Error.Changes.InvalidAttribute{
      field: :confirm_word,
      message: "Type DELETE to confirm",
      private_vars: nil,
      value: nil,
      changeset: nil,
      query: nil,
      error_context: [],
      vars: [],
      path: [],
      stacktrace: #Stacktrace<>,
      class: :invalid
    }
  ],
```

**Comment by puruzio** [comment]
No, it’s not a simplified example. Let me try to create a minimal example that reproduces the issue.

Ash 2.21.6
Ash_Phoenix 1.3.4

**Comment by puruzio** [comment]
I realized I had a IO.inspect(changeset..) line at the bottom returning the changeset before add_error. :( Now it's working as I expected. Sorry for wasting your time.

**Comment by zachdaniel** [comment]
Not a problem :)
