### ISSUE TITLE
RC.27 breaks atomic_update for upsert create actions

### ISSUE THREAD

**Issue by chriscox** [ash-project/ash#1048]
**Describe the bug**
Release `3.0.0-rc.27` breaks the ability to use create actions with upserts as per [Atomic Updates doc](https://hexdocs.pm/ash/3.0.0-rc.27/create-actions.html#atomic-updates). It returns an `%Ash.Error.Invalid.AtomicsNotSupported` error. Prior to this RC (<= rc.26), a call to `change atomic_update()` works as expected.

**To Reproduce**
Simple example from docs will create the `%Ash.Error.Invalid.AtomicsNotSupported` error.

```elixir
create :create_game do
  accept [:identifier]
  upsert? true
  upsert_identity :identifier
  change set_attribute(:score, 0)
  change atomic_update(:score, expr(score + 1))
end
```

**Expected behavior**
Configuring upsert would expect the score to be incremented. Instead error is generated.

**Runtime**
 - Elixir version: 1.16.2
 - Erlang version: Erlang/OTP 26
 - OS: Mac Sonoma 14.4.1
 - Ash version: 3.0.0-rc.27

**Comment by zachdaniel** [comment]
Interesting...what data layer are you using? Are you sure its not an update in `AshPostgres` that caused the issue?

**Comment by zachdaniel** [comment]
If you're using the ETS data layer, then atomics are not supported.

**Comment by chriscox** [comment]
I'm using AshPostgres.DataLayer. Interestingly without any other changes, the upsert works ok with RC.26, but same code fails in RC.27. Using dep `ash_postgres 2.0.0-rc.9`

**Comment by zachdaniel** [comment]
How strange. Its a pretty small release: https://github.com/ash-project/ash/compare/v3.0.0-rc.26...v3.0.0-rc.27

I've just pushed up a new version of `ash_postgres`, could you try upgrading to that and see if it helps? `2.0.0-rc.10`

**Comment by chriscox** [comment]
Awesome! The `ash_postgres` update to `2.0.0-rc.10` fixes the issue.

**Comment by zachdaniel** [comment]
Thanks for the report :)
