### ISSUE TITLE
Ash.create() and Ash.update() oneliner

### ISSUE THREAD

**Issue by pierrelegall** [ash-project/ash#1051]
I'm always frustrated by the verbosity of the code below when I have no domain/resource code action for it.

```elixir
MyResource
|> Ash.Changeset.for_action(:create, %{data: value})
|> Ash.create()
```

Maybe something like this could do the job:

```elixir
Ash.create({MyResource, data: value})
# or
Ash.create({MyResource, data: value}, action: :not_primary_create)
```

And it could be the same for an update action (with a record instead of an atom):

```elixir
Ash.update({record, data: value})
# or
Ash.update({record, data: value}, action: :not_primary_update)
```

I'll be happy to implement it myself :)

PS: still not an Ash 3.0 user ;p

**Comment by zachdaniel** [comment]
I'm down 👍 Probably not worth back porting to 2.0 though.

**Comment by sevenseacat** [comment]
This seems weird to me - it feels like another way of making a code interface (but not as succinctly and missing most of the benefits of doing so)?

**Comment by zachdaniel** [comment]
Hm...I mean, it can be useful for cases when you are writing generic code (which is primarily what this interface is for). You're right that it does bring them closer to code interfaces, but it's much less verbose for the same result, so feels weird to artificially limit these interfaces just to push users elsewhere.

**Comment by pierrelegall** [comment]
Note this have already been change to something more elegant on `main`:

```elixir
Ash.create(User, %{name: "John"}, action: :register_with_password)
```

**Comment by pierrelegall** [comment]
It always seems weird to me do `Ash.create(changesets)`. A changeset is not created here: a resource is created from a changeset. Now we can do both, a changeset or a resource with its params.

Obviously, the execution path is now less self-evident.
