### ISSUE TITLE
Proposal: Treat `:*` as a single argument in accept, not a special syntax

### ISSUE THREAD

**Issue by nallwhy** [ash-project/ash#1061]
**Is your feature request related to a problem? Please describe.**

Sometimes, when I want to accept all public attributes along with a private attribute, I cannot use `:*` in accept and must explicitly list all the public attributes.

**Describe the solution you'd like**

I want to use it like `defaults [create: [:*, :private_attribute]]`.

**Describe alternatives you've considered**

Write all public attributes explilcitly like `defaults [create: [:public_attribute0, :public_attributes1, ..., :private_attribute]]`

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

Allow `defaults [create: [:*, :private_attribute]]`

**Additional context**

**Comment by zachdaniel** [comment]
This is acceptable 👍 It should be compatible with the current syntax.

**Comment by nallwhy** [comment]
#1062 is merged.
