### ISSUE TITLE
Ash.can?/3 is both asking for domain AND saying domain isn't valid

### ISSUE THREAD

**Issue by allenwyma** [ash-project/ash#1078]
**Describe the bug**
`Ash.can?(:update, user, data: Resource)` is complaining that I need to add in the domain as the domain cannot be found. After uing `Ash.can?(:update, user, data: Resource, domain: MyApp.Domain)`, i'm now getting: `no with clause matching: {:error, %Ash.Error.Unknown{changeset: nil, query: nil, action_input: nil, errors: [%Ash.Error.Unknown.UnknownError{error: %Spark.Options.ValidationError{message: "unknown options [:domain], valid options are: [:maybe_is, :filter_with, :run_queries?, :data, :tenant, :alter_source?, :base_query, :no_check?, :on_must_pass_strict_check, :atomic_changeset, :return_forbidden_error?]", key: [:domain], value: nil, keys_path: []}, field: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}], splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}}`

**To Reproduce**
trying to use Ash.can? with a resource

**Expected behavior**

**Runtime**
 - Elixir version
 - Erlang version
 - OS
 - Ash version
 - any related extension versions

**Additional context**

**Comment by allenwyma** [comment]
maybe i have this wrong? cause I can get it to work with this:
`Ash.can?({resource, :update}, user)`, but this also works? `Ash.can?(:create, user, domain: Tweeter.Tweets)`

**Comment by allenwyma** [comment]
oh, when I read the docs, it wasn't so clear for me what I can and cannot do, but I think i got it now. so for `:create` we can just pass in the module? I somehow got it working by passing in an empty struct.

**Comment by zachdaniel** [comment]
Yeah, I think we need to add a guide for it for `Ash.can` for sure. I will add something to the docs overhaul.
