### ISSUE TITLE
Calculations not loaded through union type attributes

### ISSUE THREAD

**Issue by nallwhy** [ash-project/ash#1082]
**Describe the bug**

Calculations not loaded through union type attributes.

**To Reproduce**

https://github.com/devall-org/ash/commit/36f7c20b577a2a7977b2edeba32a6452bd666233

`mix test test/resource/calculations_test.exs:281` fails

I tried `Ash.load!(post, content: [value: [:calc]])` also, but it fails too.

**Expected behavior**

Loading calculations works through union type attribute.

**Runtime**
 - Elixir version: 1.16.1
 - Erlang version: 26
 - OS: mac
 - Ash version: 3.0.0-rc.39
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Loading "through" a union involves using the type name as the key, as opposed to `value`.

```elixir
Ash.load!(post, content: [normal: [:calc]])
```

That way you can specify a different load statement for any given union type.
