### ISSUE TITLE
Actor template not working in relationship-filters

### ISSUE THREAD

**Issue by Torkan** [ash-project/ash#1085]
**Describe the bug**
Using the actor-template in a relationship filter throws
`%RuntimeError{message: "Unsupported expression in Elixir.AshPostgres.SqlImplementation query: {:_actor, :id}"}`

**To Reproduce**
Set up a relationship with a filter such as:
`has_one :entry, MyApp.Entries.Entry do
      filter expr(user_id == ^actor(:id))
      public? true
    end`

**Expected behavior**
That using the actor-template doesn't throw an error 😄 

**Runtime**
 - Elixir version 1.16.2-otp-26
 - Erlang version erlang 26.2.1
 - OS - MacOS 14.4.1
 - Ash version - 3.0.0-rc.39
 - ash_postgres - 2.0.0-rc.13
 - ash_sql - 0.1.1-rc.15

**Additional context**
Can't think of much to add here 😄

**Comment by zachdaniel** [comment]
Fixed in `ash_sql` `v0.1.1-rc.16`
