### ISSUE TITLE
New calculation bug introduced in 3.0.0-rc.38

### ISSUE THREAD

**Issue by chriscox** [ash-project/ash#1091]
**Describe the bug**
Calling a calculation defined in the  `define_calculation` within the `code_interface` of a resource no longer finds the calculation when it uses a module. Please note this works in `rc.37`, but seems to have been broken in `rc.38`.

An example error:

```
** (Ash.Error.Unknown) Unknown Error

* %UndefinedFunctionError{module: :demo_calc, function: :name, arity: 0, reason: nil, message: nil}
  :demo_calc.name()
  (ash 3.0.0-rc.38) lib/ash/actions/read/calculations.ex:132: Ash.Actions.Read.Calculations.calculate/3
  (ash 3.0.0-rc.38) lib/ash.ex:1333: Ash.calculate!/3
```

**To Reproduce**
You can use the example in [docs](https://hexdocs.pm/ash/3.0.0-rc.38/code-interfaces.html#calculations) to repro this. Except modify to return a module calculation rather than an `expr`. Its worth noting that using an inline `expr` does continue to work, its only when referring to a Calculation Module that it breaks.

Create the calc and `define_calculation` in the resource.
```
code_interface do
  define_calculation :demo_calc, args: [:_record]
end

# Note: Using module here is where it breaks. Using expr still works correctly.
calculations do
  calculate :demo_calc, :atom, Calculations.DemoCalcTest
end
```

Define a module for this calculation in a separate file.
```
defmodule Calculations.DemoCalcTest do
  use Ash.Resource.Calculation

  def calculate(records, _opts, _params) do
    Enum.map(records, fn record ->
      # just a simple return to see if working
      :got_a_result
    end)
  end
end
```

Now call somewhere using `MyResource.demo_calc(record)`

**Expected behavior**
In rc.37, the calculate method correctly returns. However in rc.38, the module is not found resulting in UndefinedFunctionError

**Runtime**
 - Elixir version: 1.16.2
 - Erlang version: Erlang/OTP 26 [erts-14.2.2
 - OS: macOS 14.4.1
 - Ash version: 3.0.0-rc.38

**Comment by zachdaniel** [comment]
Thanks for the report! Fixed in b8c01596cb7f46b1bfe5d9f5114bbd16b3be94e7
