### ISSUE TITLE
documentation: link docs containing code examples related to modules

### ISSUE THREAD

**Issue by legrec14** [ash-project/ash#1110]
**Is your feature request related to a problem? Please describe.**
Many times I go through module doc pages with only a schema or types described on it, as for instance:
https://hexdocs.pm/ash/3.0.0-rc.40/Ash.Resource.Actions.html

But when I’m looking for Resource.Actions doc, I’m indeed looking for how to create and feed correctly an `actions` section inside my Resource module.
I’m looking for the syntax to use, for the available options, and more globally for code examples on how to create and custom `actions`.

Finally, I can find this kind of information under other links, as:
https://hexdocs.pm/ash/3.0.0-rc.40/actions.html
https://hexdocs.pm/ash/3.0.0-rc.40/create-actions.html

But because there are a lot of modules and related documentation under the Ash project, it’s not always easy (at least for me) to navigate quickly to the right documentation page (through a web research or even when trying to navigate inside the documentation sections). I guess I’ll be better and better at navigating through the good information inside these docs, but for new users, I think it could be simplified.

**Describe the solution you'd like**
It could be so nice to have a banner or something like that, asking on certain widely-used modules (such as Resource.Actions) if the visitor is looking for code example, options, etc… rather than just the module types.

And to have links to other pages already existing in the docs, showing code examples related to the module doc we just visited.

**Describe alternatives you've considered**
After I realized ChatGPT was driving me very badly, I pursued my researches through official documentation, questions / answers on the Elixir forum (from me and other users), questions / answers on Discord, etc…

**Express the feature either with a change to resource syntax, or with a change to the resource interface**
Maybe just some banners and some links.

**Additional context**
I’ve nothing more to say :)

**Comment by zachdaniel** [comment]
The will be addressed as a later initiative, where we review all reference documentation. #1089
