### ISSUE TITLE
An Aggregate of Calculations fails to load

### ISSUE THREAD

**Issue by BryanJBryce** [ash-project/ash#1112]
Relevant ElixirFourm discussion. Thought it was an Ash GraphQL issue at the time, but appears to be Ash/AshPostgres:
https://elixirforum.com/t/ashgraphql-filtering-on-calculations-that-use-aggregates/63145

**Describe the bug**
I'll describe the bug using a simple example.

**`OrderItem`** 
```
  attributes do
    uuid_primary_key :id

    attribute :product_name, :string, allow_nil?: false, public?: true
    attribute :size_name, :string, allow_nil?: true, public?: true

    attribute :quantity, :decimal, allow_nil?: false, public?: true
    attribute :price, :decimal, allow_nil?: false, public?: true
  end

  calculations do
    calculate :subtotal, :string, expr(type(quantity, :decimal) * type(price, :decimal)),
      public?: true
  end
```

**`Order`**
```
  aggregates do
    sum :subtotal, :order_items, :subtotal, public?: true
  end
```

`iex >  Ash.read(Order, load: [:subtotal])`

> %Ash.Error.Unknown.UnknownError{
>          error: "** (Postgrex.Error) ERROR 42883 (undefined_function) function sum(text) does not exist\n\n    query: SELECT o0.\"id\", o0.\"customer_name\", s1.\"subtotal\"::text::text FROM \"orders\" AS o0 LEFT OUTER JOIN LATERAL (SELECT so0.\"order_id\" AS \"order_id\", sum((so0.\"quantity\"::decimal::decimal * so0.\"price\"::decimal::decimal)::text::text)::text AS \"subtotal\" FROM \"public\".\"order_items\" AS so0 WHERE (o0.\"id\" = so0.\"order_id\") GROUP BY so0.\"order_id\") AS s1 ON TRUE\n\n    hint: No function matches the given name and argument types. You might need to add explicit type casts.",
>          field: nil,
>          splode: Ash.Error,
>          bread_crumbs: [],
>          vars: [],
>          path: [],
>          stacktrace: #Splode.Stacktrace<>,
>          class: :unknown
>        }

**To Reproduce**
I've set up a project that reproduces the issue on the branch linked:
https://github.com/BryceLabs/ash_issues_examples/tree/calc_aggregate

**Expected behavior**
I'd expect the aggregate of calculations to load

**Runtime**

>       {:ash, "~> 3.0.0-rc.42"},
>       {:ash_postgres, "~> 2.0.0-rc.14"},
>       {:ash_phoenix, "~> 2.0.0-rc.8"},
>       {:ash_graphql, "~> 1.0.0-rc.5"

**Comment by zachdaniel** [comment]
Was looking into this for a while before I realized 😆 :

```elixir
  calculations do
    calculate :subtotal, :string, expr(type(quantity, :decimal) * type(price, :decimal)),
      public?: true
  end
```

The calculation is not a `:string`, its a `:decimal` :)

**Comment by BryanJBryce** [comment]
Doh! I was just thinking, hey, where do I set the type...there is is

**Comment by BryanJBryce** [comment]
I think an error remains in my more complex example, but I'll open an new issue for that
