### ISSUE TITLE
Support returning notifications from a `before_action` function

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#1123]
**Is your feature request related to a problem? Please describe.**

In an `after_action` hook, the return type of the hook lets you return any generated notifications for sending, eg.

```elixir
{:ok, changeset} # normal 
{:ok, changeset, notifications} # added notifications!
```

`before_action` hooks don't support this - you can only return a changeset. 

So to send notifications from a `before_action`, you end up having to store them onto the changeset to read back later, eg. 

```elixir
      change before_action(fn changeset, _context ->
                   %{notifications: notifications} =
                     MyApp.Accounts.Notification.destroy(
                       changeset.data.notifications,
                       %{},
                       return_notifications?: true
                     )

                   Ash.Changeset.set_context(changeset, %{notifications: notifications})
               end
             end)

      change after_action(fn changeset, _opts, _context ->
               {:ok, changeset, changeset.context.notifications}
             end)
```

Which works, but it's not super great!

**Describe the solution you'd like**

Ideally the return types of before/after action hooks would be consistent, but I know that doesn't really play nicely with before actions - you'd have to construct an `ok` tuple every time.

So maybe tweaking the return type to support a `changeset | {changeset, notifications}` ?

**Comment by zachdaniel** [comment]
The type spec for `before_action_fun` is this

```elixir
@type before_action_fun :: (t -> t | {t, %{notifications: [Ash.Notifier.Notification.t()]}})
```

(unfortunately weird and inconsistent with `after_action`. We can clean that up another time)

**Comment by zachdaniel** [comment]
I'll close this for now. If returning that format is causing a bug, then we'll have to address that as a separate issue.

Also, just to note, we added something a while ago that automatically gathers up any notifications that would be emitted as long as it was an Ash action that started the transaction using 🪄. So you don't typically need to return notifications anymore. If you are finding that you have to, then that might be a separate bug also.

**Comment by sevenseacat** [comment]
I could have sworn I looked at the docs and it only supported returning a changeset. Huh. I'll give it a go and report back!

**Comment by zachdaniel** [comment]
Its very very likely that somewhere in the docs we don't indicate it properly.

**Comment by sevenseacat** [comment]
Nonetheless, that works, thank you!

I'll try to figure out how/where I got the wrong idea from in the docs, and correct it

**Comment by sevenseacat** [comment]
I think I misread the typespec here https://hexdocs.pm/ash/3.0.0-rc.46/Ash.Changeset.html#before_action/3 to think the hook could only return a `t()`. Oops
