### ISSUE TITLE
Call to destroy for embeddable type does not work if embeddable type has policies

### ISSUE THREAD

**Issue by barnabasJ** [ash-project/ash#1136]
https://github.com/ash-project/ash/blob/078cc4f28b34897f2da36e898e4cb7e72b534381/lib/ash/embeddable_type.ex#L727 as well as https://github.com/ash-project/ash/blob/078cc4f28b34897f2da36e898e4cb7e72b534381/lib/ash/embeddable_type.ex#L822

This does not work if you have policies on your embedded type. There are a couple more places inside this module where Ash.<action> calls are performed without passing anything for authorization.

**Comment by barnabasJ** [comment]
Locally, I just added `authorize?: false` to make my test work for now. I haven't had the time yet to investigate where the actor would be coming from.

**Comment by barnabasJ** [comment]
Maybe you already know where you would get it from, @zachdaniel. Otherwise, let me know, and I can investigate further.

**Comment by zachdaniel** [comment]
So, taking a look, I can see why this would be the case for the `destroy` call, but not the `update` call. I will push up a fix for the `update` call in a bit, and we can see if that resolves it for you.

**Comment by barnabasJ** [comment]
> So, taking a look, I can see why this would be the case for the `destroy` call, but not the `update` call. I will push up a fix for the `update` call in a bit, and we can see if that resolves it for you.

I'm not sure I understand. Did you mean `destroy` in the second sentence? I'm also not sure what the difference is. Both are calls to action that do not get the necessary data to run policies.

**Comment by zachdaniel** [comment]
What information are they missing (as of the latest?) I believe they are fixed.

**Comment by barnabasJ** [comment]
The `actor`

**Comment by zachdaniel** [comment]
We get the actor from the source changeset, because we copy the `private` context

**Comment by barnabasJ** [comment]
I guess that's happening in `copy_source`? I didn't check in there, because the variable passed in was called `constraints`. 

I wasn't able to verify this yet because the newest commit kills my tests because of infinite recursion.
