### ISSUE TITLE
not specifying attribute_type: integer for integer_primany_key in its relationships throws invalid_attribute error.

### ISSUE THREAD

**Issue by bhanuvrat** [ash-project/ash#1140]
**Describe the bug**
Even if both the resources in a relationship have `integer_primary_key`s, one would expect foregoing `attribute_type: integer` specification may be okay. 

There is no mention of an error when defining the resource or generating migrations.
There error shows up only when we try to insert a record in the table.
The error is not very descriptive and just says "invalid attribute" on the foregin_key making it very hard to debug.

**To Reproduce**
```elixir
defmodule MyApp.MyApi.M1 do
  use Ash.Resource, data_layer: AshPostgres.DataLayer

  postgres do
    table "m1"
    repo MyApp.Repo
  end

  attributes do
    integer_primary_key :id
    m1_name :string
  end

  relationships do
    has_one m2, MyApp.MyApi.M2
  end
end

defmodule M2 do
  use Ash.Resource, data_layer: AshPostgres.DataLayer

  postgres do
    table "m1"
    repo MyApp.Repo
  end

  attributes do
    integer_primary_key :id
    m2_name: string
  end

  code_interface do
    define_for MyApp.MyApi

    define :create, action: :create
  end

  actions do
    create :create do
      primary? true

      accept [
        :m1_id
      ]
    end
  end

  relationships do
    belongs_to m1, MyApp.MyApi.M1
  end
end
```

```elixir
# assume m1 is a record of MyApp.MyApi.M1

MyApp.MyApi.M2 
|> Ash.Changeset.for_create(:create, %{m2_name: "what's in a name?", m1: m1.id}) 
|> MyApp.MyApi.create!()
```
  
Inserting a record in M2 would throw `invalid_attribute` on the m1_id field, unless we add `attribute_type: integer` in the relationship as such:

```elixir
  relationships do
    belongs_to m1, MyApp.MyApi.M1, attribute_type: integer
  end
```

**Expected behavior**

Either Ash should figure out that the field is integer and accept the integer value being passed.
Or state that it expects the attribute to be specified as integer in the relationship.

**Runtime**
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Interactive Elixir (1.16.2) - press Ctrl+C to exit (type h() ENTER for help)
 - Elixir version: 1.16.2
 - Erlang version: Erlang/OTP 26 [erts-14.2.2]
 - OS: macOS 14.4 (23E214)
 - Ash version: 2.18
 - any related extension versions:
 ```
     {:ash_phoenix, "~> 1.3"},

      {:ash_postgres, "~> 1.4"},
      {:ash_authentication, "~> 3.12"},
      {:ash_authentication_phoenix, "~> 1.9.4"},
```

**Comment by zachdaniel** [comment]
AFAIK there should be a warning in place that expresses  incompatible foreign key types. Do you not get that warning?

**Comment by bhanuvrat** [comment]
Both the tables had integer_primay_key specified on them.

Ash expects that even if both the resources have integer_primary_key, we still need to specify `attribute_type: integer` on the relationship for things to work.

**Comment by zachdaniel** [comment]
Correct, we cannot do this automatically due to compile time constraints. But we warn you when it's wrong, and that's the best we can do.

**Comment by bhanuvrat** [comment]
@sevenseacat Need a A little help here.
I think I am unable to describe the issue properly.

**Comment by sevenseacat** [comment]
Yeah I don't recall having any warnings come up, but I've just tried setting up a similar scenario in a Livebook and I'm seeing the compilation warning:

```
warning: Source attribute may not be compatible with destination attribute for Example.Post.author to Example.Author

`source_attribute` type: `Ash.Type.UUID`
`destination_attribute` type: `Ash.Type.Integer`

Types are considered compatible if:

1. They are exactly the same
2. Their `storage_type/1` callback returns the same value
3. The storage types are `:text` and `:string`
4. The relationship has `validate_destination_attribute?` set to `false`.
5. They are explicitly configured as compatible. To do so in this instance, add it to your config like so:


config :ash, :compatible_foreign_key_types,
  [
    {Ash.Type.UUID, Ash.Type.Integer}
  ]

  #cell:l3pofv5fqax7tn3kfoptxzl5jf7uxzpl:10: Example.Post.__verify_spark_dsl__/1
```

Did we possibly just miss the warning?

Can you try removing the `attribute_type: :integer` in your app and seeing if there is a warning that we skipped past?

**Comment by bhanuvrat** [comment]
Both source and the destination were integer_primary_key.

Perhaps that is why there was no warning.

**Comment by zachdaniel** [comment]
That relationship isn't from one primary key to another, it's from a new generated attribute, I.e `m1_id` to a primary key.

**Comment by zachdaniel** [comment]
Honestly its one of those things that 100% *seems* like the framework would/should be able to do for you, just unfortunately its a technical chicken and the egg problem that we can't solve 😢
