### ISSUE TITLE
Missing sidebar links in hexdocs

### ISSUE THREAD

**Issue by yasoob** [ash-project/ash#1153]
As part of 3.0 release it seems like some configuration needed to be changed but was not. The current hexdocs does not show any sidebar links for 3.0 version:

<img width="321" alt="image" src="https://github.com/ash-project/ash/assets/3696393/ec3e2ba7-0940-431c-b3ca-efc028b340b1">

The links are present if I open an RC version:

<img width="334" alt="image" src="https://github.com/ash-project/ash/assets/3696393/7d9bfa03-d8ae-4910-8e60-43169a2e190e">

**Comment by zachdaniel** [comment]
Strange, don't know why this happened. I pushed docs again and it appears to be fixed.
