### ISSUE TITLE
A bulk_create action no longer sets the user relationship in my resource using change relate_actor(:user)

### ISSUE THREAD

**Issue by chriscox** [ash-project/ash#1154]
**Describe the bug**
When using `Ash.bulk_create`, the `change relate_actor(:user)` no longer appropriately associates the user field required for the relationship. In my case, I'm passing in the actor using `actor: current_user`.

**To Reproduce**
In a `create` action, associate the actor `change relate_actor(:user)`. When calling this create specifically, it works ok. However when calling this with a bulk_create, it fails to make the association.

The following error is after using bulk_create (and still passing in the `actor: current_user` in options.

```
** (Ash.Error.Invalid) Invalid Error

* relationship user is required
  (elixir 1.16.2) lib/process.ex:860: Process.info/2
  (ash 3.0.0) lib/ash/error/changes/required.ex:5: Ash.Error.Changes.Required.exception/1
  (ash 3.0.0) lib/ash/actions/managed_relationships.ex:361: anonymous fn/3 in Ash.Actions.ManagedRelationships.validate_required_belongs_to/2
  (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 3.0.0) lib/ash/actions/create/bulk.ex:383: anonymous fn/2 in Ash.Actions.Create.Bulk.handle_batch/9
  (elixir 1.16.2) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
  (elixir 1.16.2) lib/enum.ex:4839: Enumerable.List.reduce/3
  (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4
  (elixir 1.16.2) lib/enum.ex:4396: Enum.reduce/3
  (ash 3.0.0) lib/ash/actions/create/bulk.ex:392: Ash.Actions.Create.Bulk.handle_batch/9
  (ash 3.0.0) lib/ash/actions/create/bulk.ex:165: anonymous fn/12 in Ash.Actions.Create.Bulk.do_run/5
  (elixir 1.16.2) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
  (elixir 1.16.2) lib/stream.ex:1816: anonymous fn/3 in Enumerable.Stream.reduce/3
  (elixir 1.16.2) lib/stream.ex:289: Stream.after_chunk_while/2
  (elixir 1.16.2) lib/stream.ex:1845: Enumerable.Stream.do_done/2
  (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4
  (elixir 1.16.2) lib/stream.ex:943: Stream.do_transform/5
  (elixir 1.16.2) lib/enum.ex:4396: Enum.reverse/1
  (elixir 1.16.2) lib/enum.ex:3728: Enum.to_list/1
  (ash 3.0.0) lib/ash/actions/create/bulk.ex:189: Ash.Actions.Create.Bulk.do_run/5
* Invalid Error
```

**Expected behavior**
I would expect the actor to be associated with the attribute (`user` in my case) the same way when calling it directly or with bulk_create.

**Runtime**
 - Elixir version: 1.16.2
 - Erlang version: Erlang/OTP 26 [erts-14.2.2]
 - OS: Sonoma 14.4.1
 - Ash version: 3.0.0

**Comment by zachdaniel** [comment]
Interesting, I haven't been able to reproduce this yet. Can I see how you are calling the bulk create? I may need a reproduction, as I've tested this locally and it appears to work.

**Comment by zachdaniel** [comment]
Nevermind, got it reproduced :)
