### ISSUE TITLE
relates_to_actor_via creates an expensive left join

### ISSUE THREAD

**Issue by hanrelan** [ash-project/ash#1179]
**Describe the bug**
With a policy like this:

```elixir
    policy action_type([:read]) do
      authorize_if relates_to_actor_via([:user])
      authorize_if expr(is_nil(user_id))
    end
```

Ash creates a query that looks like this:

```sql
SELECT v0."id", v0."slug", v0."name"
FROM "resource" AS v0
LEFT OUTER JOIN "public"."users" AS u1 ON v0."user_id" = u1."id"
WHERE (
    (u1."id"::uuid = '<uuid>'::uuid)
    OR (v0."user_id"::uuid IS NULL)
);
```

The LEFT OUTER JOIN makes this query very expensive. 

**Expected behavior**
The following query:
```sql
SELECT v0."id", v0."slug", v0."name", v0."type", v0."inserted_at", v0."updated_at", v0."user_id" FROM "resource" AS v0 WHERE ((v0."user_id"::uuid IS NULL) OR (v0."user_id"::uuid = '<uuid>'))
```
This executes 30x faster

**Runtime**
 - Ash version: 2.21.12
 - any related extension versions: Ash postgres: 1.5.1

**Comment by zachdaniel** [comment]
So the problem here is the `or` that is involved. "Either it relates to the actor *or* user_id is nil" means that we have to left join. If we inner join, its actually "has a user, and that user is the actor, or user_id is nil" which would be a query that cannot produce any rows.

**Comment by zachdaniel** [comment]
Okay one thing we *could* do is replace references like "foo.id" to "foo_id" if the current resource belongs to that thing with a non-filtered relationship... will look into it.

**Comment by zachdaniel** [comment]
We may make some optimizations like this in the future, but for now the resolution is to use `user_id ==` instead of `actor_attribute_equals`
