### ISSUE TITLE
identities with `where` like custom_indexes

### ISSUE THREAD

**Issue by jechol** [ash-project/ash#1182]
**Is your feature request related to a problem? Please describe.**

When creating an index that requires a where condition, it is not possible to create it using identity. Instead, it can only be created using custom_indexes.

However, upsert_identity can only use indexes created with identity and cannot utilize indexes created with custom_indexes.

As a result, it is currently not possible to perform an upsert based on an identity that requires a where condition.

**Describe the solution you'd like**

I would like to be able to use where with identity.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

```
identity :foo_bar, [:foo, :bar], where: expr(baz == "10")
```

or

```
identity :foo_bar, [:foo, :bar], where: "baz = '10'"
```

(It seems like the latter approach is dependent on SQL, so I should probably use the former one...)

**Comment by zachdaniel** [comment]
👍 makes sense to me. Will need a way to express the sql variant of the filter, but we can add that to the Postgres DSL
