### ISSUE TITLE
Migration Resources

### ISSUE THREAD

**Issue by emtudo** [ash-project/ash#1189]
# Conversion of attributes to migrate

Is it possible to configure the string attributes with their respective sizes and the migrate is not as text but as a string, and the size is also defined?

Another question would be possible to add the TimestampTz type so that it correctly generates migrates?

Another feature would be interesting to have a way to define unique index attributes, example: CREATE UNIQUE INDEX unique_organization_slug ON organizations(slug) WHERE archived_at IS NULL

**Comment by zachdaniel** [comment]
These are all possible using the DSL available in the Postgres section, yes: https://hexdocs.pm/ash_postgres/2.0.2/dsl-ashpostgres-datalayer.html
