### ISSUE TITLE
Ash.Resource.Calculation.load has incorrect typespec

### ISSUE THREAD

**Issue by aidalgol** [ash-project/ash#1219]
**Describe the bug**
The typespec for [Ash.Resource.Calculation.load](https://hexdocs.pm/ash/Ash.Resource.Calculation.html#c:load/3) indicates a custom callback can return either a list of atoms, or a single atom (or a Keyword list, but that is not relevant to the issue at hand).

**To Reproduce**
Livebook minimal reproduction (fix filename extension after downloading): 
[calculation_load_bug.txt](https://github.com/user-attachments/files/15529637/calculation_load_bug.txt)

**Expected behavior**
I expect the calculation to work just the same as when `load` returns a list of a single atom.

**Runtime**
 - Elixir version: 1.16.2
 - Erlang version: 25
 - OS: NixOS
 - Ash version: 3.0.6
 - any related extension versions: N/A

**Additional context**
N/A

**Comment by zachdaniel** [comment]
Should be fixed in `main` :)
