### ISSUE TITLE
Issue with many to many on update

### ISSUE THREAD

**Issue by torepettersen** [ash-project/ash#1239]
**Describe the bug**
I have a problem updateing a record with an assosition in a many to many relationship. When updateing the assosioation and one of the records in the list already is assosiated I get an error message.

**To Reproduce**
Was a bit hard to describe the bug, so I [created a repoduction](https://github.com/torepettersen/helpdesk) of the bug.

In short, if you try to update the list of programming lanuages in the exampel, when one of the programming languages in the list is already assosiated to the job, you will get  an error.

```elixir
iex> job = Ash.create!(Helpdesk.Support.Job, %{title: "Backend Developer"})
iex> job = Ash.update!(job, %{programming_languages: [%{name: "Elixir"}]})
iex> job = Ash.update!(job, %{programming_languages: [%{name: "Elixir"}]})

** (Ash.Error.Invalid) Invalid Error

* Invalid value provided for job_id: has already been taken.

nil

    at programming_languages, 0
  (elixir 1.17.0-rc.0) lib/process.ex:864: Process.info/2
  (ash 3.0.11) lib/ash/error/changes/invalid_attribute.ex:5: Ash.Error.Changes.InvalidAttribute.exception/1
  (elixir 1.17.0-rc.0) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
  (ash_postgres 2.0.8) lib/data_layer.ex:2145: AshPostgres.DataLayer.handle_raised_error/4
  (ash_postgres 2.0.8) lib/data_layer.ex:1986: AshPostgres.DataLayer.create/2
  (ash 3.0.11) lib/ash/actions/create/create.ex:365: anonymous fn/6 in Ash.Actions.Create.commit/3
  (ash 3.0.11) lib/ash/changeset/changeset.ex:3381: Ash.Changeset.run_around_actions/2
  (ash 3.0.11) lib/ash/changeset/changeset.ex:2965: anonymous fn/3 in Ash.Changeset.with_hooks/3
    (elixir 1.17.0-rc.0) lib/process.ex:864: Process.info/2
    (ash 3.0.11) lib/ash/error/invalid.ex:3: Ash.Error.Invalid.exception/1
    (ash 3.0.11) /home/tore/workspace/helpdesk/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
    (ash 3.0.11) lib/ash/error/error.ex:66: Ash.Error.to_error_class/2
    (ash 3.0.11) lib/ash/actions/update/update.ex:306: Ash.Actions.Update.do_run/4
    (ash 3.0.11) lib/ash/actions/update/update.ex:235: Ash.Actions.Update.run/4
    (ash 3.0.11) lib/ash.ex:2448: Ash.update/3
    iex:3: (file)

```

**Expected behavior**
I expect this error not happen and that the list of programming languages give will be assosiated to the job.

**Runtime**
 - Elixir version: 1.17.0-otp-27
 - Erlang version: 27.0
 - OS: EndeavourOS
 - Ash version: 3.0.11
 - Ash Postgres: 2.0.8

**Comment by zachdaniel** [comment]
Thank you for the report, I will look into this tomorrow or the day after.

**Comment by zachdaniel** [comment]
Alright, so this is actually working *mostly* as intended. Specifically, if you want it to know not to insert some related thing, it has to infer that it is already related in some way based on the input. In this case, that means doing this:

```elixir
      change manage_relationship(:programming_languages,
               type: :append_and_remove,
               use_identities: [:name] # <- tell it to use the `:name` identity to determine that existing/new entities are matches
             )
```

With that said, at some point managed_relationships will be built to use bulk actions with will bulk upsert the join rows, preventing the attempt to insert duplicate rows. Going to close for now as it is working "as intended", even though that will be slightly improved later :)

**Comment by torepettersen** [comment]
Thanks for explaining! That worked :blush:
