### ISSUE TITLE
Fix warnings and suggestions when compiling the project with elixir 1.11

### ISSUE THREAD

**Issue by WolfDan** [ash-project/ash#128]
With the new release of elixir 1.11 we have much better compilation times and more compiler checks

The addition of new compiler checks (in special data constructors) makes the project have a lot of compilation warnings, which should be solved for any future release of the library

**Comment by zachdaniel** [comment]
This has been completed for ash core, as well as ash_postgres. We may need separate issues for the other projects, or I'll just fix them the next time I work on them :)
