### ISSUE TITLE
default_accept and accept does not accept :* for embeds

### ISSUE THREAD

**Issue by olivermt** [ash-project/ash#1288]
**Describe the bug**
If you `change_attribute` on a changeset and configure either `default_accept` or `accept` in the create/read with `:*` you get invalid input for all attrs. Specifying all the attrs in either default or normal accept makes it work again.

**To Reproduce**
```
Ash.Changeset.change_attribute(
          changeset,
          :your_embed,
          some_embed_with_matching_map_keys
        )
```
**Expected behavior**
Expected that `:*` would work

**Runtime**
 - Ash version - 3.0.16
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Hey @olivermt if possible could you please provide a reproduction or some example code that fails? I've looked and our existing tests don't seem to reproduce this behavior. Our existing tests use `default_accept :*`. Perhaps the issue that you have is that your attributes are not marked as public? `:*` does not mean "all attributes", it means "all public attributes". However, you can *explicitly* (only explicitly, for safety) choose to accept non-public attributes.

Going to close for now until we can confirm the issue or reproduce it.
