### ISSUE TITLE
Option for controlling visibility through field policies rather than with the public flag

### ISSUE THREAD

**Issue by torepettersen** [ash-project/ash#1290]
**Is your feature request related to a problem? Please describe.**

The public flag on attributes is not very explicit. It can tell if an attribute is public or private, but it does not tell anything about who it is public to. Being public could mean being public to the internal system, an admin user or a regular user.

Ash has field policies that are a lot more descriptive. Field policies don't just let you know if an attribute is public or not; they also let you know who it is public to.

Currently, if you want to cover all attributes by field policies, you need to explicitly mark each attributes as public. This is not necessarily a problem, but it feels a bit redundant to me.

**Describe the solution you'd like**

I would like a new global option `control_visibility_through_field_policies`.

This option would:
- Make all attributes public by default
- Require field policies for each resource
- Disallow the usage of `:*`

I am aware that making attributes public by default could be a vulnerability in itself. But if all attributes are covered by field policies, there should be no worry about exposing an unwanted field. The only exception to this is if `:*` is used, since `:*` includes all public fields, which are all fields, if public defaults to true. That is why I'm also purposely suggesting disabling usage of `:*` with this setting.

**Describe alternatives you've considered**

Another option could be to have one option for each of the options included in `control_visibility_through_field_policies` from the proposal. This allows for more customization, but also allows for more vulnerabilities if they are used wrong.

**Additional context**
Is this an option that would make sense to add? Or do you see some problems I don't see? If this is something that you would accept, I would be happy to provide a PR.

**Comment by zachdaniel** [comment]
We definitely will not do anything that makes all attributes public by default, as tools like `AshGraphql` and `AshJsonApi` automatically add all public attributes (with or without usage of `:*`) to their exposed schemas/documentation etc.

I don't even want the code in there that can do that to avoid potential bugs around that behavior.

With the exception of making all attributes public by default, you could actually use a custom extension to:
- disallow the usage of `:*`, and could use what we're discussing in your current PR for private fields in field policies to accomplish the hiding of all attributes via policies (which I believe is more in line with your original goals anyway).
