### ISSUE TITLE
`ash.gen.resource` Igniter task does not prompt to proceed with changes, so they can't actually be made

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#1297]
**Describe the bug**
 
When generating a resource inside a domain, no prompt is given to accept the changes or not:

```
.: ~/P/t/cat : main (1ca2111) : 8:35pm :.
$ mix ash.gen.resource Cat.Music.Meow -d Cat.Music

Igniter:
Update: lib/cat/music.ex

   ...|
3 3   |
4 4   |  resources do
  5 + |    resource Cat.Music.Meow
5 6   |  end
6 7   |end
   ...|


Create: lib/cat/music/meow.ex

1 | defmodule Cat.Music.Meow do
2 |   use Ash.Resource,
3 |     otp_app: :cat,
4 |     domain: Cat.Music
5 | end
6 |


.: ~/P/t/cat : main (1ca2111) : 8:35pm :.
```

**Expected behavior**

I should see a "Proceed with changes? [Yn]" prompt like when generating a domain.

**Runtime**
Elixir version 1.17.0-otp-27
    Erlang version 27.0
    OS macOS Sonoma
    Ash version main @ https://github.com/ash-project/ash/commit/d04e846f2cb00ca514e43b04c41c87ad9fb92b86
    Igniter version main @ 27b6808408d7cf80cc7b02d53880f6239af0b5cb

**Comment by sevenseacat** [comment]
As an aside, should the resource have `otp_app: :cat` in it?

And `--domain` doesn't seem to be an accepted option:

```
.: ~/P/t/cat : main (1ca2111) : 8:43pm :.
$ mix ash.gen.resource Cat.Music.Froo --domain Cat.Music
** (Mix) Could not invoke task "ash.gen.resource": 1 error found!
--domain : Unknown option

.: ~/P/t/cat : main (1ca2111) : 8:43pm :.
$ mix ash.gen.resource Cat.Music.Froo --domain=Cat.Music
** (Mix) Could not invoke task "ash.gen.resource": 1 error found!
--domain : Unknown option
```

**Comment by sevenseacat** [comment]
Upon further testing it seems to be related to providing a domain - if I don't specify a domain I get the prompt and can generate as normal.

**Comment by zachdaniel** [comment]
Yes, the resource and domain should have the `otp_app`. It allows configuring specific DSL elements with application config, i.e

```elixir
config :my_app, Cat.Music.Froo, postgres: [table: "table_name"]
```

As for not prompting but just making the changes, that is pretty strange. So to confirm it just "does it" without asking?

**Comment by sevenseacat** [comment]
No - when a domain is specified, it doesn't do anything at all. Just prints out and exits.

**Comment by zachdaniel** [comment]
Fixed in latest igniter and and ash
