### ISSUE TITLE
Unable to set attributes on nested resource from nested input attributes, when `public?: false`

### ISSUE THREAD

**Issue by moxley** [ash-project/ash#1305]
**Describe the bug**

I'm upgrading my application to Ash 3, and this issue came up. I have code that needs to build nested embedded resource structs from nested attributes. Some of the attributes in the nested resources are private, but according to the Ash docs, there's no reason they should be un-writable. Even so, adding `writable?: true` doesn't make a difference.

**To Reproduce**

```elixir
# Child resource
defmodule Credentials do
  use Ash.Resource, data_layer: :embedded

  attributes do
    attribute :username, :string, public?: true
    attribute :password, :string, public?: false, writable?: true
  end
end

# Parent resource
defmodule ServiceConfig do
  use Ash.Resource, data_layer: :embedded

  attributes do
    attribute :name, :string, public?: true
    attribute :credentials, Credentials, public?: true
  end
end

test "saving attributes on nested, embedded resources" do
  attrs = %{
    "name" => "Test Service",
    "credentials" => %{
      "username" => "test",
      "password" => "password"
    }
  }

  changeset =
    ServiceConfig
    |> Ash.Changeset.new()
    |> Ash.Changeset.for_create(:create, attrs, domain: Domain)

  dbg(changeset.errors)
  # changeset.errors #=> [
  #   %Ash.Error.Invalid.NoSuchInput{
  #     calculation: nil,
  #     resource: Ash.Test.Changeset.ChangesetTest.Credentials,
  #     action: :create,
  #     input: "password",
  #     inputs: MapSet.new([:username, "username"]),
  #     did_you_mean: [],
  #     splode: Ash.Error,
  #     bread_crumbs: [],
  #     vars: [],
  #     path: [:credentials],
  #     stacktrace: #Splode.Stacktrace<>,
  #     class: :invalid
  #   }
  # ]

  assert changeset.valid?
end
```

I also tried setting this attributes like this, and go the same result:

```elixir
changeset =
  ServiceConfig
  |> Ash.Changeset.new()
  |> Ash.Changeset.for_create(:create, %{}, domain: Domain)
  |> Ash.Changeset.force_change_attributes(attrs)
```

**Expected behavior**

The changeset should should be valid, and all the nested attributes should be set.

**Runtime**
 - Elixir version 1.17
 - Erlang version 26
 - OS MacOS 14
 - Ash version `main`
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Ah, okay I see what's happening here. So the `force_change_attribute` doesn't "thread through" to the creation of the embedded resource. An embedded resource is a type where casting input is equivalent of calling a create action on the nested data.

So your options here would be:

1. make the nested attributes public
2. modify the primary create action to accept those attributes
```elixir
actions do
  defaults [create: [:foo, :bar], ...
end
```
3. pass structs instead of input maps. If you pass structs, they are used "as is" (because no external interface can provide a struct).
i.e ```elixir
%{credentials: %Credentials{....}}
```

There isn't any mechanism to do a sort of "cascading force change". The embedded type encapsulate the way you interact with its internals.

**Comment by zachdaniel** [comment]
The main insight from above may be that you can `accept` attributes even if the attribute is `public?: false`. This only works with explicit accept lists, because `:*`  is only public attributes.

**Comment by moxley** [comment]
Cool. Thanks @zachdaniel. I ended up implementing another solution, but probably not as elegant as the ones you suggested.
