### ISSUE TITLE
Calculation dependencies specified in calculation modules *are* returned with the data? 

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#1312]
**Describe the bug**
Not sure if its a bug per se, but I know we specifically say that you don't always have access to any dependencies loaded while calculating a calculation. For inline expression calculations this seems to hold true, but for calculations in modules not always? 

**To Reproduce**

An `Album` resource that has a `year_released` integer attribute, and a couple of calculations:

```elixir
  calculations do
    calculate :years_ago, :integer, expr(2024 - year_released)
    calculate :string_years_ago_module, :string, CalculateStringYearsAgo
    calculate :string_years_ago_expr, :string, expr("wow, this was released " <> years_ago <> " years ago!")
  end
```

The CalculateStringYearsAgo module is defined like:

```elixir
defmodule CalculateStringYearsAgo do
  use Ash.Resource.Calculation

  def load(_query, _opts, _context), do: [:years_ago]

  def calculate(records, _opts, _context) do
    Enum.map(records, fn record ->
      "wow, this was released #{record.years_ago} years ago!"
    end)
  end
end
```

When testing in iex, the `expr` version of the calculation doesn't return the `years_ago` field:

```iex
iex(7)> Tunez.Music.get_album_by_id("35db271a-e63c-4338-af06-0884ba60ff4c", load: [:string_years_ago_expr])
{:ok,
 #Tunez.Music.Album<
   string_years_ago_expr: "wow, this was released 7 years ago!",
   string_years_ago_module: #Ash.NotLoaded<:calculation, field: :string_years_ago_module>,
   years_ago: #Ash.NotLoaded<:calculation, field: :years_ago>,
   ...
```

But the `module` version of the calculation does:

```iex
iex(13)> Tunez.Music.get_album_by_id("35db271a-e63c-4338-af06-0884ba60ff4c", load: [:string_years_ago_module])
{:ok,
 #Tunez.Music.Album<
   string_years_ago_expr: #Ash.NotLoaded<:calculation, field: :string_years_ago_expr>,
   string_years_ago_module: "wow, this was released 7 years ago!",
   years_ago: 7,
   ...
```

Is this something we care about? I know it can introduce subtle bugs with data being loaded/not loaded, is there something we need to address?

**Expected behavior**

I would expect neither version of the calculation to return the `years_ago` value as part of the Album data.

**Runtime**
 - Elixir version 1.17.0-otp-27
 - Erlang version 27.0
 - OS macOS Sonoma
 - Ash version 3.1.4

**Comment by zachdaniel** [comment]
The only rule is that data is not *guaranteed* to be there unless you explicitly state it. It would be expensive (from a performance standpoint) to clear out any already loaded fields, and we try to keep that process optimized. It definitely *can* cause misunderstandings and bugs, but the performance trade-off is not worth it.
