### ISSUE TITLE
Compilation error in file lib/ash/policy/authorizer/authorizer.ex

### ISSUE THREAD

**Issue by briankariuki** [ash-project/ash#1358]
**Describe the bug**
I'm getting this error when I build my project in github actions. It works perfectly fine in dev mode and compiles.

```
==> ash
Compiling 478 files (.ex)

== Compilation error in file lib/ash/policy/authorizer/authorizer.ex ==
** (CompileError) Elixir.Ash.Policy.Authorizer:1: function '__set_and_validate_options__'/2:
  Internal consistency check failed - please report this bug.
  The following label(s) were referenced but not defined:
  11 13 18 

    (stdlib 5.2.3) lists.erl:1686: :lists.foreach_1/2
could not compile dependency :ash, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ash --force", update it with "mix deps.update ash" or clean it with "mix deps.clean ash"
```

**To Reproduce**
I have in my mix.exs file ash 3.2.1
```
{:ash, "~> 3.2.1"},
```

**Expected behavior**
Project to compile fine. I have had a couple of runs with this same ash version and it worked. 

**Runtime**
 - Elixir version: 1.17.0
 - Erlang version: 26.2.5
 - OS: Ubuntu latest
 - Ash version: 3.2.1
 - any related extension versions

**Comment by zachdaniel** [comment]
This should be fixed with the latest `spark` version.
