### ISSUE TITLE
ash.gen.resource errors out with --extend

### ISSUE THREAD

**Issue by albinkc** [ash-project/ash#1373]
**Describe the bug**
ash.gen.resource errors out when --extend is used

**To Reproduce**

1. Create a new project with igniter
```
mix igniter.new helpdesk \
--install ash@github:ash-project/ash,\
ash_postgres@github:ash-project/ash_postgres,\
ash_phoenix@github:ash-project/ash_phoenix \
--with phx.new \
--extend postgres
```
2. Add a resource with --extend postgres as per the example given in docs
```
mix ash.gen.resource Helpdesk.Support.Ticket \
  --default-actions read,create,update,destroy \
  --uuid-primary-key id \
  --attribute subject:string:required:public \
  --relationship belongs_to:representative:Helpdesk.Support.Representative \
  --timestamps \
  --extend postgres
```

This returns the following error:
```
 (Mix) Could not invoke task “ash.gen.resource”: 1 error found!
–extend : Missing argument of type keep
```
Manually trying to extend the resource with postgres after omitting --extend in the first step errors out like so:
```
% mix ash.patch.extend Helpdesk.Support.Ticket postgres
Issues during code generation
* Could not find module to extend: Elixir.Helpdesk.Support.Ticket
``` 

**Runtime**
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Elixir 1.17.1 (compiled with Erlang/OTP 27)
 macOS 15.1 Beta (24B5009l)
ash@b5d4532

**Additional context**

**Comment by zachdaniel** [comment]
I was able to reproduce and resolve the first one in `igniter`. However, I was not able to reproduce the second one. Please try w/ the latest igniter and ash version to confirm if the second issue is resolved.

To update igniter, `mix deps.update igniter`.

Thank you for the report!

**Comment by albinkc** [comment]
Yup, both ways to extend postgres works now. Thank you for the quick fix!
