### ISSUE TITLE
Warn on expression with `== nil` or convert to `is_nil`

### ISSUE THREAD

**Issue by maennchen** [ash-project/ash#1377]
**Is your feature request related to a problem? Please describe.**
When writing an expression containing `something == nil`, this is literally translated to SQL. In SQL however nothing is equal to `NULL`.

**Describe the solution you'd like**

Warn user to use `is_nil(something)` instead.

**Describe alternatives you've considered**

Convert `== nil` to `is_nil`.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

No changes in interface.

**Additional context**

> Do not write `expression = NULL` because `NULL` is not “equal to” `NULL`. (The null value represents an unknown value, and it is not known whether two unknown values are equal.)

https://www.postgresql.org/docs/current/functions-comparison.html

**Comment by zachdaniel** [comment]
Addressed in 793cd715a7e9278989543804f612bf381f8a358d

**Comment by maennchen** [comment]
Awesome ❤️
