### ISSUE TITLE
The `true` and `false` values of the `countable` option in `pagination` behave the same way.

### ISSUE THREAD

**Issue by nallwhy** [ash-project/ash#1412]
**Describe the bug**

`needs_count?` doesn't consider whether `countable` is `true` or `false`.

```elixir
needs_count? =
    action.pagination && page &&
      (page[:count] == true ||
         (page[:count] != false and action.pagination.countable == :by_default))
```

https://github.com/devall-org/ash/blob/53dd555e037354a91ed4cf143ea55b1af24ec9d4/lib/ash/actions/read/read.ex#L2132

**To Reproduce**

Changing all `countable: true` to `countable: false` in `Ash.Actions.PaginationTest` does not cause any test failures.

**Expected behavior**

If `countable` is `false`, returns exception when `page[:count]` is `true`.

**Runtime**
 - Elixir version: 1.17
 - Erlang version: 26
 - OS: mac
 - Ash version: 3.4.1
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Fixed in 9b0fb15ecb1d2ad30b5368ca4da69a65bcd3b324
