### ISSUE TITLE
The selection criteria for `keyset` and `offset` in the pagination **query** and the **return** are different.

### ISSUE THREAD

**Issue by nallwhy** [ash-project/ash#1413]
**Describe the bug**

In the query, if both `keyset` and `offset` of pagination are `true`, it is classified as `keyset`.

```elixir
paginated =
    cond do
      page_opts[:before] || page_opts[:after] ->
        keyset_pagination(query, pagination, page_opts)

      page_opts[:offset] ->
        limit_offset_pagination(query, pagination, page_opts)

      pagination.offset? && pagination.keyset? -> # <------------ here
        keyset_pagination(query, pagination, page_opts)

      pagination.offset? ->
        limit_offset_pagination(query, pagination, page_opts)

      true ->
        keyset_pagination(query, pagination, page_opts)
    end
```

https://github.com/ash-project/ash/blob/55f1ead24fa708a6cc356f289adeb855b72a6bcd/lib/ash/actions/read/read.ex#L2404

In the return, if both `keyset` and `offset` of pagination are `true`, it is classified as `offset`.

```elixir
if page_opts[:offset] do
  Ash.Page.Offset.new(data, count, original_query, more?, opts)
else
  cond do
    action.pagination.keyset? && (page_opts[:after] || page_opts[:before]) ->
      Ash.Page.Keyset.new(data, count, sort, original_query, more?, opts)

    action.pagination.offset? && action.pagination.keyset? -> # <---------------- here
      Ash.Page.Offset.new(data, count, original_query, more?, opts)

    action.pagination.offset? ->
      Ash.Page.Offset.new(data, count, original_query, more?, opts)

    true ->
      Ash.Page.Keyset.new(data, count, sort, original_query, more?, opts)
  end
end
```

https://github.com/ash-project/ash/blob/55f1ead24fa708a6cc356f289adeb855b72a6bcd/lib/ash/actions/read/read.ex#L1732

This appears to be a mistake, as the second and third conditions in the `cond` statement are redundant, although it seems intentional when looking at the test code.

```elixir
test "it defaults to offset pagination" do
  assert %Ash.Page.Offset{} = Ash.read!(User, action: :both_optional, page: [limit: 10])
end
```

https://github.com/ash-project/ash/blob/55f1ead24fa708a6cc356f289adeb855b72a6bcd/test/actions/pagination_test.exs#L893

The important issue is that, while it is possible to explicitly request an offset page by inputting [page: [offset: 0]], there is no way to explicitly request a keyset page because it is difficult to arbitrarily set the `after` or `before` opts for keyset pagination.

To address this, it would be ideal to allow the pagination type to be explicitly specified or to prioritize keyset pagination when only the limit is provided.

**To Reproduce**

https://github.com/ash-project/ash/blob/55f1ead24fa708a6cc356f289adeb855b72a6bcd/test/actions/pagination_test.exs#L893

**Expected behavior**

I hope there will be a way to receive `Ash.Page.Keyset` as the result of the first pagination query.

**Runtime**
 - Elixir version: 1.17
 - Erlang version: 26
 - OS: mac
 - Ash version: 3.4.1
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
This behavior will change in 4.0. However, to adopt it today you can use `config :ash, :default_page_type, :keyset`
