### ISSUE TITLE
`return_destroyed?: true` destroy option not honoured by `AshArchival`.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash#1433]
**Describe the bug**

When calling `Ash.destroy(archiveable_record, return_destroyed?: true)` we simply receive `:ok`.

**To Reproduce**

Will open a repro PR

**Expected behavior**

Should receive the record with the `archived_at` attribute set.

**Comment by zachdaniel** [comment]
This is a generalized issue of soft destroys not honoring `return_destroyed?`. Fixing in core.
