### ISSUE TITLE
Typo relating to no_filter_static_forbidden_reads?

### ISSUE THREAD

**Issue by ahey** [ash-project/ash#1436]
With the [recently added `no_filter_static_forbidden_reads?` option](https://github.com/ash-project/ash/blob/main/lib/ash/policy/authorizer/authorizer.ex#L1562), we have:

```elixir
Keyword.get(
  Application.get_env(:ash, :policy, []),
  :no_filter_static_forbidden_reads?,
  true
)
```

However, the [getting started guide](https://github.com/ash-project/ash/blob/main/documentation/tutorials/get-started.md?plain=1#L260) instructs to add:
```
config :ash, :policies, no_filter_static_forbidden_reads?: false
```

We should either change the former code from `policy` to `policies`, or the latter from `policies` to `policy`. I didn't know which way round it should be so have not submitted a PR.

**Comment by zachdaniel** [comment]
Oops 🤦 , thanks for pointing this out. I'll cut a new release with this using the correct configuration.
