### ISSUE TITLE
New type of aggregate - `one`? `through`? `copy`?

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#1447]
**Is your feature request related to a problem? Please describe.**

I often find myself wanting simple "through"-type aggregates for a belongs_to or has_one relationship to copy a field to another resource, eg.

```elixir
calculate :verb_name, :string, expr(verb.name)
```

(when the resource belongs_to a verb)

More than once this has bitten me when I accidentally get the wrong type for the calculation. (Most recently, saying an enum type was a string.) With aggregates, the type can be automatically inferred, so these kinds of bugs can be avoided.

**Describe the solution you'd like**

A new type of aggregate, so I could write something like:

```elixir
aggregates do 
  # copy, or one, or through, etc.
  copy :verb_name, :verb, :name
end
```

**Describe alternatives you've considered**

Currently I do it with expressions, which works for simple attributes, but not for relationships.

For relationships, I've also tried a `has_many` with no attributes, eg:

```elixir
has_many :segments, Segment do
  no_attributes? true
  filter expr(parent(latest_published_version.id) == version_id)
end
```

But that didn't work either, I can't remember why.

In the end, for the generic case, I wrote a custom module to load + copy relationships across.

```elixir
defmodule MyApp.Forwarder do
  @moduledoc """
  A calculation that "forwards" a requested field to a given relationship.
  """
  use Ash.Resource.Calculation

  def load(_query, opts, _context) do
    [{opts[:relationship], [opts[:key]]}]
  end

  def calculate(records, opts, _context) do
    Enum.map(records, fn record ->
      case Map.fetch!(record, opts[:relationship]) do
        nil ->
          Keyword.get(opts, :default, [])

        records when is_list(records) ->
          Enum.map(records, fn record -> Map.fetch!(record, opts[:key]) end)

        record ->
          Map.fetch!(record, opts[:key])
      end
    end)
  end
end
```

**Comment by zachdaniel** [comment]
I think the `first` aggregate covers this case?

**Comment by sevenseacat** [comment]
Wait what!? I could have sworn I tested that first and it returned nil. 

Okay so that works for simple attributes (I have some code to rewrite...) but not for relationships. I guess the general relationship case would be better served by a `through` relationship, which there's already issues for. Never mind me!
