### ISSUE TITLE
Ash.bulk_update does not skip resource validations when using skip_global_validations?

### ISSUE THREAD

**Issue by zeneodev1** [ash-project/ash#1464]
Related to https://github.com/ash-project/ash/issues/1414

**Describe the bug**
`Ash.bulk_update` does not skip resource-level validations even when the option `skip_global_validations?: true` is passed. This causes resource validations to still be triggered during bulk updates, which contradicts the expected behavior of skipping validations.

**To Reproduce**
```elixir
defmodule MyApp.MyDomain.MyResource do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: MyApp.MyDomain

  validations do
    # my validations here
  end

  actions do
    update :increment_index do
      change increment(:index, amount: 1)
      skip_global_validations? true
    end
  end
end
```

**Expected behavior**
Resource-level validations should be skipped when `skip_global_validations?: true` is passed in the options. The bulk update should proceed without triggering any resource validation checks.

 **Runtime**
 - Erlang/OTP 26
 - Elixir 1.16.0
 - Ash 3.4
 - Ash postgres 2.3

**Comment by zachdaniel** [comment]
🤔 interesting, I'm looking at the code that should prevent that from happening. Is it applying the global validation? Or are you getting a warning about a non atomic validation that is contained in global validations perhaps?

**Comment by zeneodev1** [comment]
No warning, it applies the global validation to the query.
