### ISSUE TITLE
Bulk actions ignore `around_action` hooks

### ISSUE THREAD

**Issue by vonagam** [ash-project/ash#1473]
Bulk actions currently silently ignore `around_action` hooks.

Also bulk actions do not add `:action` tracer spans.

(I've reported it before on Discord, repeating just to keep track of it.)

**Comment by zachdaniel** [comment]
I thought I fixed the around action issue. Can you confirm that's still broken in latest ash?

As for the other one, we probably need to add new span types for that, specifically "atomic_update" and "bulk_action_batch".

**Comment by vonagam** [comment]
I'm on `3.4.20` and based on what I see they do not run.

Looking at codebase I see that around hooks are executed in `Ash.Changeset.with_hooks` but that method is not used in bulk actions, only normal ones.

The only reference to around hooks in bulk is [this check](https://github.com/ash-project/ash/blob/a1473bbe0ee1d8262bbb9436a8266bb14edcb4b8/lib/ash/actions/update/bulk.ex#L1515) in bulk update. Am I missing something?

**Comment by vonagam** [comment]
Hm... so that check, as I understand, should force normal execution of an action if there are those hooks present.

But it applies only to bulk update, there is no such code for bulk create/destroy.

**Comment by zachdaniel** [comment]
Got it. We need it to apply to all three action types. Would you mind making a PR for that?
