### ISSUE TITLE
`require_attributes` allows missing or empty string

### ISSUE THREAD

**Issue by RoyalIcing** [ash-project/ash#1475]
**Describe the bug**
I have an attribute `:some_uuid` that is define as nil-able, but for an update action I want it to be required using Ash validation.

My first instinct was `accept` and TIL that `require_attributes` can make these “required”.

```elixir
accept [:some_uuid]
require_attributes [:some_uuid]
```

But what I had to settle on is an `argument` instead:
```elixir
argument :some_uuid, :uuid, allow_nil?: false
change set_attribute(:some_uuid, arg(:some_uuid))
```

This then correctly errs when `AshPhoenix.Form.submit` is passed `%{some_uuid: ""}` or `%{}`. The `required_attributes` approach did not err with this input.

**To Reproduce**
```elixir
  actions do
    update :set_foo do
      accept [:some_uuid]
      require_attributes [:some_uuid]
    end
  end
  
  attributes do
    attributes do
      uuid_primary_key :id

      attribute :some_uuid, :uuid
    end
  end
```

Note: I’m also using `AshStateMachine`, I don’t know if that would interfere.

**Expected behavior**
I expect `require_attributes` to behave like `allow_nil?: true`, which is what its documentation even say it tries to replicate the behaviour of.

**Runtime**
 - Elixir version `1.16.3`
 - Erlang version `V14.2.5.1`
 - OS `macOS Sonoma 14.7`
 - Ash version `3.4.8`
 - any related extension versions

**Additional context**
It’s an Alembic project.

**Comment by zachdaniel** [comment]
Right, so this is interesting. This actually *is* replicating the behavior of `allow_nil?: false`. `allow_nil?: false` on an attribute allows not specifying the attribute if the current value is non-nil.

So if the value of `:some_uuid` was currently `nil`, you'd get an error. 

This is pretty confusing behavior, but adjusting the behavior isn't straightforward. Aside from being a breaking change, it's also a more aggressive validation than we currently have. 

Given that this isn't technically a "bug", I'm going to close this issue. I hesitate to add a new option that just adds to the lexicon required for update actions, and we can't change this now w/o it being a breaking change for users. The argument + change is pretty much the answer at this point. We can revisit the concepts on a major release.

**Comment by zachdaniel** [comment]
On further investigation, there is one more nuance to the current behavior. Specifically `require_attributes` on update only applies to changing attributes.

**Comment by zachdaniel** [comment]
I did find some issues with `require_attributes` behavior on `update` actions, specifically around atomics and around setting values that are already nil to `nil` again. But at the end of the day I still don't think it will do what you want.
