### ISSUE TITLE
Ash.read/2 with `count: true` and a filter will return the count of all records, unfiltered

### ISSUE THREAD

**Issue by allenwyma** [ash-project/ash#1481]
**Describe the bug**
I'm applying a filter in the page params using `page: [filter: filter, count: true]` and I'm getting back a full count of all records. I'm expecting that the count will be based on the filter I've passed in.

**To Reproduce**
Apply a filter to limit total records and ask for the count, and the full count should be returned.

**Expected behavior**
I'm expecting that when I apply a filter in the page params, that this will be applied to the count and give me an accurate count based on the filtered records.

**Runtime**
 - Elixir version 1.17.3
 - Erlang version 27.1
 - OS Mac OS
 - Ash version 3.4.21
 - any related extension versions ash_postgres 2.4.2

**Comment by zachdaniel** [comment]
The `filter` option when used in pagination like this is not meant to reflect in the full count. The query you are paginating should itself be filtered if you want it to be factored into the count.

**Comment by allenwyma** [comment]
Okay so I should use Ash.Query.filter(Resource, filter)? I think I tried that and was getting errors. Do I need to use the pin operator or is it another function?

**Comment by zachdaniel** [comment]
You do need to use the pin operator, or use `Ash.Query.do_filter(Resource, filter)`

**Comment by allenwyma** [comment]
Applying directly to the query gives me an error saying i cannot compare nil:

```
[error] GenServer #PID<0.2526.0> terminating
** (ArgumentError) comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead
    (ecto 3.12.3) lib/ecto/query/builder.ex:1188: Ecto.Query.Builder.not_nil!/1
    (ash_sql 0.2.32) lib/expr.ex:914: anonymous fn/3 in AshSql.Expr.default_dynamic_expr/6
    (ecto 3.12.3) lib/ecto/query/builder/dynamic.ex:83: Ecto.Query.Builder.Dynamic.expand/3
    (ecto 3.12.3) lib/ecto/query/builder/dynamic.ex:53: Ecto.Query.Builder.Dynamic.fully_expand/2
    (ecto 3.12.3) lib/ecto/query/builder/filter.ex:133: Ecto.Query.Builder.Filter.filter!/7
    (ash_sql 0.2.32) lib/filter.ex:47: anonymous fn/2 in AshSql.Filter.add_filter_expression/2
    (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash_postgres 2.4.2) lib/data_layer.ex:2944: AshPostgres.DataLayer.filter/4
    (ash 3.4.21) lib/ash/query/query.ex:3172: Ash.Query.maybe_filter/3
    (ash 3.4.21) lib/ash/query/query.ex:3043: Ash.Query.data_layer_query/2
    (ash 3.4.21) lib/ash/actions/read/read.ex:2249: Ash.Actions.Read.fetch_count/4
    (ash 3.4.21) lib/ash/actions/read/read.ex:529: anonymous fn/8 in Ash.Actions.Read.do_read/5
    (ash 3.4.21) lib/ash/actions/read/read.ex:883: Ash.Actions.Read.maybe_in_transaction/3
    (ash 3.4.21) lib/ash/actions/read/read.ex:269: Ash.Actions.Read.do_run/3
    (ash 3.4.21) lib/ash/actions/read/read.ex:81: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 3.4.21) lib/ash/actions/read/read.ex:80: Ash.Actions.Read.run/3
    (ash 3.4.21) lib/ash.ex:1983: Ash.read/2
```
