### ISSUE TITLE
Virtual fields?

### ISSUE THREAD

**Issue by bs1180** [ash-project/ash#149]
Hi, this looks like a really interesting project! 

I'm trying to implement a simple password hashing step like [this one](https://github.com/aaronrenner/phx_gen_auth_output/blob/v0.6.0/lib/demo/accounts/user.ex#L58-L69), but I don't see a way to have a virtual field that isn't persisted to the data layer. Is this possible?

Thanks for your help.

**Comment by zachdaniel** [comment]
Glad you like it! There are a lot of things in Ash that I've intentionally left out at the moment, waiting for solid use cases (like yours). Ideally, I'd like to implement things that are more expressive than virtual fields. In my experience, using virtual fields typically leads to having to deal with instances of a resource in "intermediate" states that are less than ideal. I think that a custom type might suit this better, e.g
```
defmodule MyApp.Password do
  use Ash.Type

  @impl true
  def storage_type, do: :string

  @impl true
  def cast_input(value) when is_binary(value) do
    {:ok, hash_password(value)}
  end

  @impl true
  def cast_stored(value) when is_binary(value) do
    {:ok, value}
  end

  @impl true
  def dump_to_native(value) when is_binary(value) do
    {:ok, value}
  end
end
```

I'll need to do a slight fix to ash_json_api if you are using that custom type along with that extension, but that is a quick fix. What do you think?

**Comment by zachdaniel** [comment]
You would then use that in your resource like so:
```
attributes do
  ... 

  attribute :password, MyApp.Password, ...
end
```

**Comment by zachdaniel** [comment]
Although, right now, that would result in the hashed password being exposed in the resource, which is likely not what you want. What I think we'd want to do to support this is actually add `arguments` to actions, and expose those arguments to custom changes. Let me work something up.

**Comment by zachdaniel** [comment]
@bs1180 are you using graphql or Json API?

**Comment by zachdaniel** [comment]
Alright, so I'm wrapping up support for the solve for it in ash, and will add support to the extensions for it shortly.  The way it will work is by supporting `arguments` for actions, which you can use in a `change`. You can use the change to read the value of the `password` argument, and set a value to the `hashed_password` value. The benefit of this approach is that you can set the `private?: true` flag on the `hashed_password` attribute, so it won't show up in any API extensions like `ash_graphql` and `ash_json_api`. You can look at the builtin changes for examples of how to write your own, but it looks like this:

```elixir
defmodule MyApp.HashPassword do
  use Ash.Resource.Change

   # This is to give you a nice interface for using this in a resource, you'll see in the section below where we use it in a resource
  def hash_password() do
    {__MODULE__, []}
  end
 
  # You'd validate any options here, but there are none
  def init(opts), do: {:ok, opts}

  def change(changeset, _opts, _context) do
    password = changeset.arguments.password
    hashed = hash_password(password)

    Ash.Changeset.change_attribute(changeset, :hashed_password, hashed)
  end
end
```

Usage in a resource:

```
defmodule MyApp.MyResource do
  use Ash.Resource, ...

  import MyApp.HashPassword, only: [hash_password: 0]

   ....

  actions do
    create :create do
      argument :password, :string
      change hash_password()
    end
  end
end
```

And that ought to do it. Once I add support for it in ash_json_api and ash_graphql, arguments will be usable in json post/patch/delete and graphql input objects :)

**Comment by zachdaniel** [comment]
Oh, also I forgot to mention, you can set arguments in the code api using `Ash.Changeset.set_argument/3` or `Ash.Changeset.set_arguments/2`. So if you wanted to use that action in code:
```
MyResource
|> Ash.Changeset.new(%{attribute: value})
|> Ash.Changeset.set_arguments(%{password: "foobar"})
|> MyApi.create!()
```

**Comment by zachdaniel** [comment]
This is all shipped, and works on both extensions now (arguments are included in graphql input objects, and in JSON:API post/patch payloads), so you should be good to go :)

Please reopen this issue if you find that this feature doesn't let you accomplish what you wanted.

**Comment by bs1180** [comment]
😍 Thanks for adding a whole new feature overnight for me, that's really wonderful. I better go and build something great now!
