### ISSUE TITLE
`parent` expression fails to reference relationship attributes.

### ISSUE THREAD

**Issue by jechol** [ash-project/ash#1506]
**Describe the bug**
The expression parent(attribute) works as expected, but parent(relationship.attribute) does not.

**To Reproduce**
I have submitted a PR that reproduces this issue: see #1505.

**Expected behavior**
The test should pass successfully.

**Comment by zachdaniel** [comment]
Thank you again for your reproduction! Issue is fixed in 1122aa86ee2d07f385ccda2a6f56ef72fc7a1a62
