### ISSUE TITLE
Ash.read!/3 with load: option doesn't pass query context

### ISSUE THREAD

**Issue by allenwyma** [ash-project/ash#1516]
**Describe the bug**
I'm setting a custom context option using a nested load, and setting `context: %{locale:"en"}`, but the related table calculation isn't receiving the context.

**To Reproduce**
```elixir
Ash.read!(Post, load: [:name, comments: [:name])
```

**Expected behavior**
Context should be passed to all loading in all calculations.

**Runtime**
 - Elixir version 1.17.2
 - Erlang version 27.1
 - OS mac OS
 - Ash version 3.4.29
 - any related extension versions

**Comment by zachdaniel** [comment]
Related resources do not receive context automatically. It must be set manually. There have been many previous discussions about setting some kind of context that *is* passed down automatically, but there are complexities with that concept. As it stands now, you'd need to do something like:

```elixir
Ash.read!(Post, load: [:name, comments: Comment |> Ash.Query.set_context(....) |> Ash.Query.load(:name)])
```
