### ISSUE TITLE
Cannot remove relationship from a belongs_to

### ISSUE THREAD

**Issue by lifeofdan** [ash-project/ash#1518]
**Describe the bug**
Cannot remove a `belongs_to` relationship on a resource.

**To Reproduce**
Test case provided on this repo. https://github.com/lifeofdan/ash_postgres/tree/can_unrelate_belongs_to

**Expected behavior**
Expected `author` to be removed from `post`.

** Runtime
 - Elixir version 1.17.2-otp-27
 - Erlang version 27.0.1
 - OS MacOs Sonoma 14.6.1
 - Ash version {:ash, ash_version("~> 3.4 and >= 3.4.28")}

**Comment by zachdaniel** [comment]
fixed in c50c9c7cdfd018e32c83c6cd3a8446f41bc3cf40

**Comment by zachdaniel** [comment]
Thank you for the reproduction

**Comment by lifeofdan** [comment]
Thank you for the fix!
