### ISSUE TITLE
Documentation: filter checks

### ISSUE THREAD

**Issue by aidalgol** [ash-project/ash#1519]
The example code for filter checks on the [Policies](https://hexdocs.pm/ash/policies.html) page includes a comment that reads,

> Filter checks don't have a `context` available to them"

But following the link right above that, [`Ash.Policy.FilterCheck`](https://hexdocs.pm/ash/Ash.Policy.FilterCheck.html), callback `filter` is documented as taking three arguments, `actor`, `context`, and `options`.

Also, is it correct for this example code snippet to be using `expr` in the body of `filter`, or is that only for inline filter-checks?

**Comment by zachdaniel** [comment]
Thanks for pointing this out :) It is correct for it to be using an `expr` in the body of the filter, but the other bit is wrong.
