### ISSUE TITLE
Docs Clarification: max_concurrency

### ISSUE THREAD

**Issue by aidalgol** [ash-project/ash#1531]
The documentation for `:max_concurrency` option to the various `bulk_*` functions (https://hexdocs.pm/ash/Ash.html) does not specify whether the default value of `0` means that only one task is used (no concurrency), or the function will automatically decide how many tasks to start.

**Comment by zachdaniel** [comment]
max_concurrency of `0` means that it does not start any tasks. I think the sentence is reasonably clear, but open to PRs to improve its clarity.

>  If set to a value greater than 0, up to that many tasks will be started to run batches asynchronously The default value is 0.

The implication is that, since its not greater than 0, no tasks are used (no async).
