### ISSUE TITLE
Support atomic updates

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash#155]
Ash doesn't support atomic updates yet, it would be nice to have those available.

**Comment by zachdaniel** [comment]
For example, the ability to update attributes via `increment`.

**Comment by zachdaniel** [comment]
I think that, for now, we should close this as its not really on the radar. Atomic updates (i.e that don't have the current value beforehand) are currently a good use case for bypassing Ash and using Ecto directly. I can see a case eventually where we can support update actions that don't require an initial value, and use `expr` to update, but that is a long way off.
