### ISSUE TITLE
Filter in resourceless update not making changes after Ash 3.4.29

### ISSUE THREAD

**Issue by haste** [ash-project/ash#1559]
**Describe the bug**

After upgrading to Ash 3.4.29 one of our update actions have stopped updating.

**To Reproduce**

The relevant code is the `logout` action in `lib/helpdesk/account/user_session.ex`:

```
    update :logout do
      change filter expr(session_uid == ^actor(:session_uid))
      accept []
      change set_attribute(:user_id, nil)
    end
```

Full minimal reproduction project: https://github.com/haste/ash_filter_in_resourceless_update_bug
Run `mix test`.

Downgrading Ash to 3.4.28 makes the test pass.

**Expected behavior**

Expected behavior is for the action to run a SQL `UPDATE` statement setting `user_id` to `null`.

**Runtime**
 - Elixir version 1.17.3-otp-27
 - Erlang version 27.1.2
 - OS Fedora Linux 40
 - Ash version 3.4.29
 - any related extension versions

**Additional context**

This was [initially reported](https://elixir-lang.slack.com/archives/C0193AHFLPN/p1729858324130499) on the Elixir slack

**Comment by zachdaniel** [comment]
This appears to have already been fixed in latest `main` of `ash` and `ash_postgres`. As such, I will close this. Those will be released this week.
