### ISSUE TITLE
Missing dependency in Phoenix app generated by Igniter command

### ISSUE THREAD

**Issue by aidalgol** [ash-project/ash#1562]
The command in `documentation/tutorials/get-started.md` to generate a Phoenix application produces an application without `ash_phoenix` in the dependencies list.

```sh
mix igniter.new helpdesk --install ash --with phx.new && cd helpdesk
```

**Comment by zachdaniel** [comment]
`{:ash_phoenix` isn't necessarily required to use `Ash` with `Phoenix`, but it would make sense to add regardless.

**Comment by zachdaniel** [comment]
Fixed in `main`.
