### ISSUE TITLE
integer_primary_key generates invalid defaults

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash#157]
**Describe the bug**
integer_primary_key defaults allow_nil? to true, which is incompatible with the :serial ecto type (see https://github.com/ash-project/ash_postgres/pull/36)

**To Reproduce**
add the following attribute:
```elixir
integer_primary_key :id
```
generate the postgres migration, the following migration is created:
```elixir
add(:id, :serial, null: true, primary_key: true)
```
run the migration, the following error is emitted:
```
** (Postgrex.Error) ERROR 42601 (syntax_error) conflicting NULL/NOT NULL declarations for column "id" of table "user_tokens"
```
**Expected behavior**
The following migration operation should be generated:
```elixir
add(:id, :serial, null: false, primary_key: true)
```

**Comment by zachdaniel** [comment]
This has been resolved.
