### ISSUE TITLE
Calcluation throwing error in a read

### ISSUE THREAD

**Issue by allenwyma** [ash-project/ash#1589]
**Describe the bug**
Calculation can load properly, but having an issue when trying to sort on the calculation.

**To Reproduce**
Will reproduce this for you in a separate project you have access to.

**Expected behavior**
Can sort without an issue.

**Runtime**
 - Elixir version 1.17.3
 - Erlang version 27.1.1
 - OS MacOS
 - Ash version 3.4.41
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
I will close this until we have a reproduction. (or maybe I already fixed it?)

**Comment by allenwyma** [comment]
We do have a reproduction. 

Please reopen and I find the branch for you.

**Comment by zachdaniel** [comment]
@allenwyma the latest on this issue is that in the branch you shared with me separately I can't reproduce, but I also don't know what I'm looking for. What kind of error does it throw? What specific code was run that produced the error?

**Comment by allenwyma** [comment]
hi @zachdaniel as said over discord: i've provided a broken test for you to help with debugging.

thank you! 🙏
