### ISSUE TITLE
Embedded resources

### ISSUE THREAD

**Issue by alexfreska** [ash-project/ash#159]
Looking for embedded resource support similar to Ecto embeds.

This would require that Ash resources without a Data Layer implement the Ash.Type behaviour.

Potential syntax:
```elixir
# single
attribute :one_something, MyResourceWithNoDataLayer
# many
attribute :multiple_somethings, {:array, MyResourceWithNoDataLayer}
```

**Comment by zachdaniel** [comment]
This has been released.
