### ISSUE TITLE
Add `UtcDatetimeUsec` type

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash#160]
It would be nice to have a `UtcDatetimeUsec` type built in; I even think it would be nice to use it by default. I'm happy to send a PR if you like, it looks like the `UtcDatetime` code can be copied here.

Question: Do we still need to configure `migration_timestamps: [type: :utc_datetime_usec]` or `@timestamps_opts [type: :utc_datetime_usec]`? I assume that Ash is quite explicit so the answer should be *No*, I'm leaving this note just in case.

**Comment by zachdaniel** [comment]
You are correct that we would not need that type of configuration. I'm happy to have it added 😀 

Would you be interested in making a PR to add it?

**Comment by zimt28** [comment]
Done, can we use it as default for `create_timestamp` and `update_timestamp`?

**Comment by zachdaniel** [comment]
That's a tough one, primarily because it would break anyone who is currently using it unless we add provisions for it in the ash_postgres migration generator. And even then it would still be unexpected/break because people wouldn't think they needed new migrations. You might be better of creating a macro called `used_create_timestamp` in your project that does `create_timestamp unquote(name), type: <type>`.

Then you'd import that into your resources.

**Comment by zimt28** [comment]
Yes, I think I read a comment by José where he described the same issue with Phoenix timestamps. As Ash is "pre ~~1.0~~ 2.0" I assumed it would be a chance to get it right in the first place.

**Comment by zachdaniel** [comment]
Good point, let's do it :) we'll just write a short guide on upgrading via adding a regular migration and changing the column type of any date time columns.

**Comment by zimt28** [comment]
I don't know where to put the guide but it would include instructions like:

1. Create a migration:
```
mix ecto.gen.migration update_timestamp_types
```

2. Modify the type of all fields that use timestamps:
```elixir
defmodule YourApp.Repo.Migrations.UpdateTimestampTypes do
  use Ecto.Migration

  def change do
    alter table(:accounts) do
      modify :inserted_at, :utc_datetime_usec, from: :utc_datetime
      modify :updated_at, :utc_datetime_usec, from: :utc_datetime
    end

    alter table(:email_addresses) do
      modify :confirmed_at, :utc_datetime_usec, from: :utc_datetime
    end
  end
end

```

**Comment by zachdaniel** [comment]
How does this look to you? https://github.com/ash-project/ash#upgrading-to-1270

**Comment by zachdaniel** [comment]
The anchor link there is misbehaving, so you'll have to scroll up to the top.

**Comment by zimt28** [comment]
Looking good! As a minor improvement it might be good to add `from: :utc_datetime` in case someone needs to roll back migrations.

**Comment by zachdaniel** [comment]
Awesome, I'll tweet this guide out as well so hopefully more people see it before they are bitten.
