### ISSUE TITLE
`^atomic_ref(field)` does not work in vars for certain data types

### ISSUE THREAD

**Issue by binarypaladin** [ash-project/ash#1634]
**Describe the bug**

```
     Unknown Error

     * ** (Postgrex.Error) ERROR 42P18 (indeterminate_datatype) could not determine data type of parameter $14
```

This happens when trying to return an atomic ref in `vars` on an error.

**To Reproduce**

```elixir
@impl Ash.Resource.Validation
def atomic(_changeset, opts, context) do
  aggregate_field = Keyword.fetch!(opts, :aggregate)
  aggregate_value = Keyword.fetch!(opts, :value)

  {
    :atomic,
    [aggregate_field],
    expr(^atomic_ref(aggregate_field) != ^aggregate_value),
    expr(
      error(^Ash.Error.Changes.InvalidAttribute, %{
        field: ^aggregate_field,
        message: ^(context.message || "must equal %{value}"),
        value: ^atomic_ref(aggregate_field),
        vars: %{current_value: ^atomic_ref(aggregate_field), value: ^aggregate_value}
      })
    )
  }
end
```

So, if I pass in a value of `100` (an integer) as `aggregate_value` this all works just fine.

When I pass in `Decimal.new(100)` as `aggregate_value` I get the above error.

Here's the weird part though. You'd think the problem was maybe `value: ^aggregate_value` but, the thing that actually causes death? `current_value: ^atomic_ref(aggregate_field)`

It works fine with `100` or if I use `Decimal.new(100)` and remove `current_value: ^atomic_ref(aggregate_field),`.

**Expected behavior**
`Decimal.new(100)` would work just as well as `100`.

**Runtime**
- Elixir version 1.17.2
- Erlang version 27.0.1
- OS macOS 15.0.1
- Ash version 3.4.43

**Comment by binarypaladin** [comment]
Oh, relevant SQL w/ Decimal:

```
jsonb_build_object($13::varchar::varchar,($14),$15::varchar::varchar,(coalesce(ss1."total_asset_allocation_percentage", $16::decimal)::decimal))
```

With an integer:

```
jsonb_build_object($13::varchar::varchar,($14::bigint::bigint),$15::varchar::varchar,(coalesce(ss1."total_asset_allocation_percentage", $16::decimal)::decimal))
```

**Comment by zachdaniel** [comment]
So, I don't think that this particular application is actually possible? There isn't a concept of "the value before hooks that run after this statement and the value after". Those would both equal the same thing always.

**Comment by binarypaladin** [comment]
It works with integers. It looks like something is just getting confused about the datatype somewhere when generating the SQL inside the JSONB?

```elixir
%Ash.Error.Invalid{
  bread_crumbs: ["Returned from bulk query update: Resource.update"], 
  changeset: "#Changeset<>", 
  errors: [
    %Ash.Error.Changes.InvalidAttribute{
      field: :total_percentage,
      message: "must equal %{value}% (hint: current sum is only %{current_value}%)",
      private_vars: nil,
      value: 0,
      splode: Ash.Error,
      bread_crumbs: ["Returned from bulk query update: Resource.update"],
      vars: [{"current_value", 0}, {"value", 100}],
      path: [],
      stacktrace: #Splode.Stacktrace<>,
      class: :invalid
    }
  ]
}
```

**Comment by zachdaniel** [comment]
Hmm...I think it may be a case of having to type these expressions due to their being encoded into JSON

```elixir
  {
    :atomic,
    [aggregate_field],
    expr(^atomic_ref(aggregate_field) != ^aggregate_value),
    expr(
      error(^Ash.Error.Changes.InvalidAttribute, %{
        field: ^aggregate_field,
        message: ^(context.message || "must equal %{value}"),
        value: ^atomic_ref(aggregate_field),
        vars: %{current_value: type(^atomic_ref(aggregate_field), :decimal), value: type(^aggregate_value, :decimal)}
      })
    )
  }
```

try something like that perhaps?

**Comment by binarypaladin** [comment]
Very nice. That solves the problem and is very useful to know. Is there a good way to just infer this type or attempt to infer types in general?

I realize it cannot be perfect. I have several types that are just some variation of `:string` right now because I like baking common validations into types that are used all over the place. I wrote a little function that defaults to `:string` for the time being.

Sorta related, looking at the SQL I see a lot of this:

```
$14::decimal::decimal
```

What's with all the doubling of types?

**Comment by binarypaladin** [comment]
Another thing, is there a place where the documentation could be updated detailing this? I'm happy to clean up a couple spots with hints about this if you can point me in the right direction. (Since... this isn't really a bug, is it? Although perhaps the returned error could provide a hint. That's even better than documentation!)

**Comment by zachdaniel** [comment]
Hmm...perhaps a spot in the docs that expresses that in some expressions (like this one) we may need to hint to the query engine what the type of a given thing is for json serialization to work?
