### ISSUE TITLE
Running the `can_` functions on a domain triggers N queries if used in a list

### ISSUE THREAD

**Issue by StephanH90** [ash-project/ash#1658]
**Describe the bug**
When you use the `can_:action_name?` functions that get generated on a domain in a list, it creates 1 query for every row.

**To Reproduce**
Let's assume we have a policy like this:
```ex
policy action :delete do
    authorize_if relates_to_actor_via(:users)
    # I have also tried other flavours such as:
    # authorize_if expr(exists(users, id == ^actor(:id))) # <- also produces a query for every row
end
```
A common use-case would be to only show the delete button if this authorization passes. However, if you use the function `MyDomain.can_delete?(some_resource, user)` you actually get 1 query for every resource.

**Expected behavior**
I would have assumed that Ash tries to use the preloaded relationship if possible.

**Comment by zachdaniel** [comment]
You get 1 query for *every record*? That shouldn't be the case.

**Comment by zachdaniel** [comment]
I think? I'll have to double check that implementation. Could you provide a more concrete example of how you're calling it?

**Comment by StephanH90** [comment]
@zachdaniel I prepared a little MR that illustrates the problem: https://github.com/ash-project/ash/pull/1661/files

Otherwise, here is the main bit of my change:

```ex
test "a can check doesn't rerun queries" do
      start_supervised({Ash.Test.Authorizer, {}})

      user =
        User
        |> Ash.Changeset.for_create(:create)
        |> Ash.create!(authorize?: false)

      post =
        Post
        |> Ash.Changeset.for_create(:create, %{title: "test", user_id: user.id})
        |> Ash.create!(authorize?: false)
        |> Ash.load!(:user)

      # ! This causes an extra SQL query (!not when running against ETS)
      Domain.can_update_post_title(user, post)

      # In my actual usecase I have something like this in my liveview:
      # <div :for={item <- @items}>
      #   <button :if={MyDomain.can_delete(@current_user, item)}>Delete</button>
      #   {item.name}
      # </div>

      # This causes 1 query for every row.
    end
```

**Comment by zachdaniel** [comment]
So, I'm not actually able to reproduce this. I've written a test in `ash_postgres` that shows that when using `can?` it actually *does* properly leverage the loaded relationship. See that test here: https://github.com/ash-project/ash_postgres/commit/25882e936aad8d00c5fa08181baba51d2c23c769

Is it possible there is something that differentiates your policies/checks from that test? I've fixed an unrelated check type in `main`, perhaps you can try `ash` main and see if that helps?

**Comment by StephanH90** [comment]
I will try and also check our your test to see if I can reproduce something, thx!
