### ISSUE TITLE
Sort should be loaded only if the currect (not simply any) action/read uses keyset pagination

### ISSUE THREAD

**Issue by vonagam** [ash-project/ash#1665]
Reminder about issue found on Discord. Current logic of [`load_and_select_sort`](https://github.com/ash-project/ash/blob/af3adb9c9463f983094d3d90f9fb0ee710fd8210/lib/ash/actions/read/read.ex#L2680C8-L2693):

```elixir
defp load_and_select_sort(query) do
  query.resource
  |> Ash.Resource.Info.actions()
  |> Enum.any?(&match?(%{pagination: %{keyset?: true}}, &1))
  |> if do
    query.sort
    |> Enum.map(&elem(&1, 0))
    |> then(fn load ->
      Ash.Query.load(query, load)
    end)
  else
    query
  end
end
```

Here sort is added to loaded fields if **any** read action of a resource supports keyset pagination (which is set to true for default primary generated `read`).

**Comment by zachdaniel** [comment]
I've added a new config for this, and made it the default in generators, commenting int he code for us to change it when 4.0 is released. Please try it out and let me know.

b9107f7bb4ef246083286cf1b0bcc82e3429e2cc

```
config :ash, :show_keysets_for_all_actions?, false
```

**Comment by vonagam** [comment]
I was about to try it but looking at the tests seems like ash_graphql/ash_json_api/ash_sqlite/ash_authentication all fail with the same message now.

**Comment by zachdaniel** [comment]
Oops, fixed :)

**Comment by vonagam** [comment]
Ok, seems to be working so far with `config :ash, :show_keysets_for_all_actions?, false`. Waiting for release now, thanks.
