### ISSUE TITLE
`return_query?` option for reads is broken

### ISSUE THREAD

**Issue by vonagam** [ash-project/ash#1667]
The code expects in multiple places only `{:ok, results}` and does not know how to handle `{:ok, results, query}` that is returned with `return_query?: true`.

**Comment by zachdaniel** [comment]
Fixed here: 1c470dd422b752187ee5a9422d1d485bc8185378

Although I only see one place it needed to be addressed. Mind pointing me at the other places you noticed?

**Comment by vonagam** [comment]
There are multiple methods where `return_query?` is listed as an option in documentation. Not sure it makes sense for all of them. But I assume it does for `read_one` and `read_first` and they currently do not handle it properly.
