### ISSUE TITLE
Treat empty values as nil

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash#167]
Currently, this is possible:

```elixir
attributes do
  attribute :title, :string, allow_nil?: false
end

{:ok, _} =
  resource
  |> Changeset.for_create(:default, %{title: ""})
  |> API.create()
```

Values with `String.trim(value) == ""` should be treated as `nil`. 

Edit: Maybe empty characters (https://emptycharacter.com/) should be replaced by space before trimming.

**Comment by zachdaniel** [comment]
We should probably implement it as a `constraint` that defaults to this behavior. We could take the name `empty_values` from ecto. https://hexdocs.pm/ecto/Ecto.Changeset.html#module-empty-values

We could also add options to trim empty characters as another constraint. We could then modify the behavior like so:

```
attribute :foo, :string,
  empty_values: [],
  replace_empty_char?: false
```

**Comment by zimt28** [comment]
I'll send a PR

**Comment by zimt28** [comment]
Gave it a try (#169)

**Comment by zachdaniel** [comment]
Done!
