### ISSUE TITLE
Api.destroy should return the resource

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash#168]
Currently `Ash.Api.destroy/2` returns just `:ok` on success. It would make sense to return `{:ok, resource}`, so it's a) similar to Ecto and b) returns the changed resource if using `soft? true`.

**Comment by zimt28** [comment]
`--exit` might not be the best name though. Maybe `--enforce-latest-migrations`.
This is how other libraries do it:
```elixir
[
  "format --check-formatted",
  "credo --strict",
  "sobelow --exit",
  "dialyzer --halt-exit-status"
]
```

**Comment by zachdaniel** [comment]
You're right, but it will be a relatively big change. Pretty much every extension uses that helper.
