### ISSUE TITLE
Feature: Support case-insensitive text in attributes

### ISSUE THREAD

**Issue by frankdugan3** [ash-project/ash#174]
**Describe the solution you'd like**
I would like first-class support for case-insensitivity for Ash resource attributes.

In Postgres, this would be implemented with the `citext` type, but we would want the Ash resource to be aware of insensitivity for other uses such as the runtime filter check.

A possible definition implementation:

```
attribute :name, :string, constraints: [case_insensitive?: true]
```

Something else to consider is that I think MySQL is case-insensitive by default. I'm not sure about other databases.

**Comment by zachdaniel** [comment]
Done!
