### ISSUE TITLE
Rename Api to API in modules for Ash 2.0

### ISSUE THREAD

**Issue by axelson** [ash-project/ash#197]
Matches better because `API` is an acronym

As discussed on discord in the #questions channel

**Comment by zimt28** [comment]
Some more acronyms to take into consideration: `GraphQL`, `JSON`, `ETS`.
There probably needs to be a special solution for `AshJsonApi`.

**Comment by adnikiforov** [comment]
> There probably needs to be a special solution for `AshJsonApi`.

`AshJSON`? Cause there is `AshJsonApi.Api` already, why state it twice?

**Comment by zimt28** [comment]
@adnikiforov It's not an extension that handles JSON but an implementation of [`JSON:API`](https://jsonapi.org/), so the main module is named after that.

**Comment by zachdaniel** [comment]
Ultimatley we've decided to continue using the convention that only the first letter of an abbreviation or acronym is capitalized.
