### ISSUE TITLE
Ash + NATS integration

### ISSUE THREAD

**Issue by byu** [ash-project/ash#200]
**Is your feature request related to a problem? Please describe.**

In my organization's growth, our monolith application is evolving into separate "bounded contexts" such that a combination of Service Mesh and Event-Driven-Architecture is likely (but not to the granularity of microservices).

NATS 2.2 provides the following messaging styles that could cover the support of SOA and EOA.
1. request-reply and fire-and-forget messaging
2. at-most-once semantics by default, and at-least-once w/ Jetstream

**Describe the solution you'd like**

The general goal would be that one could:
1. Spin up an elixir running instance so that it is subscribed to NATS subjects and trigger Ash Event handler code that would execute specific event-driven actions on ash resources; errors, etc, logged to monitoring systems.
2. An ash based RPC endpoint-over-NATS-subject that supports some sort of request-reply for Ash resource API actions, liken to HTTP+JSONAPI that Ash currently supports.
3. specify Ash notifier that can send ash events as CloudEvents to NATS subjects (named by ash resource + event type).

Specific solution design, not proposed.

**Describe alternatives you've considered**

0. Create a Plug.Nats adapter, Ash API Extension (vs JSONAPI/GraphQL) and custom Ash Nats Notifier.
1. Instead of trying to make RPC over NATS, maybe just using an existing service mesh and Phoenix for Ash API actions ala JSONAPI would be better, easier, more straight forward. (for goal 2 above)
2. Possibly creating a Plug NATS Adapter that would completely proxy HTTP over NATS.  (for goal 2 above)
3. Custom background job workers that can directly call Ash resources API (idempotent fashion?) on receipt of event messages? (for goal 1 above).
4. [Broadway](https://github.com/dashbitco/broadway) custom NATS connector, and write event handler code that directly executes Ash resource APIs?

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

Unknown at this time.

**Additional context**

Discoveries/Thoughts, please correct me if I'm wrong:

1. Cowboy Server, itself, spins up erlang processes per connection that it handles (up to max connections soft limit).

Point: Process per OS socket connection is the concurrency and limit here.

2. Plug+Plug.Cowboy, liken to ruby rack, is just `defmodules`, `init/1`, `call/2` strung together into a pipeline.  Where the `call` params are the Conn and the result of init.

Point: No processes created here, just calls to module functions.  And I'm assuming data structure immutability here for the Conn and init options.

3. Plug.Cowboy Handler does the protocol work to take the cowboy HTTP connection and request (ignoring streaming http right now) and converts it to a plug conn that plug middleware, phoenix and ash
all know and love.

4. ecto DBConnection project is how we can manage pools to the db.

Point: Pooling at the adapter is dimension of concurrency and limiting.

5. Gnats ConnectionSupervisor, ConsumerSupervisor, Connection and Consumer are each Processes in the supervision tree. All messages that come in are handled by creating additional task processes, `Task.Supervisor.async_nolink`, that either execute a module conforming to the `Gnat.Server` behavior or a given module and function.  `Gnat.Server` will do some additional error handling for us that would have to be implemented by module+function otherwise.

Point: I did not see any concurrency limits here, tasks will be spun up as fast as the consumer can process an inbound message.

Point: This is an integration point such that the given module would need to create create a plug conn and pass it on to a plug pipeline if we were to use plug. Though, my novice Elixir state isn't sure about to go about this part from a "static module" to a declared/compiled plug pipeline (with configured state).

```
  Task.Supervisor.async_nolink(state.task_supervisor_pid, Gnat.Server, :execute, [module, gnat_message])
```

Point: No concurrency limits here, calling lots of ash resource actions would probably be limited by the throughput of the DBConnection pool.

6. NATS 2.2 just got tagged in github. (a) it has headers support for messages now (b) and it has the new Jetstream feature that provides at-least-once messaging (it deprecates NATS-Streaming).

Point: I predict that the NATs community will come up with some sort of HTTP-Binding using headers+payload for service mesh; I imagine at least two solutions, which would include proxy-in-front-of-phoenix, and the Plug.Nats idea.

7. CQRS, I would think that whatever present use-case would dictate the choice of either the request-reply or fire-and-forget semantic (wrt Client). That is, we may fire off the Command-- but I prefer the idea that they are actually Intents that a handler may or may not accept, and these are more like statements of fact (Events) about user actions-- and we may want an immediate reply that the command was accepted to be processed; or it may not matter and the command gets thrown into the command bus. In the fire-and-forget, we'd likely use at-least-once semantics Kafka-style.  Either way, I agree that CQRS is a bit orthogonal to this idea/feature.

8. For request-reply semantics (services), I am reminded by a few things:
i. Derek Collison once mentioned in a podcast (regarding NATS) that one could configure the fabric so that two+ service-instances could handle each RPC request, and the requestor/client would just take and use the first response.  That is, two+ queue-groups (eg Alpha and Bravo) each with its own set of servers, and each message would be handled by each queue-group, where it load balances within the group.
ii. Shuffle Sharding
iii. Power of Two Random Choices

9. The Ash notifiers system sounds great. Sounds like one could set up Ash resources to publish events, and one would create a notifier extension that could hypothetically take the events and send them over varying NATS subjects using a custom serialization format+schema (eg CloudEvents).

Point: Outbound publishing events to NATS is more straight forward problem to tackle than a request-reply service plug that is its own "Protocol"; the idea of binding HTTP for NATS as a transport to interop HTTP Plug assumptions for Phoenix is likely even a harder problem with unclear Return-On-Investment; the inbound receipt of messages to trigger handlers may or may not be the same magnitude of difficulty (depending?) for the "request-reply service plug", but might be the one with fewer interop concerns.

10. If anyone has any links or pointers for me to take a look at, I'd love to do more exploration on the topic.

# References:
* http://ninenines.eu/docs/en/cowboy/2.8/guide/
* https://ninenines.eu/docs/en/ranch/2.0/guide/internals/
* https://www.baozi.technology/ranch-under-the-hood/
* https://github.com/elixir-ecto/db_connection
* https://github.com/nats-io/nats-server/commit/0d5b037fc3fac5395617d4a0c992f5735830965c
* https://github.com/nats-io/nats.ex/blob/master/lib/gnat/server.ex
* https://aws.amazon.com/blogs/architecture/shuffle-sharding-massive-and-magical-fault-isolation/
* https://people.cs.umass.edu/~ramesh/Site/PUBLICATIONS_files/MRS01.pdf

**Comment by zachdaniel** [comment]
My first suggestion would be to set up a very simple application that has these characteristics using the "lower level" tools that exist right now. For instance, setting something up that uses Gnats + Ecto to 

* accept specific requests over NATS (e.g service mesh style) and respond in some fashion (probably a guide on best practices on this kind of thing in the nats docs)
* hook into events to react to them, e.g EOA
* publish messages as a result of those changes.

Then what we can do is talk about how we can 
1.) replace the ecto schemas with ash resources (you could also just start there if you wanted)
2.) look at how we can add declarative configuration to those resources to abstract away the imperative code needed to power your prototype
3.) clean it up/package it up as an extension

**Comment by zachdaniel** [comment]
I'm going to close this for now as its highly specific to an individual use case and has been open for a while.
