### ISSUE TITLE
Picosat Installation Issues

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#201]
This is a placeholder that can be used for search to contain any issues people run into with picosat installation.

Alpine linux w/ muslc
```bash
In file included from pycosat.c:19:
picosat.c:8150:10: fatal error: sys/unistd.h: No such file or directory
 #include <sys/unistd.h>
```
Solution: https://stackoverflow.com/questions/52894632/cannot-install-pycosat-on-alpine-during-dockerizing

**Comment by simpers** [comment]
When dockerizing my test app with Ash I ran into this issue and I found the solution here:

https://stackoverflow.com/questions/52894632/cannot-install-pycosat-on-alpine-during-dockerizing
