### ISSUE TITLE
Changeset.for_* functions to use the primary action by default

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash#202]
**Is your feature request related to a problem? Please describe.**
When calling `for_create` (and siblings), i'm noticing that I'm only using the primary action for that action type. In an effort to identify extraneous boilerplate in my live views, I've noticed I'm doing this a lot:

```elixir
Changeset.for_create(MyApp.Resource, :create)

# which kind of sticks out in a pipeline

MyApp.Resource
|> Changeset.for_create(:create)
```

**Describe the solution you'd like**
I'd like `for_create` and siblings to use the primary action. If I want to use an action other than the primary, I'd like to pass the action in as an option:

```elixir
Changeset.for_create(MyApp.Resource)

Changeset.for_create(MyApp.Resource, action: :my_special_action)
```

**Describe alternatives you've considered**
Create a helper and use `Ash.Resource.Info.primary_action!(resource, :create).name` to get the primary action name

**Express the feature either with a change to resource syntax, or with a change to the resource interface**
As above

**Additional context**
I'm only using in a forms / live view context, so haven't considered how this would effect the api extensions

**Comment by MrFlorius** [comment]
This will be very convenient! I've used Ash for like half a day and have a similar thought.

**Comment by totaltrash** [comment]
The more I'm using Ash, the more I'm finding this is a non issue. I'm actually feeling like that it could cause me issues later on, as I might decide to change which action is primary. It's probably better to be explicit.

**Comment by zachdaniel** [comment]
@totaltrash i tend to agree. Fetching the primary action of a given type is very easy, so people are free to implement their own function that does this.
