### ISSUE TITLE
add .tool-versions to .gitignore

### ISSUE THREAD

**Issue by dkuku** [ash-project/ash#212]
I'm using different version of elixir and I need to remember every time to not commit this file. 
I think its per user setting and this should be excluded from the repo

**Comment by zachdaniel** [comment]
Sounds good to me, seems like low hanging fruit if anyone wants to take it.

**Comment by dkuku** [comment]
I did this, so I don't have to think about it anymore

**Comment by zachdaniel** [comment]
Awesome, thanks!
