### ISSUE TITLE
"cannot be changed" when trying to create resource with private attribute

### ISSUE THREAD

**Issue by michaelst** [ash-project/ash#217]
**Describe the bug**
Can't create a resource with a private attribute

**To Reproduce**
I have this private attribute
```
    attribute :firebase_id, :string, private?: true, allow_nil?: false
```

When I try to create the user on sign up like this
```
Ash.Changeset.new(User, %{firebase_id: firebase_id})
    |> Api.create()
```

I get this error
```
errors: [%Ash.Error.Changes.InvalidAttribute{changeset: nil, class: :invalid, field: :firebase_id, message: "cannot be changed", path: [], query: nil, stacktrace: #Stacktrace<>, vars: []}],
```

**Expected behavior**
I don't want this id to be exposed outside of the system, but I need to be able to set it internally. I'm not seeing anything in the docs for a separate create/insert function I can use that would bypass this restriction.

**Comment by zachdaniel** [comment]
Hello! There are a few ways to do what you're trying to do.

1.) `Ash.Changeset.force_change_attribute/3`

```elixir
User
|> Ash.Changeset.new(%{})
|> Ash.Changeset.force_change_attribute(:firebase_id, firebase_id)
|> Api.create()
```

2.) action arguments, combined with an action-specific `change

```elixir
defmodule MyApp.SetFirebaseId do
  use Ash.Resource.Change
  
  def change(changeset, _, _) do
    firebase_id = Ash.Changeset.get_argument(changeset, :firebase_id)
    Ash.Changeset.force_change_attribute(changeset, :firebase_id, firebase_id)
  end
end

# In your resource:
# by default, an action of each type is defined for you. If you define an action of that type (with any # name), it replaces the default implementation. Their names are :create, :update, :destroy and :read
actions do
  create :create do
    argument :firebase_id, :string, allow_nil?: false
    
    change MyApp.SetFirebaseId # <- add a `change` to the action, like a `plug` but for changesets
  end
end

# Now you can say
Ash.Changeset.for_create(User, :create, %{firebase_id: firebase_id})
```



One more note:

You likely don't want to use `Ash.Changeset.new/2`. It is available for when you want to do some low-level work, but you should generally reach instead for the action-specific changeset functions (`Ash.Changeset.for_create/4`, `Ash.Changeset.for_update/4`, `Ash.Changeset.for_destroy/4), or for defining a `code_interface` for your resource. See the above example of `for_create`.


Additionally, in your resource you can create a `code_interface` to give yourself named functions to call. For example:

```elixir
code_interface do
  define :create_user, action: :create
end

# Defines `create_user` and `create_user!` on your Api module.

`Api.create_user!(%{firebase_id: firebase_id})`
```
