### ISSUE TITLE
Identities does not work on ETS

### ISSUE THREAD

**Issue by florius0** [ash-project/ash#225]
**Describe the bug**
Identities does not work on `Ash.DataLayer.Ets` data layer.

> Yeah the ets layer actually just doesn't appear to use the identities which is a bug. Its not necessarily easy to enforce unique constraints on an ets resource, but at the worst case you should get a resource compilation error for a mismatch in data layer capabilities
@zachdaniel 

**To Reproduce**
```elixir
defmodule User do
  use Ash.Resource, data_layer: Ash.DataLayer.Ets
  
  identities do
    identity :unique_thing_by_user, [:thing, :user_id]
  end

  attributes do
    uuid_primaty_key :id

    attribute :thing, :string
  end
end

defmodule Api do
  use Ash.Api

  resources do
    resource User
  end
end
```
In iex:
```elixir
iex(1)> {:ok, user1} = Ash.Changeset.new(User, %{thing: "thing"}) |> Api.create()
iex(2)> {:ok, user2} = Ash.Changeset.new(User, %{thing: "thing"}) |> Api.create() # no errors here
iex(3)> Api.get(User, thing: "thing")
{:error,
 %Ash.Error.Invalid.InvalidPrimaryKey{
   changeset: nil,
   class: :invalid,
   path: [],
   query: nil,
   resource: User,
   stacktrace: #Stacktrace<>,
   value: [thing: "thing"],
   vars: []
 }}
```

**Expected behavior**
A compilation warning with info on identities support on ETS or an error on `iex(2)>` and 
```elixir
{:ok,
 %User{
   __meta__: #Ecto.Schema.Metadata<:built, "">,
   __metadata__: %{},
   aggregates: %{},
   calculations: %{},
   id: "...",
   thing: "thing"
 }}
```
on `iex(3)>`

** Runtime**
 - Elixir version 1.11.4
 - Erlang version Erlang/OTP 23 [erts-11.2]
 - OS macOS 10.15.7
 - Ash version 1.41.6

**Comment by zachdaniel** [comment]
This is now supported by the `pre_check_with`, and as of 8b10b892efc1277ec730e0e5266375a0f656def2 the ets and mnesia data layers require that option to be set.
