### ISSUE TITLE
Set tenant per process

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash#233]
Proposal: Add a way to set a tenant for the current process, it could be stored in the process dictionary.

**Comment by kernel-io** [comment]
I have been thinking of this today and think that it may be better to incorporate this functionality in a more abstract manner, i.e: we provide Ash with a MFA that would return the context to use, ie: the returned struct has actor values, and tenant values in it. This way we can store our tenant / actor in a process dictionary key if we wanted, while also leaving it open for us to store it however else we wanted.

**Comment by kernel-io** [comment]
https://github.com/ash-project/ash/commit/c9f20f1488bd5d2c7d454ca27bdc0d23c20bc21c

Closed here
