### ISSUE TITLE
Feature: Add `select` option to calculations to support making sure fields are present before proceeding

### ISSUE THREAD

**Issue by simpers** [ash-project/ash#237]
**Problem description**
The use-case for this is that currently you need to select all fields you will need in a calculation before attempting to do the calculation. If you don't know ahead of time which fields will be used in the calculation then the calculation might fail or be incorrect, depending on what your API expects.

**Problem example**
For example, using `AshGraphQL` I could create a mutation that would submit data for creation of a resource that it would not request back as the result. It does however request a calculation for its result. As it stands right now, without `always_select? true` on the fields that would affect this calculation the calculation will be incorrect in my case. I was trying to calculate a total cost of certain fields. All fields were either submitted or defaulted to 0, but I would not request all of them back. This resulted in an incorrect calculation. The fix for me for now was to add `always_select? true` to each of these **18 fields** (jeez) but it would be handier and cheaper to only request all of these upon needing them.

**Proposed solution**
@zachdaniel suggested this solution where you could just add a list of fields that are necessary for the calculation and it will make sure that those has been loaded. This could be done by adding a `select` option to calculate.

**Alternatives**
The work-around in the description versus the proposed solution by Zach.

**API proposition**

```elixir
  attributes do
    attribute :a, :integer, default: 0
    attribute :b, :integer, default: 0
    attribute :c, :integer, default: 0
    ...
  end
  
  calculations do
    # adding this would make it easier and cheaper to solve the above issue compared to `always_select?`.
    calculate :foo, :integer, select:  [:a, :b, :c] 
  end
```

**Comment by zachdaniel** [comment]
This issue has been resolved in the form of a `select/2` callback on calculations, and a select option on calculations in a resource.

**Comment by simpers** [comment]
Can confirm that this works.

1. I removed the work-around `always_select? true` declarations from all affected fields
2. Ran tests to confirm one test now fails
3. Added select @all_affected_attributes to my calculation
4. Ran tests again to confirm that they now pass again

Works like a charm :)
