### ISSUE TITLE
Invalid argument data types not throwing errors

### ISSUE THREAD

**Issue by kernel-io** [ash-project/ash#260]
**Describe the bug**
When defining an argument (within an action) that has an invalid data type, an error is not thrown.

**To Reproduce**
Define an argument on an action and give it a type of :list (which is invalid).

**Expected behavior**
Expected to throw an error informing the user of their mistake instead of just silently failing.

**Comment by zachdaniel** [comment]
You now get an error (albeit not the prettiest) that at least clues you in to where you've gone wrong.
