### ISSUE TITLE
Cross platform example

### ISSUE THREAD

**Issue by NikNik77** [ash-project/ash#261]
Hello all

Is it possible to provide an initial config on the basis of ash API that can be compiled to

windows 2. linux 3. macos 4. ios 5. android
It should draw a classical example of an triangle by shaders.

Triangle should be redrawn than window resized, moved or opened

The structure of the project consists of:

The rust library that actually do all work
rust project is dependent on lib number 1. and can be compiled to all desktop platforms
java project is dependent on lib number 1. and can be compiled to android
swift project is dependent on lib number 1. and can be compiled to ios

**Comment by zachdaniel** [comment]
Hey there! Did you perhaps mean to open this issue over here?: https://github.com/richardlord/Ash

**Comment by NikNik77** [comment]
> Hey there! Did you perhaps mean to open this issue over here?: https://github.com/richardlord/Ash

I mean vulkano ash. So, this is right place.
