### ISSUE TITLE
Fields not selected for calculations on create

### ISSUE THREAD

**Issue by michaelst** [ash-project/ash#262]
**Describe the bug**

I have this calculation setup 
```
calculations do
  calculate :balance, :string, Spendable.Budget.Calculations.Balance,
    allow_nil?: false,
    select: [:adjustment]
end
```

But on create (specifically from GraphQL) the adjustment field is not being selected so that calculation is failing. 

**To Reproduce**
https://github.com/fiftysevenmedia/spendable/blob/268790c9f6b12f582b5142b9786870fef3d50d4e/backend/lib/spendable/resources/budget.ex/#L0

**Expected behavior**
Fields in `:select` should be selected after create.

**Comment by michaelst** [comment]
@zachdaniel I believe you fixed this already right?

**Comment by zachdaniel** [comment]
Yes, this is resolved. Good catch!
