### ISSUE TITLE
Recursively discover column type for Ash.Type?

### ISSUE THREAD

**Issue by kernel-io** [ash-project/ash#270]
When creating a new Ash.Type i.e: to support Range column types in Postgresql, it is common practice to install a type for Ecto and then to stub the Ash.Type callbacks with calls to the Ecto type, this works for the most part, except for when referring to a custom type from within a calculation.

Ash seems to use the value returned by the type callback verbatim, however when you pass in a module  it will use that (as module names are just atoms). 

i.e: 
```elixir
  @impl Ash.Type
  def storage_type, do: PgRanges.TstzRange
 ``` 
results in the system trying to cast the column as a literal `PgRanges.TstzRange` instead of a `tstzrange` - but only in calculations, at least this is the only place I've observed it so far.

`tstzrange` is defined in the type function of the PgRanges.TstzRange module (implementing the Ecto.Type behaviour).
```elixir
  @impl true
  def type, do: :tstzrange
```

It would be nice to either check if the passed in value is a module, then check if it implements the Ecto.Type behaviour, and in turn use the return value from the type function there, _or_ to have a note in the Ash.Type documentation regarding this.

**Comment by zachdaniel** [comment]
Thanks for the report. I thought about this since we first talked about it, and I actually think the best path forward would be notate this in the docs just to avoid people getting tripped up, and then implement an `Ash.Type.WrapEcto` (or something) module that allows you to simply bootstrap a wrapped ecto type, e.g

```elixir
defmodule MyApp.TstzRange do
  use Ash.Type.WrapEcto, ecto_type: PgRanges.TstzRange
end
```

**Comment by kernel-io** [comment]
this sounds like an ideal solution, provided we are still able to override any of the auto-generated callbacks.

**Comment by zachdaniel** [comment]
This is open for anyone to take a stab at if they'd like, but I'm not convinced of its necessity given that we've gotten by without it for now, and each ecto -> ash type has a reasonable chance of needing at least some small amount of massaging (i.e to handle `nil`)
