### ISSUE TITLE
Should attributes default to `allow_nil?: false`

### ISSUE THREAD

**Issue by michaelst** [ash-project/ash#273]
With following this ticket (https://github.com/ash-project/ash/issues/272) we are considering matching the behavior across the framework to say things should not be nil by default.

**Comment by zachdaniel** [comment]
Alright, I've gone back and forth on this a hundred times and ultimately I'm not convinced its worth the overhead of changing. While it may be a marginally better default, I can't bring myself to put in hours of work and make every current Ash user put in a significant amount of work when they need to upgrade to this. I'm going to leave the default as `allow_nil?: true`
