### ISSUE TITLE
Ash fails to throw error if a filter doesn't include the pin (^) operator erroneously. 

### ISSUE THREAD

**Issue by kernel-io** [ash-project/ash#287]
When crafting filters, Ash fails to warn me that I have missed a `^` i.e: `expr(status == OrderStatus.pending())`, I'd expect Ash to warn me that I am missing a `^` on `OrderStatus.pending()`.

**Comment by zachdaniel** [comment]
We won't actually ever be able to warn on this, because the available functions are determined when we run the expression :(
