### ISSUE TITLE
Remove primary & default actions

### ISSUE THREAD

**Issue by zimt28** [ash-project/ash#288]
Default and primary actions are mainly used for `manage_relationship` convenience. A `when_managed` or `managed` option should be added instead:

```elixir
actions do
  managed [read: :read_name, create: :create_name, update: :update_name, destroy: :destroy_name]
end
```

Users who need to migrate should be pointed to an example "base resource" in the new docs:

```elixir
use MyApp.Resource, ...
```

```elixir
actions do
  managed [read: :read, ...]

  read :read
end
```

**Comment by zachdaniel** [comment]
This has been done!
