### ISSUE TITLE
Implementing `get_by_pkey` action could be more obvious

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash#293]
First thing I tried to do for read actions was implement fetch all and fetch by id, and ended up with this:

```elixir
  actions
    read :all do
      primary? true
    end

    read :get_by_id
  end

  code_interface do
    define_for Api

    define :all, action: :all
    define :get_by_id, action: :get_by_id, args: [:id], get?: true
  end
```

I assumed that the `define :get_by_id, action: :get_by_id, args: [:id], get?: true` line did the filtering. Sometimes I got `multiple results` errors, and even more confusing, if there was only one record I got a valid result. That was super confusing.

It wasn't until I stumbled across the filter example here https://hexdocs.pm/ash/expressions.html#filters that I realised what was missing. This allowed me to fix the problem:

```elixir
  actions do
    read :all do
      primary? true
    end

    read :get_by_id do
      get? true
      argument :id, :uuid, allow_nil?: false

      filter expr(id == ^arg(:id))
    end
  end

  code_interface do
    define_for Api

    define :all, action: :all
    define :get_by_id, action: :get_by_id, args: [:id], get?: true
  end
```

For a standard CRUD resource I'd be repeating this pattern everywhere, but it is explicit.

### Possible Solutions

- A clearer example code in the getting started guide would have helped a bunch here. eg Here's how you do a standard fetch all and fetch by id

- When `get_by_id`  with `get?: true` returned multiple results. This could have produced a more helpful error message eg
  > You've specified "read_one" which expects a single result, but the query has returned more than one result.
  > Please use a filter to ensure a single result is fetched

- An option like `define :get_by_id, ... get_by_pkey?: true` could provide the filter for you against your primary key, removing the need for `args: [:id], get?: true`

**Comment by joshprice** [comment]
For improving the multiple error results https://github.com/ash-project/ash/blob/main/lib/ash/error/invalid/multiple_results.ex

**Comment by joshprice** [comment]
Putting together a PR for this

**Comment by joshprice** [comment]
From the `Api.get` example in the getting started guide (https://github.com/ash-project/ash/blob/main/documentation/introduction/getting_started.md#list-and-read-a-resource) , I think I assumed that the code interface definition with `get?: true would do the same thing. eg

`define :get_by_id, action: :get_by_id, args: [:id], get?: true`

**Comment by joshprice** [comment]
@zachdaniel what's are the backward compatibility implications of using `get?: true` instead of making a new option `get_by_pkey?: true`?

**Comment by zachdaniel** [comment]
Well, anyone using `get?: true` would have all of their generated functions changed when they upgrade. We would have to add a `read_one` option, and they would have to know to change their code_interface blocks. Granted, we've been wanting to experiment with "update scripts" using sourceror for a while now, but I don't think this is the time for that, and people would still need to know to run it.
