### ISSUE TITLE
Clear or reload the calculations after updates

### ISSUE THREAD

**Issue by smt116** [ash-project/ash#296]
**Describe the bug**
When you perform an update on the record, it won't recalculate its loaded values. It means the result will include the calculations from before the update. You have to call the API's load after the operation to work around it.

**Runtime**
Ash version: 1.50.16

**Additional context**
[Discord message](https://discord.com/channels/711271361523351632/799097774523547669/955796204376174663)

**Comment by AliNisarAhmed** [comment]
@zachdaniel I'll take this one please assign.

**Comment by zachdaniel** [comment]
This issue is open again for anyone who wishes to take it :)
