### ISSUE TITLE
Error `message` field is `nil` even when parameters are passed in.

### ISSUE THREAD

**Issue by tlietz** [ash-project/ash#301]
**Describe the bug**
The `message` field on errors remains `nil` even when parameters are passed in.

**To Reproduce**

Create the following test and run it:
```elixir
defmodule Ash.Test.Errors do
  @moduledoc false
  use ExUnit.Case, async: true

  defmodule Post do
    @moduledoc false
    use Ash.Resource

    attributes do
      uuid_primary_key :id
      attribute :name, :string
    end
  end

  test "fails if error message field is `nil`" do
    err = Ash.Error.Invalid.NoSuchResource.exception(resource: Post)
    assert err.message != nil
  end
end
```

Result: `Assertion with != failed, both sides are exactly equal`

**Expected behavior**
The message field gets filled in with the `message` function of `no_such_resource.ex` instead of `nil`:
```elixir
def message(%{resource: resource}) do
  "No such resource #{inspect(resource)}"
end
```

** Runtime
 - OS = mac 
 - Ash version = 1.51.2

**Additional context**
I am unsure if the error is supposed to be working differently than I expect, but it is similar to how the error is used in `lib/ash/api/api.ex`
https://github.com/ash-project/ash/blob/main/lib/ash/api/api.ex#L992-L993

**Comment by zachdaniel** [comment]
Thanks for the report! This was just fixed in main.
