### ISSUE TITLE
Add a ‘Testing’ section in the guide.

### ISSUE THREAD

**Issue by tlietz** [ash-project/ash#304]
This would help to create a more comprehensive onboarding process and also provide boilerplate for common tests a developer using Ash would need to create.

**Comment by tlietz** [comment]
Since the guide already has sections for `test resources`, `test functionality`, and `test relationships`, I think it would be better to just add some testcases in the `test` directory to supplement the iex code that is already there.

**Comment by zachdaniel** [comment]
Yeah, good idea 👍🏻

**Comment by zachdaniel** [comment]
This has been added to the 2.0 release board.
