### ISSUE TITLE
Update typespecs for in Ash.Api w.r.t. return_notifications option

### ISSUE THREAD

**Issue by dvic** [ash-project/ash#306]
Haven't had time to submit a PR yet but I believe the typespecs in `Ash.Api` should be updated to take into account the possibility of returning notifications when `return_notifications?` is `true`. For example, for `create/2`, it should be `{:ok, Ash.Resource.record(), Ash.Notifier.Notification.t()}` | {:error, term()}.

**Comment by zachdaniel** [comment]
```elixir
  @spec create(Ash.Api.t(), Ash.Changeset.t(), Keyword.t()) ::
          {:ok, Ash.Resource.record(), list(Ash.Notifier.Notification.t())}
          | {:ok, Ash.Resource.record()}
          | {:error, term}
```

This is the current return type of `create/2` in `Ash.Api`, which looks correct to me. Happy to accept PRs to fix any broken/incorrect typespects! 🙇🏻

**Comment by dvic** [comment]
Sure! I'll have a look later this week 👍
