### ISSUE TITLE
Feature: Allow `first` aggregates on other aggregates

### ISSUE THREAD

**Issue by frankdugan3** [ash-project/ash#323]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to do a `first` aggregate on another aggregate.

**Describe the solution you'd like**
I would like to be able to use `first` on other aggregates.

**Describe alternatives you've considered**

- I can use a manual calculation, but that loses the ability to filter/sort
- I can do a raw subquery, but that's hacky/bad for maintenance

**Example**

Here is an example of using a `first` aggregate on another aggregate that is useful for a calculation:

```elixir
aggregates do
  sum :qty_completed, :lot_accountability_records, :qty_completed, default: 0
  ...
  first :previous_step_qty_completed, :previous_step, :qty_completed do
    default 0
  end
end

calculations do
  calculate :qty_completed_delta, :integer, expr(previous_step_qty_completed - qty_completed) do
    load [:previous_step_qty_completed]
  end
end

relationships do
  ...
  belongs_to :previous_step, __MODULE__
end
```

**Comment by zachdaniel** [comment]
This is now complete. Aggregates can reference other aggregates.
