### ISSUE TITLE
Feature: Add `cond` and/or `case` expression syntax

### ISSUE THREAD

**Issue by frankdugan3** [ash-project/ash#330]
**Is your feature request related to a problem? Please describe.**
Complex expression calculations with nested `if` logic can be very hard to read.

**Describe the solution you'd like**
`cond` and/or `case` syntax would greatly simplify many complex nested `if` operators.

**Describe alternatives you've considered**
Nesting `if` operators, though hard to read, can get the job done.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

For example

```elixir
Ash.Query.expr(
  cond do
    1 + 1 == 3 ->
      10
    1 + 1 == 4 ->
      11
    1 + 1 == 5 ->
      12  
    true ->
      13
  end
)
```
Which would translate into nested `if`s for execution:
```elixir
if 1 + 1 == 3 do
  10
else
  if 1 + 1 == 4 do
    11
  else
    if 1 + 1 == 5 do
      12
    else
      if true do
        13
      end 
    end
  end
end
```

Or

```elixir
Ash.Query.expr(
  case status do
    :pending ->
      10
    :failed ->
      11
    :running ->
      12  
    _ ->
      13
  end
)
```
Which would translate into nested `if`s for execution:
```elixir
if status == :pending do
  10
else
  if status == :failed do
    11
  else
    if status == :running do
      12
    else
      if true do
        13
      end 
    end
  end
end
```

**Comment by zachdaniel** [comment]
Seeing as we can't accurately reproduce pattern matching in the data layer (maybe some subset of pattern matching actually would work?) I think cond is our best bet here. This is actually a relatively easy change to make, so potentially a good first issue for someone who wants to dive into the expression stuff.

**Comment by frankdugan3** [comment]
Apparently, this was already implemented!
