### ISSUE TITLE
Example app without Phoenix

### ISSUE THREAD

**Issue by wess** [ash-project/ash#350]
**Is your feature request related to a problem? Please describe.**
Phoenix is a great framework, but not everyone uses it. Ash is an awesome looking framework
and i would love to use it but the only example I see is Phoenix, and I don't use Phoenix. 

**Describe the solution you'd like**
A web services, api, and/or spa that doesn't use phoenix and relies solely on Ash and Postgresql.

**Comment by zachdaniel** [comment]
Realistically, web development is the most common use case, but generally speaking the usage of Ash looks the same either way as it primarily sits underneath the web layer, connecting to it via extensions. We're working on generators, i.e `mix ash.new` and `mix ash.gen.resource` that will go a long way towards providing a good starting point with/without phoenix, i.e `mix ash.new --phoenix`. I'll consider if I have time to make another example project without phoenix in the coming days, but the current focus is on the documentation overhaul and new documentation site.
