### ISSUE TITLE
Registry entries not validated

### ISSUE THREAD

**Issue by mbuhot** [ash-project/ash#359]
**Describe the bug**

While following the getting started guide, an invalid `entries` block (my mistake) was silently ignored.
The symptom was that the ash_postgres mix tasks failed with an unexpected error message.

**To Reproduce**

The Registry module

```elixir
defmodule Beerlog.Registry do
  use Ash.Registry,
    extensions: [Ash.Registry.ResourceValidations]

  entries do
    Beerlog.Beer # NOTE: missing the `entry` here 
  end
end
```

```bash
mix ash_postgres.create

** (RuntimeError) must supply the --apis argument, or set `config :my_app, ash_apis: [...]` in config
    (ash_postgres 0.41.7) lib/mix/tasks/ash_postgres.create.ex:40: Mix.Tasks.AshPostgres.Create.run/1
    (mix 1.13.1) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.1) lib/mix/cli.ex:84: Mix.CLI.run_task/2 
```

**Expected behavior**

Ideally a compile time error when compiling the Beerlog.Registry module, indicating that the `entries` block is invalid.

**Runtime**

 - Elixir version: 1.13.1
 - Erlang version: Erlang/OTP 24
 - OS: macOS 12.4
 - Ash version: 1.51.2
 - any related extension versions, `ash_postgres: 0.41.7`

**Comment by zachdaniel** [comment]
Hey there! Thanks for the report. Unfortunately, given that the DSLs accept valid elixir code, there really isn't anything we can do about this. At least, nothing that I can think of.

For example, you could do something like this:
```elixir
entries do
  foo = Foo
  bar = Bar

  entry Module.concat(Foo, Bar)
end
```

So there isn't really a way to tell the difference between a dangling module like that and any other elixir expression.

With that said, what we could potentially do is simply fail to compile the registry if it has zero entries? It doesn't make much sense to have a registry with zero entries.

**Comment by mbuhot** [comment]
Thanks @zachdaniel, yes an error or warning for an empty registry makes sense.

It might also be helpful to output different error messages from `mix ash_postgres.create` based on whether there were no APIs configured or no resources found having `AshPostgres.DataLayer`.

**Comment by zachdaniel** [comment]
ah, yeah I completely agree :) That would also have been the simple answer. At the moment it can't tell the difference between no apis or no resources.
