### ISSUE TITLE
strict_check/3 should return false when nil actor is referenced in policy

### ISSUE THREAD

**Issue by frankdugan3** [ash-project/ash#372]
**Describe the bug**

Given a policy such as:
```elixir
policy action_type(:read) do
  authorize_if relates_to_actor_via([:user])
  authorize_if actor_attribute_equals(:id, :id)

  forbid_unless actor_is_active()
  authorize_if actor_roles_has_any(UserRole._employee_roles())
end
```
When I run it through `PolicyInfo.can/3` with a `nil` actor, the underlying call to `Ash.Policy.Info.strict_check/3` is returning `:maybe`. I understand this is due to the default of filtering policies (which what I want for any non-nil actor), but it kinds of seems like the above policy could be statically determined to always be unauthorized given a `nil` actor.

**Additional context**

Something like the below logic would need to be added [to this module](https://github.com/ash-project/ash/blob/main/lib/ash/policy/filter_check.ex#L46):

```elixir
if is_nil(actor) && Ash.Filter.template_references_actor?(template) do
```

I think this functionality may have previously existed, but was removed due to a lack of testing around it.

**Comment by zachdaniel** [comment]
Actually, looking at this, I'm not entirely sure that is the right behavior (we talked about this before and I had recommended this course of action). I think what we should do is add a custom `strict_check` call to `actor_attribute_equals` that returns `:forbidden` when actor is nil (and probably the same as any other built in check that requires an actor.

**Comment by frankdugan3** [comment]
That makes sense... though should it be `:forbidden` or just `false`? Because it's possible a later check could pass, right?

Also, in my custom simple checks, I handle a `nil` actor by returning `false`. I think that's adequate because the simple check behavior has a `strict_check` that basically runs `match/3`; am I right on that?

**Comment by zachdaniel** [comment]
Ah, yeah you're right sorry. I meant `false` :)

`strict_check` running `match/3` is only a thing for `Ash.Policy.SimpleCheck`, but you're right about the return value of `strict_check` being a boolean, not `:forbidden`
