### ISSUE TITLE
Manual action wrapped in transaction

### ISSUE THREAD

**Issue by smt116** [ash-project/ash#373]
**Describe the bug**
I'm using a manual create action with the `transaction? false`, but I can still see `begin ... commit` in the logs.

**Expected behavior**
I would expect that such an action runs outside of a database transaction.

**Runtime**
 - Elixir version 1.13.4
 - Erlang version 25.0.4
 - OS macOS
 - ash_admin 0.6.0-rc.0
 - ash_graphql 0.20.0-rc.0
 - ash_postgres 1.0.0-rc.0
 - ash 2.0.0-rc.0

**Comment by zachdaniel** [comment]
🤔 yeah that sounds like an issue. Let me take a look.

**Comment by smt116** [comment]
> Actually, what do you do in your manual action? do you call a resource action inside of it?

I'm performing a few things and calling the `create` action (actually a create-like via another code interfaces' action) at the end. I would expect it wraps only that "create" into a transaction. Does it wrap the whole manual action because it _contains somewhere_ something that uses actions?

**Comment by zachdaniel** [comment]
No, but if you are calling a create on some other resource, *that* will start a transaction, which could explain the begin/commit that you are seeing.

**Comment by smt116** [comment]
Makes sense, 👍.
