### ISSUE TITLE
Generated typings for `Ash.Resource` are incorrect and cannot be overriden.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash#383]
**Describe the bug**
Resources generated with `Ash.Resource` are generated with a type `t` which is simply the module name of the resource.  This is incorrect as the resource is actually a struct.

**To Reproduce**
```elixir
defmodule Boned do
  use Ash.Resource, data_layer: Ash.DataLayer.Ets

  attributes do
    uuid_primary_key :id
    attribute :surprise, :boolean, default: true
  end
end
```

    iex> t Boned
    @type t() :: Boned

Additionally, attempting to manually define `@type t` on the resource causes a compile error:

```
== Compilation error in file lib/boned.ex ==
** (CompileError) lib/boned.ex:1: type t/0 is already defined in lib/boned.ex:4
    (elixir 1.14.0) lib/kernel/typespec.ex:936: Kernel.Typespec.compile_error/2
    (stdlib 4.1) lists.erl:1355: :lists.foldl_1/3
    (elixir 1.14.0) lib/kernel/typespec.ex:226: Kernel.Typespec.translate_typespecs_for_module/2
```

**Expected behavior**
A `t` type for the resource should be correctly defined at a minimum with `@type t :: %__MODULE__{}` however, generating the attribute typespecs from the resource attributes would be pretty great too.

**Runtime**
 - Elixir version 1.14.0
 - Erlang version 25.1
 - OS Ubuntu jammy/amd64
 - Ash version `8a87e7c`
 - any related extension versions:
     ash_phoenix 0.7.7
     ash_postgres 0.43.0

**Comment by zachdaniel** [comment]
This has been fixed in the later releases of Ash, so updating has resolved the issue. Thanks for the report!
