### ISSUE TITLE
Docs: get started

### ISSUE THREAD

**Issue by trymkb** [ash-project/ash#389]
Instructions on creating files and structure is wrong:

# Run in your terminal
touch lib/helpdesk/tickets.ex
mkdir -p lib/helpdesk/support/resources && touch $_/ticket.ex
touch lib/helpdesk/support/registry.ex

Should be
# Run in your terminal
mkdir -p lib/helpdesk/support/resources && touch $_/ticket.ex
touch lib/helpdesk/support/registry.ex
touch lib/helpdesk/support.ex

**Comment by zachdaniel** [comment]
Thanks for the report! Would you like to PR the fix to the guide here? https://github.com/ash-project/ash/blob/main/documentation/tutorials/get-started.md

Happy to do it if not :)

**Comment by trymkb** [comment]
I can create a PR later today :-)

**Comment by zachdaniel** [comment]
Fixed in #390 390
