### ISSUE TITLE
Show relationships as fields in class diagrams

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#393]
At the moment, we draw a single line between anything and its related things, because relationships are two noisy, especially in both directions. However, not having this context is also a bummer in the diagrams. I'm thinking there are two things we can do here:

1. we could add an option to hide specific relationships in diagrams. i.e `belongs_to :owner, User, diagram?: false`
2. we could add relationships as fields in the class diagram, i.e

```elixir
User owner
Comment[] comments
```

**Comment by zachdaniel** [comment]
@joshprice thoughts?

**Comment by joshprice** [comment]
Not sure I love the diagram options on core relationships. Relationships are already fields in class diagrams (but awkward to include in ER diagrams).

**Comment by zachdaniel** [comment]
Ah, I just didn't realize. I was expecting a certain relationship to show up, but it wasn't because it was private (which is desired behavior :))

**Comment by joshprice** [comment]
We may want to also show private fields (attrs, aggs, calcs, etc) in class diagrams for completeness?

**Comment by zachdaniel** [comment]
Yeah, we could make it an optional flag, i.e `include_private?: true`.

**Comment by zachdaniel** [comment]
I'll make an issue for that
