### ISSUE TITLE
Allow defining output format for ash.generate_flow_charts mix task

### ISSUE THREAD

**Issue by juhalehtonen** [ash-project/ash#422]
Currently the `ash.generate_flow_charts` mix task depends on the Mermaid CLI being installed on the users system, and only the PDF output format is supported.

By allowing users to pass in a `--format` option of `.svg`, `.pdf` or `.md` to the mix task, we could both 1) remove the hard dependency on Mermaid CLI when just the text-based output is needed, and 2) enable SVG file format as an alternative output option.

**Comment by joshprice** [comment]
Happy to pick this up, it needs to be mirrored across the other mermaid diagram task.

Had planned to switch between `.pdf` and `.svg` and `.png`, but great idea to be able to also generate both `.md` and plaintext options (no backticks).

I'm probably going to make the plaintext option the default unless anyone has any objections, as this avoids the Mermaid CLI dependency, and is useful for copy and pasting into Mermaid editor or other docs.

**Comment by juhalehtonen** [comment]
> I'm probably going to make the plaintext option the default unless anyone has any objections, as this avoids the Mermaid CLI dependency, and is useful for copy and pasting into Mermaid editor or other docs.

Sounds great to me!

**Comment by zachdaniel** [comment]
The above commit is not actually related to this, I just referred to 422 when I meant to refer to #442
