### ISSUE TITLE
Loading children in global change can affect upsert behaviour

### ISSUE THREAD

**Issue by oco-adam** [ash-project/ash#436]
**Describe the bug**
Lazy loading the children of a parent resource in an after_action of a global change block seems to affect behaviour when upserting children through the parent.

**To Reproduce**
This has been reproduced as a test in pull request here: https://github.com/ash-project/ash/pull/434/files

**Expected behavior**
Lazy loading children in an after_action of a global change block should have no effect on upsert behaviour.

**Runtime**
 - Elixir version: Elixir 1.14.0
 - Erlang version: Erlang/OTP 25
 - OS: MacOS 12.5.1
 - Ash version: 2.3.0

**Comment by zachdaniel** [comment]
Fixed in: d70a05c8052b7a99c657d8081094ed7a198f8f6f

**Comment by zachdaniel** [comment]
Thanks for the report!
