### ISSUE TITLE
Ash.DataLayer.Ets configurable

### ISSUE THREAD

**Issue by JuanjoA** [ash-project/ash#439]
Hi, first of all, thanks for your work.

I trying Ash framework to build an aggregator, consume messages from X and create ets entries.

Maybe because the ets layer is not recommended for production, it doesn't allow many options.
By default, the ets table has enabled read_concurrency, but not write_concurrency (example).
Another default is the table type, :ordered_set.

It would be nice to be able to configure the options to configure ets as needed.

I have little experiencie with elixir but maybe I can create a PR about this.

**Comment by zachdaniel** [comment]
I'm going to close this specific issue for now, but if you want to open individual issues for the things you'd like to add, i.e "Allow changing table type instead of requiring `:ordered_set`", please do!

**Comment by JuanjoA** [comment]
Thanks @zachdaniel ,I undestand, I will try to add more options, thanks for the suggestion.
