### ISSUE TITLE
Documentation Site Unwanted Refresh

### ISSUE THREAD

**Issue by andyl** [ash-project/ash#441]
**Describe the bug**

I'm using your documentation site, the page auto-refreshes periodically, forcing me to scroll back to my reading point.  

Looks like some sort of live-view issue.

**To Reproduce**

Open the get started page (https://ash-hq.org/docs/guides/ash/2.4.1/tutorials/get-started.md), scroll half way down, wait 5 or 10 minutes.

**Expected behavior**

No refresh

**Runtime**

I'm using the brave browser on Xubuntu 22.04

**Additional context**

Just learned about Ash this morning - excited by what I see.

**Comment by zachdaniel** [comment]
Thanks for the report, LMK if it continues to happen.
