### ISSUE TITLE
Unclear error when using an incorrect type for an attribute

### ISSUE THREAD

**Issue by brettkolodny** [ash-project/ash#442]
When declaring an attribute with an incorrect type you get an error message relating to the underlying ecto types. It would be better to have a more targeted error message describing the problem.

Currently:

```ex
attribute :score, :int
```

```
== Compilation error in file lib/.../player.ex ==
** (UndefinedFunctionError) function :int.ecto_type/0 is undefined or private
```

**Comment by zachdaniel** [comment]
Fixed in 27ca1d2
