### ISSUE TITLE
unclear error message when using invalid filter syntax

### ISSUE THREAD

**Issue by MrGrinst** [ash-project/ash#443]
**Describe the bug**
This is similar to https://github.com/ash-project/ash/issues/442. I ran into it while attempting to use `filter` with the keyword list syntax, passing it `id: {:in, [...]}` instead of the correct `id: [in: [...]]` args. Instead of complaining about the tuple syntax, it gave me the error:

```
No such attribute or relationship :id for Resource
```

**To Reproduce**
```
Resource |> Ash.Query.filter(id: {:in, [1]}) |> API.read!()
```

**Expected behavior**
It would be awesome if it returned something related to the fact the filter syntax couldn't be parsed.

**Comment by zachdaniel** [comment]
The tough thing there is that that actually is a valid filter syntax *if* there was an id field. I'll think on how we can improve the DX here. Have you looked into using expression filters instead of the keyword list syntax?

**Comment by MrGrinst** [comment]
I might be misunderstanding, but in my case there is an `id` field. I did end up going the expression route. Was trying to be fancy and try to pipe things around and the keyword list, but the expression `id in [...]` is working great.

**Comment by MrGrinst** [comment]
Done, just pushed up #444

**Comment by zachdaniel** [comment]
Thanks! Will close this in favor of that.
