### ISSUE TITLE
Validate Ash HQ doc links for modules in the same project

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash#447]
**Problem**

When linking to modules in Ash HQ, it would be useful to check if they exist in the doc index https://github.com/ash-project/ash/blob/main/lib/doc_index.ex#L93

**Possible Solution**

https://github.com/ash-project/ash/blob/main/lib/mix/tasks/replace_doc_links.ex#L52

In there, we can check if the `library == to_string(current_mix_project)`

**Extra context**

https://github.com/ash-project/ash/issues/448 would be avoided if links were validated

**Comment by zachdaniel** [comment]
Fixed in 5090deb202522b4a6bb9b30cc06638dba6166d89
