### ISSUE TITLE
Ash.Tracer is not in the doc index

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash#448]
**Describe the bug**

In the Ash HQ docs:

https://github.com/ash-project/ash/blob/39ea911d33629a9c874c0522a0a797f4094544a9/documentation/topics/monitoring.md#instrumentation

The link to `Ash.Tracer` expressed as `{{link:ash:module:Ash.Tracer}}` doesn't work correctly. It produces the correct link https://ash-hq.org/docs/module/ash/latest/ash-tracer but this falls back to the Getting Started page as the `Ash.Tracer` module is not in the doc index.

https://github.com/ash-project/ash/blob/main/lib/doc_index.ex#L93

**To Reproduce**

https://ash-hq.org/docs/module/ash/latest/ash-tracer leads to Getting Started page

**Expected behavior**

Should go to `Ash.Tracer` module page

**Comment by zachdaniel** [comment]
Resolved this specific issue in [5d43444](https://github.com/ash-project/ash/commit/5d434448efc0d140e9d2cefe57dc3a8e1508e2ab)
