### ISSUE TITLE
Allow for expressing the behavior of related items when a record is deleted.

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#45]
**Is your feature request related to a problem? Please describe.**

There are two versions of this, one implemented at the data layer, e.g `ON DELETE CASCADE` options in postgres, and one handled by application logic. Generally, implementing it in the database is the best way to ensure integrity. We don't currently support deleting with a query, but when we do it would be difficult (and maybe just completely unreasonable) to work these rules into that process.

However, we want to leverage that information to make smarter decisions, especially when we start adding caching layers. Additionally, we want to do it manually for data layers that don't support it.

The difficulty here is that if we have:

```elixir
relationships do
  has_many :comments, MyApp.Comments, on_delete: :cascade
end
```

But they've configured it in their database as well, we need some way to reconcile those two configurations so we know that there isn't actually anything to do when something is deleted.

**Comment by zimt28** [comment]
> we want to do it manually for data layers that don't support it

This is also important for destroy/delete actions with `soft? true`.

**Comment by zachdaniel** [comment]
For now, this can be implemented in the data layer, or can be done with a manual change. If someone ends up needing this and isn't using ash_postgres (or some other data layer that supports this feature) then they are welcome to PR a builtin change i.e `change delete_all_related(...)`
