### ISSUE TITLE
Extension Proposal: [Change tracking via Carbonite]

### ISSUE THREAD

**Issue by terrisgit** [ash-project/ash#456]
** What is the purpose of the extension? **

Track changes to resources that are stored in Postgres tables using the bitcrowd/carbonite project. (Only Postgres 13 and higher are supported.) See https://hexdocs.pm/carbonite/Carbonite.html for the list of benefits and how it works.

** How would it extend the DSL? **

I am open to suggestions. In my case every resource would be tracked but in the general case only certain resources should be tracked.
"track changes with carbonite" 

** What it would do? **

1. Would these be manual tasks? 

A) Add Carbonite dependencies. See https://hexdocs.pm/carbonite/Carbonite.html#module-hex-dependency

B) Create a migration to add the carbonite schema if it doesn't already exist. Perhaps the dsl should accept an optional schema name. See https://hexdocs.pm/carbonite/Carbonite.html#module-creating-the-initial-migration

2. Create a migration to add triggers to the table for cud operations - see https://hexdocs.pm/carbonite/Carbonite.html#module-trigger-configuration

3. Alter all cud operations to create a Carbonite transaction row. See https://hexdocs.pm/carbonite/Carbonite.html#module-inserting-a-transaction

** Interaction with other features **

1. Tenants - does each tenant get its own carbonite schema?

2. Context - I want to associate current_user.id with the Carbonite transaction. However, some operations will be done anonymously

3. Archive - unclear whether anything special is needed

4. Seed data (if applicable). Ash would either insert a transaction for Carbonite or disable the validation. See https://hexdocs.pm/carbonite/Carbonite.html#module-inserting-a-transaction

5. Migrations. Similarly, if migrations alter data, Ash would either insert a transaction for Carbonite or disable the validation. See https://hexdocs.pm/carbonite/Carbonite.html#module-transactions-in-data-migrations

**Comment by zimt28** [comment]
I haven't looked into Carbonite but have you seen the [`ash_paper_trail` extension](https://github.com/ash-project/ash_paper_trail)?

**Comment by zachdaniel** [comment]
Carbonite does look quite interesting :) The benefit of carbonite is that it actually tracks all of the changes effectively "automagically" under the hood, allowing for things like arbitrary changes in the db to be tracked even if they don't go through Ash resources. The benefit of `ash_paper_trail` is that you can track anything that changes about a resource even if that doesn't map to a pg datalayer, and it will be a bit more semantic, i.e we track each "action invocation". They likely have two different places, and I could even see a world where you might use both. From a practical standpoint:


1. tenants - we would likely want people who are using schema based multitenancy to have separate carbonite schemas? I'm not too informed on carbonite to say what is preferred there.
2. Context - This should be quite easy. Since the extension would just add a `change` to each action, or we may add a new option called something like `around_transaction` that lives in the api, in either case we can ensure that the callback there has access to the "actor" (user), the "tenant" and any other context.
3. Archive - This should likley just work. All we do for archive is add an attribute and ensure that we filter on it at the application layer
4. Seed data - Hard to say really. We have some utilities for seeding directly to the data layer, so perhaps we can add some kind of config to wrap seeding in a carbonite transaction. Or just some kind of utility like `AshCarbonite.transaction("name", fn -> ... end)`.

I'd be curious to see how this goes!

**Comment by terrisgit** [comment]
The benefit of paper trail is if json/graphql/etc. APIs provide read only access to historical versions. The benefit of carbonite is it works with ecto. So if you have a hybrid app that uses ash and ecto you can standardize on carbonite. Carbonite is also more mature and supports partitioning which is something that paper trail will eventually need.

**Comment by terrisgit** [comment]
Here are the current steps needed to add Carbonite to an Ash project and track one resource. Assume the resource has already been setup to use Postgres and MyApp.Repo exists. All things considered, it isn't too bad.

## mix.exs

Add a dependency:

```elixir
      {:carbonite, "~> 0.6.0"},
```

## Add two migrations

```sh
mix deps.get
mix carbonite.gen.initial_migration -r MyApp.Repo
mix ecto.gen.migration add_<<resource_name>>s_carbonite
mix ecto.migrate
```

## resources/<<resource_name>>.ex

Add/modify changes section:

```elixir
  changes do
    change {MyApp.CarboniteTransaction, meta: %{type: "project_modified"}}, on: [:create, :update, :destroy]
  end
end
```

## lib/carbonite_transaction.ex

```elixir
defmodule MyApp.CarboniteTransaction do
  use Ash.Resource.Change

  def change(changeset, opts, %{actor: actor}) do
    transaction_opts = opts[:meta] || %{}
    type = transaction_opts[:type]
    actor_id = if actor, do: actor.id, else: nil

    changeset
    |> Ash.Changeset.before_action(fn changeset ->
      %{meta: %{type: type, actor_id: actor_id}}
      |> Carbonite.Transaction.changeset()
      |> KantanModel.Repo.insert!(prefix: "carbonite_default")
      changeset
    end)
  end
end
```

**Comment by zachdaniel** [comment]
you could also derive the type from the action name, i.e `type: "#{Ash.Resource.Info.short_name(resource)}_#{changeset.action.name}"` to genericize it a bit more.

So the benefit of an extension would probably mostly lie in the fact that it could add custom statements to the migration generator to create the carbonite tables. You'd still have to run the initial migration manually, but then all resources to which you add the extension could be automatically migrated when generating their migrations.

What goes into the `add_<<resource>>s_carbonite` migration?

**Comment by zachdaniel** [comment]
You're right though, its a good sign that it was so easy to integrate carbonite 👍🏻

**Comment by zachdaniel** [comment]
Maybe the folks at carbonate would want to provide this extension I wonder. Its not going to be much code to maintain realistically.

**Comment by terrisgit** [comment]
@zachdaniel Of course it's a chicken and egg problem. Few people use Carbonite and fewer use Ash. I am the only likely person who has a need for this and I'm definitely the one person motivated enough to make it happen. I would build it if I knew how to make extensions but I am a beginner in both Elixir and Ash.

**Comment by zachdaniel** [comment]
I *think* ash may have more users than carbonite FWIW. Regardless, I'll add some transaction hooks tonight or tomorrow to make this all work nicely, and then we or I can write up a short bit on integrating them, and just have that as a guide in ash_postgres. I'll put a not to that in the paper trail getting started guide too. :)

**Comment by terrisgit** [comment]
> What goes into the `add_<<resource>>s_carbonite` migration?

Create trigger statements

@zachdaniel

**Comment by terrisgit** [comment]
> you could also derive the type from the action name, i.e `type: "#{Ash.Resource.Info.short_name(resource)}_#{changeset.action.name}"` to genericize it a bit more.

Sorry, I'm new to this. I put that into the resource.ex file but I got:

 `undefined function resource/0 (there is no such import)`

And `changeset` is also not defined. 

I imagine this belongs in carbonite_transaction.ex ?

**Comment by zachdaniel** [comment]
Yeah, it would go in the Change module

**Comment by terrisgit** [comment]
See also https://github.com/bitcrowd/carbonite/issues/66 . Regardless of the responses to this issue (if any) it appears that it's best to create the Carbonite transaction at a higher level. This would require every table to be audit logged but additional configuration could be added. This points to a note compelling need for an extension. The "configuration" should be defined in resource.ex instead of elsewhere.

**Comment by zachdaniel** [comment]
FWIW you can do extensions quite simply, it’s meant to be possible to have “private” extensions, and many ash users ultimately end up with a few.

**Comment by zachdaniel** [comment]
But I might actually just make an extension because the it will be a very simple extension and will have an outsized usefulness for Ash users wishing to have great audit logs for postgres.

**Comment by terrisgit** [comment]
The above steps have been updated to use Carbonite.insert_transaction to catch the case where it is called multiple times in one transaction.

**Comment by terrisgit** [comment]
@zachdaniel An extension would be awesome but is low priority. I think this process accidentally identified a missing hook for transactions, so it was a valuable exercise and is higher priority. That said, with the hook, I'm sure you can refactor this solution to something much more elegant. It's still kind of messy with the manual migrations but all things considered this side project went really, really well.

**Comment by terrisgit** [comment]
<<Reposting due to accidental deletion>>

Here are the current steps needed to add Carbonite to an Ash project and track one resource. Assume the resource has already been setup to use Ecto+Postgres via MyApp.Repo. All things considered, it isn't too bad but an extension could remove some of the friction. I would not have even considered creating an extension; however, @zachdaniel asked me to create an issue for it. At any rate, this issue can serve as a tutorial for adding Carbonite to an Ash project. It's surprisingly simple thanks to Ash's extensible design. This is one of the main reasons why I'm using Ash instead building a vanilla Phoenix+Ecto app. Centralizing audit trail is just what the code doctor ordered!

## Modify mix.exs

Add a dependency:

```elixir
{:carbonite, "~> 0.6.0"},
```

## Add lib/carbonite_transaction.ex

```elixir
defmodule KantanModel.Changes.CarboniteTransaction do
  use Ash.Resource.Change

  def change(changeset, opts, %{actor: actor}) do
    type = "#{Ash.Resource.Info.short_name(changeset.resource)}_#{changeset.action.name}"
    meta = Map.put(opts[:meta], :type, type)
    actor_meta = actor && Map.put(meta, :actor, actor.id) || meta

    Ash.Changeset.before_action(changeset, fn changeset ->
      {:ok, _} = Carbonite.insert_transaction(KantanModel.Repo,
        %{meta: actor_meta},
        prefix: "carbonite_defaultx",
        on_conflict: {:replace, [:id]},
        conflict_target: [:id],
        returning: true)

      changeset
    end)
  end
end
```

## Add the initial migration

```sh
mix deps.get
mix carbonite.gen.initial_migration -r MyApp.Repo
Add one migration per resource

mix ecto.gen.migration add_carbonite_<<resource_name>>
mix ecto.migrate
```

## Modify resources/<<resource_name>>.ex

Add/modify the changes section:

```elixir
  changes do
    change {MyApp.CarboniteTransaction, meta: %{type: "<<resource_name>>_modified"}}, on: [:create, :update, :destroy]
  end
```

**Comment by zachdaniel** [comment]
Yeah, an extension would be great for automatically creating the migrations, but overall probably not worth putting in the time to make an extension otherwise. I'll update this issue when the new transaction hooks are in.

**Comment by zachdaniel** [comment]
Alright, as of whenever the next ash_postgres release goes out, you can use the `on_transaction_begin` callback in the ecto repo, that will get a `transaction_reason`:
```elixir
  @type transaction_reason ::
          %{type: :create, metadata: %{resource: Ash.Resource.t(), action: atom}}
          | %{
              type: :update,
              metadata: %{
                resource: Ash.Resource.t(),
                action: atom,
                record: Ash.Resource.record(),
                actor: term()
              }
            }
          | %{
              type: :destroy,
              metadata: %{
                resource: Ash.Resource.t(),
                action: atom,
                record: Ash.Resource.record(),
                actor: term()
              }
            }
          | %{
              type: :read,
              metadata: %{resource: Ash.Resource.t(), query: Ash.Query.t(), actor: term()}
            }
          | %{
              type: :flow_transaction,
              metadata: %{step_name: atom | list(term), flow: module(), actor: term()}
            }
          | %{type: :custom, metadata: map()}
          ```

**Comment by terrisgit** [comment]
am currently rewriting the code for ash_postgres 1.3.1. I will update the above post today.

**Comment by terrisgit** [comment]
Here are the steps needed to add Carbonite to an Ash project and track one resource. This requires ash_postgres 1.1.3 or higher.

## mix.exs

Add Carbonite as a dependency:

```elixir
{:carbonite, "~> 0.6.0"},
```

## lib/repo.ex: Add on_transaction_begin

```elixir
  def on_transaction_begin(%{type: type, metadata: metadata})
      when type in [:create, :update, :destroy] do
    meta = %{
      type: type,
      action: metadata.action,
      resource: Ash.Resource.Info.short_name(metadata.resource)
    }

    actor_meta = (metadata.actor && Map.put(meta, :actor, metadata.actor.id)) || meta

    {:ok, _} = Carbonite.insert_transaction(KantanModel.Repo, %{meta: actor_meta})
  end
```

## Create and modify the initial Ecto migration

```sh
mix deps.get
mix carbonite.gen.initial_migration -r MyApp.Repo
```

See https://github.com/bitcrowd/carbonite#getting-started

## Create Ecto migrations to add database triggers to Carbonite-tracked tables

Add one or more migrations. A new migration should be added when new Ash resources are added.

```sh
mix ecto.gen.migration add_carbonite_triggers
```

Also see https://github.com/bitcrowd/carbonite#getting-started

Example:

```elixir
defmodule MyApp.Repo.Migrations.AddCarboniteTriggers do
  use Ecto.Migration

  def up do
    Carbonite.Migrations.create_trigger(:rabbits)

    # Optionally you may configure the trigger inside the migration.
    Carbonite.Migrations.put_trigger_config(:rabbits, :excluded_columns, ["password"])
  end

  def down do
    Carbonite.Migrations.drop_trigger(:rabbits)
  end
end
```

```sh
mix ecto.migrate
```

**Comment by terrisgit** [comment]
@zachdaniel Does the above look correct? It works but would like to check with you.

**Comment by zachdaniel** [comment]
Yep! That looks right 👍🏻

**Comment by zachdaniel** [comment]
I appreciate you validating it, and documenting this here for other interested users. You stuck with it and I know someone else will benefit from that in the future. Great work!

**Comment by terrisgit** [comment]
@zachdaniel I got this far only because you replied to me and added new events.
