### ISSUE TITLE
DevEx: picosat_elixir on Windows

### ISSUE THREAD

**Issue by ojames-drohealth** [ash-project/ash#457]
Getting Ash to work on Windows can be frustrating. Very frustrating.

Most of the challenge comes from the NIF error raised when compiling `picosat_elixir`.

In fact, I strictly recommend WSL to Windows users trying to work with Ash.

However, for the widespread role I believe Ash can grow to have in the Elixir ecosystem, I don't think this solution is good enough.

Specifically, this WSL approach doesn't work for Livebook users.

Since people who are looking to try out Ash for the first time might do so in Livebook, how can we make the experience seamless?

**Comment by zachdaniel** [comment]
Hey there! We can make the picosat_elixir dependency optional, and support a configurable solve. We could then write an elixir native solver which will likely be much slower, but could be used on windows (naturally). 

WIth that said, we could also either 1. write a guide containing the necessary steps for getting it to work on windows or 2. fix whatever causes the frustration? What are the specific frustrations involved in making it work on windows? Have any issues been logged against `picosat_elixir` with these frustrations?

**Comment by ojames-drohealth** [comment]
How about a Rust solver instead?
I'm sure that'd be faster than the Elixir native implementation and then Rustler Precompiled can help avoid the compilation issues with the C NIF.


On the other note, the `picosat_elixir` Readme alludes to needing extra steps for Windows.
I can try to reproduce and document the pre-WSL errors later.

**Comment by zachdaniel** [comment]
I would definitely like to write a rust solver, or at least use zigler to compile the NIF which should solve for lots of the issues we see, I imagine.

**Comment by zachdaniel** [comment]
The NIF can also cause issues for M1 users due to linker environment variables. See #458

**Comment by smt116** [comment]
It might be resolved via https://github.com/bitwalker/picosat_elixir/issues/8.

**Comment by zachdaniel** [comment]
Great point :) I'm glad that got resolved! There may be other related picosat devex things but for now I'll close this issue.

**Comment by tweetandcode** [comment]
did this actually get resolved?

**Comment by zachdaniel** [comment]
The main issue that people seemed to be dealing with was resolved as an update to picosat_elixir (LDFLAGS related errors).
