### ISSUE TITLE
error compiling picosat_elixir on Apple M1

### ISSUE THREAD

**Issue by bananoid** [ash-project/ash#458]
I'm try to do the Get Started tutorial but I get the following error:

iex -S mix
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

==> picosat_elixir
cc -L/opt/homebrew/Cellar/openssl@3/3.0.5/lib -shared  /samplecode/helpdesk/deps/picosat_elixir/priv/picosat_nif.o /samplecode/helpdesk/deps/picosat_elixir/priv/picosat.o -o /samplecode/helpdesk/_build/dev/lib/picosat_elixir/priv/picosat_nif.so
Undefined symbols for architecture arm64:
  "_enif_get_int", referenced from:
      _solve_nif in picosat_nif.o
  "_enif_get_list_cell", referenced from:
      _solve_nif in picosat_nif.o
  "_enif_get_list_length", referenced from:
      _solve_nif in picosat_nif.o
  "_enif_make_atom", referenced from:
      _solve_nif in picosat_nif.o
  "_enif_make_badarg", referenced from:
      _solve_nif in picosat_nif.o
  "_enif_make_int", referenced from:
      _solve_nif in picosat_nif.o
  "_enif_make_list_from_array", referenced from:
      _solve_nif in picosat_nif.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/samplecode/helpdesk/_build/dev/lib/picosat_elixir/priv/picosat_nif.so] Error 1
could not compile dependency :picosat_elixir, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile picosat_elixir", update it with "mix deps.update picosat_elixir" or clean it with "mix deps.clean picosat_elixir"
==> helpdesk
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.

**Runtime**
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
Elixir 1.14.1 (compiled with Erlang/OTP 25)
macOS Monterey 12.5.1
{:ash, "~> 2.4"}

**Comment by ahey** [comment]
I worker around this issue with `unset CPPFLAGS && unset LDFLAGS` - more information at https://github.com/bitwalker/picosat_elixir/issues/5

**Comment by zachdaniel** [comment]
We can track the general devex issues around picosat in #457. Thanks for the report and workaround!
