### ISSUE TITLE
When updating relationships, if records are passed in, we shouldn't read them back

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#46]
In `Ash.Actions.Relationships`, when structs are passed in we just take the primary key off of them, and make the same query as if a primary key was passed. We should avoid querying in the case we are given records.

**Comment by kingshalaby1** [comment]
Can you please provide an example of passing structs instead of `{id, %Ash.Changeset{}}`, I could not find any.

**Comment by zachdaniel** [comment]
Right now there are no examples. We first need to update the changeset code to accept instances of a resource (and not just take the primary key of changes), e.g: https://github.com/ash-project/ash/blob/master/lib/ash/changeset/changeset.ex#L340.

Probably a good way to do it would just be to make this function: https://github.com/ash-project/ash/blob/master/lib/ash/changeset/changeset.ex#L605 put the actual related record as context on the struct (using `Ash.Changeset.put_context()`), and then in the read requests in `Ash.Actions.Relationships`, you can use those values instead of running a query. Keep in mind that it may be mixed input, like `[%{id: 1}, %RelatedThing{...}]`.

In retrospect, this may not be a *great* first issue, but its a really good one to tackle!

**Comment by kingshalaby1** [comment]
in case of mixed input `[%{id: 1}, %RelatedThing{...}]`, PR: #135 checks if all inputs are valid entities or not. if one of them is not a valid resource, it lets the read query do his work normally. there will be no gain in passing other entities, as we will be hitting database anyway

**Comment by zachdaniel** [comment]
@kingshalaby1 perfect 👍
