### ISSUE TITLE
Proposal - emit warning for mismatched foreign key types in relationships

### ISSUE THREAD

**Issue by dantswain** [ash-project/ash#473]
Per discussion on discord.

Having a resource with an integer primary key and another resource that `belongs_to` it, the default attribute type for the foreign key is `uuid` so it's very easy to forget to change this.  It would be good if Ash could emit a warning (or even error) if it detects this situation.

```
defmodule MyApp.ResourceA do
  use Ash.Resource

  attributes do
    integer_primary_key :id
  end

  relationships do
    has_many :bs, MyApp.ResourceB
  end
end

defmodule MyApp.Resource B do
  use Ash.Resource

  relationships do
   belongs_to :a, MyApp.ResourceA, attribute_type :integer #<---here
  end
end
```

If one forgets to set the `attribute_type` in the `belongs_to` declaration, it can manifest in cryptic ways at runtime.

Another proposal might be to allow the user to configure the default type for primary keys to integer.

**Comment by zachdaniel** [comment]
We now emit a warning on potentially incompatible relationship attributes, and make the `belongs_to_type` configurable
