### ISSUE TITLE
Dependent loads not loaded with calculation on related resources

### ISSUE THREAD

**Issue by ahey** [ash-project/ash#475]
**Describe the bug**
When a calculation on a resource refers to a calculation on a related resource, the loads of the calculation on the dependent resource are not automatically loaded.

**To Reproduce**

Please [refer to this failing test case](https://github.com/ahey/ash/commit/22b1924a920efe70d96dc420f2dd8a596bd6340a).

**Runtime**
 - Ash `main` branch version [as of this commit](https://github.com/ash-project/ash/commit/2770c544a5d6b06ed2a6ca7bd547a15e92c315f6).

**Additional context**
The issue does not occur as of ash `2.4.30`.

**Comment by zachdaniel** [comment]
So this actually just isn't supported by expression calculations currently. The way that you do this kind of thing currently is by adding a "first" aggregate.

`first :user_name, :user, :name` and then you can refer to `user_name`.

Support for this will likely be added for to-one relationships in the future.
