### ISSUE TITLE
Source code examples are unreadable (CSS problem)

### ISSUE THREAD

**Issue by wintermeyer** [ash-project/ash#484]
**Describe the bug**

https://ash-hq.org/docs/guides/ash/latest/tutorials/get-started displays code with a dark color on a dark background.

<img width="1310" alt="Screenshot 2023-01-18 at 16 34 50" src="https://user-images.githubusercontent.com/69770/213215585-4cb7b599-b13b-4b61-9522-617f5014063c.png">

**To Reproduce**

Visit https://ash-hq.org/docs/guides/ash/latest/tutorials/get-started

**Expected behavior**

More contrast.

**Runtime**

 - OS: macOS 13.1
 - Browser: Safari

**Comment by zachdaniel** [comment]
Hey there! Thanks for the report. I'm actually deploying a fix as we speak :)

**Comment by zachdaniel** [comment]
Should be fixed within a couple of minutes.
