### ISSUE TITLE
Add `min_length` and `max_length` to array embed constraints

### ISSUE THREAD

**Issue by kingdomcoding** [ash-project/ash#487]
It's not obvious how to set a constraint on an array attribute.

1. Can the documentation be improved to make this easier?
2. I need to add a min_length to the attribute. Is that possible without custom validations?

**Comment by kingdomcoding** [comment]
```
attribute :attribute_name, {:array, EmbeddedResource}, constraints: [min_length: 1]
```
throws:
```
unknown options [:min_length], valid options are: [:name, :type, :constraints, :description, :sensitive?, :source, :always_select?, :primary_key?, :allow_nil?, :generated?, :writable?, :private?, :default, :update_default, :filterable?, :match_other_defaults?]
```

Am I doing something wrong?

**Comment by kingdomcoding** [comment]
New Error:

```
unknown options [:min_length], valid options are: [:sort, :load, :create_action, :update_action, :destroy_action, :read_action, :__source__]
```

**Comment by kingdomcoding** [comment]
Sorry 😅 

The original error was for

```
attribute :attribute_name, {:array, EmbeddedResource}, min_length: 1
```

**Comment by zachdaniel** [comment]
Ohhhh, okay :). That makes more sense.

So I forgot about this, but array embeds have their own special constraints, so you can't use `min_length` unfortunately. You'll need to write a custom validation for that. I'll leave this open to track adding `min_length` and `max_length` to the array embeds type.

**Comment by zachdaniel** [comment]
This has been addressed in `main`. You can now use the `min_length` and `max_length` constraints with arrays of embedded resources.
