### ISSUE TITLE
Embedded Schema Type Compilation Error

### ISSUE THREAD

**Issue by kingdomcoding** [ash-project/ash#489]
This compile error shows up for multiple embeds in my code.

```elixir
** (RuntimeError) {:array, MyApp.Very.Long.Alias.EmbeddedSchema} is not a valid type.
```

I work around it each time by commenting the call out, compiling, uncommenting and then recompiling.

What might be causing this issue?

**Comment by zachdaniel** [comment]
Do you have embedded schemas that reference each other? This can cause recursive compile time dependencies.

**Comment by zachdaniel** [comment]
You'll likely need to define multiple copies of the same embed if they recursively mention each other.

**Comment by kingdomcoding** [comment]
Well, the closest to that is that I'm defining multiple embeds in a single file

Does that matter?

**Comment by zachdaniel** [comment]
Yep! That could potentiall cause issues.

**Comment by kingdomcoding** [comment]
I've pulled out the embeds and it seems the problem is solved.

If it comes up again, comment on this issue.

In the meantime, I'll go ahead and close this issue.
