### ISSUE TITLE
Compile time list of attributes

### ISSUE THREAD

**Issue by kingdomcoding** [ash-project/ash#491]
Is it possible to get a list of the attributes for a given resource at compile time?

I'm trying to achieve:
```elixir
@derive {Jason.Encoder, only: @attributes}
```
where `@attributes` is the list of attributes

**Comment by zachdaniel** [comment]
You can do it, but its not *super* easy because other extensions can potentially add public attributes, they aren't known up front. What you could probably do is something like this:

```elixir
defmodule MyApp.Extension.JsonEncoder do
  use Spark.Dsl.Extension, transformers: [MyApp.Extensions.JsonEncoder.Transformers.DeriveJsonEncoder]
end

defmodule MyApp.Extensions.JsonEncoder.Transformers.DeriveJsonEncoder do
  use Spark.Dsl.Transformer
  
  def after?(_), do: true
  
  def transform(dsl) do
    public_attribute_names =
      dsl
      |> Ash.Resource.Info.public_attributes()
      |> Enum.map(&(&1.name))
    
    block = quote do
      @derive {Jason.Encoder, only: unquote(public_attribute_names)}
    end
    
    {:ok, Spark.Dsl.Transformer.eval(dsl, block)}
  end
end
```

**Comment by kingdomcoding** [comment]
Apparently, this expects a `bindings` argument:

```elixir
Spark.Dsl.Transformer.eval(dsl, block)
```

It throws an undefined function error and I don't know how this works so I can't resolve it on my own.

Kindly, guide me

**Comment by zachdaniel** [comment]
Try providing an empty list for the bindings :)
