### ISSUE TITLE
Add metadata attribute to read actions

### ISSUE THREAD

**Issue by csos95** [ash-project/ash#494]
**Is your feature request related to a problem? Please describe.**

I want to add a token field to a user resource in a sign-in action.  
The token is provided by `ash_authentication` and is put in the `__metadata__` field, but there is no metadata attribute on read actions to retrieve it.

**Describe the solution you'd like**

Add the metadata attribute to read actions.

**Describe alternatives you've considered**

A workaround provided by @zachdaniel was to have a token calculate field that pulls the token value from the `__metadata__` field.

```elixir
defmodule GetTokenFromMetadata do
  use Ash.Calculation

  def calculate(users, _, _) do
    Enum.map(users, fn user -> 
      Map.get(user.__metadata__, :token)
    end)
  end
end

calculate :token, :string, GetTokenFromMetadata
```

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

```elixir
  graphql do
    type :user

    queries do
      list :list_users, :read

      get :sign_in, :sign_in_with_password do
        as_mutation? true
        identity false
        metadata :token, :string # <- this is the attribute I'd like added
      end
    end

    mutations do
      create :register, :register_with_password
    end
  end
```

**Comment by zachdaniel** [comment]
Only one small addendum here, is that the `metadata` declaration would go on the action, and `ash_graphql` would key off of that to modify its response (would be configurable, but by default it would switch to a `result: record, ...metadata` style response) 
```elixir
read :sign_in_with_password do
  metadata :token, :string
end
```
And then what we'd do is add this information to `ash_authentication`, so any extension can leverage the fact that it returns additional metadata.

**Comment by zachdaniel** [comment]
Ash main and AshGraphql main have been updated to support this. A PR is open to `ash_authentication` to add the required metadata declarations to the actions in question to support this. When that happens, if you update to the latest of each dependency, you will get a compile time error in ash_graphql asking you to either 1. provide a new name for the type for that resolver, or 2. configure it such that the metadata fields aren't part of the type. Instructions will be in the error.

**Comment by zachdaniel** [comment]
I'll close this now as the core piece for this has been done, all thats left is to release ash/ash_graphql, and get the PR merged in ash_authentication.
