### ISSUE TITLE
Improve Ecto interop with compatibility mode for `Ecto.Association.NotLoaded`

### ISSUE THREAD

**Issue by frankdugan3** [ash-project/ash#495]
**Is your feature request related to a problem? Please describe.**

Now that the generated Ecto schemas support relationships, the escape hatches have really expanded a lot. One remaining issue for full interop is that Ash uses `%Ash.NotLoaded{}` instead of `%Ecto.Association.NotLoaded{}`. This can break various Ecto APIs as noted later.

**Describe the solution you'd like**

- After reading records or running actions, check for any relationships with %Ecto.Association.NotLoaded{} and replace them with %Ash.NotLoaded{}
  - Don't have to mess with the default not-loaded fields
  - The only incompatibility is "if you got this from ecto, you can't use it with Ash without calling `from_ecto/1` on your data first"
  - Provide a `to_ecto/1` also to allow Ash data to be used in Ecto
- This makes reading a bit slower because we have to transform all the results. So perhaps it should only be done with a compile time toggle so people who want the interop have to pay that cost.

**Describe alternatives you've considered**

- A PR to Ecto to enable configuring what structs are considered "not loaded" (unlikely to be accepted)
- Update everything in Ash to handle `%Ecto.Association.NotLoaded{}` and add an "Ecto compatibility mode" to use opt-in to using that instead.
  - Requires plugins are also updated
  - Adds another (awkward) type to handle in the end-user API

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

For example:
```elixir
# Compatible out of the box w/ Ecto
Repo.all from p in AshPostResource,
           join: c in assoc(p, :comments),
           where: c.published_at > p.updated_at,
           preload: [comments: c]
```
```elixir
Api.get!(SomeAshResource...) |> to_ecto()
# now this data is good to use with ecto
```
```elixir
Repo.one!(SomeEctoSchema |> from_ecto()
# now this data is good to use with ash
```

**Additional context**

There are various places in Ecto that depend on `Ecto.Association.NotLoaded` to function properly, for example:

```elixir
def assoc_loaded?(%Ecto.Association.NotLoaded{}), do: false
def assoc_loaded?(list) when is_list(list), do: true
def assoc_loaded?(%_{}), do: true
def assoc_loaded?(nil), do: true
```

**Comment by zachdaniel** [comment]
Sounds like a great solution!

**Comment by zachdaniel** [comment]
We've actually solved for this in `AshPostgres` by redefining our own `insert` functions, for example. We can continue to do that if other non-supported operations are needed. I'll close this for now in favor of handling it in `ash_postgres` as needed.
