### ISSUE TITLE
Controller doesn't match to route in the "Getting Started With Ash Authentication Phoenix" tutorial

### ISSUE THREAD

**Issue by wintermeyer** [ash-project/ash#496]
**Describe the bug**

If I follow the [Getting Started With Ash Authentication Phoenix](https://ash-hq.org/docs/guides/ash_authentication_phoenix/latest/tutorials/getting-started-with-ash-authentication-phoenix) tutorial I'll get the following bug when trying to access `/sign-in`

<img width="1023" alt="Bildschirm­foto 2023-01-28 um 08 56 29" src="https://user-images.githubusercontent.com/69770/215254429-b59bd3bb-3544-4717-9076-a1dccf0edce4.png">

The problem is that the route doesn't match to the controller name:

<img width="650" alt="Bildschirm­foto 2023-01-28 um 08 49 56" src="https://user-images.githubusercontent.com/69770/215254474-0d63f75d-f994-47d3-b84d-aa822cc83a83.png">

<img width="504" alt="Bildschirm­foto 2023-01-28 um 09 00 34" src="https://user-images.githubusercontent.com/69770/215254522-773ba058-0b1e-4962-ae53-45da01c79805.png">

One of the two has to be changed.

**To Reproduce**

Follow the [Getting Started With Ash Authentication Phoenix](https://ash-hq.org/docs/guides/ash_authentication_phoenix/latest/tutorials/getting-started-with-ash-authentication-phoenix) tutorial. Try to access `/sign-in` afterwords.

**Expected behavior**

<img width="1023" alt="Bildschirm­foto 2023-01-28 um 09 01 47" src="https://user-images.githubusercontent.com/69770/215254569-aa92d09c-676b-4a5f-a8a9-57ff49f39cea.png">

**Runtime**
 - Elixir 1.14.3
 - Phoenix 1.7rc2
 - macOS 13.1
 - Ash 2.5.8

**Comment by zachdaniel** [comment]
I believe the convention is not to be `Controllers` in the name in phoenix right? So let's change that one 😃 thanks for the report!

**Comment by zachdaniel** [comment]
https://github.com/team-alembic/ash_authentication_phoenix/pull/83
