### ISSUE TITLE
Increase the elixir/erlang matrix we use for CI

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#50]
We want to make sure we support more than just the latest elixir/erlang. Additionally, in our extension projects, we want to do the same thing, and also add the ash version to the matrix

**Comment by TheFirstAvenger** [comment]
@zachdaniel Do you have thoughts on how you would test different versions of ash in the extension projects?

**Comment by zachdaniel** [comment]
I haven't really worked it out yet, especially considering that things are currently changing fast enough that it's unlikely for an extension to support more than one version of ash. As it stabilizes though, I'll need a better plan. Additionally, there are parts of ash that can't really be tested without testing against extensions (specifically against ash_postgres). Right now those things are just untested. If you have thoughts/ideas let me know and we can get the ball rolling on better tests in that regard. Things are stabilizing just about enough to warrant it I think.

**Comment by TheFirstAvenger** [comment]
Ecto does something similar to allow you to test ecto_sql against different versions of ecto, I will see if I can do something similar here.

**Comment by TheFirstAvenger** [comment]
Also, as far as the Elixir/Erlang matrix:
Elixir:
v1.9 and below get the following:
```
== Compilation error in file test/actions/create_test.exs ==
** (BadFunctionError) expected a function, got: Ash.Dsl.Transformer
##[error]    (elixir) lib/enum.ex:2338: anonymous fn/3 in Enum.sort_by/3
##[error]    (stdlib) lists.erl:969: :lists.sort/2
##[error]    (elixir) lib/enum.ex:2338: Enum.sort_by/3
##[error]    (ash) lib/ash/dsl/transformer.ex:100: Ash.Dsl.Transformer.sort/1
##[error]    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
##[error]    (stdlib) erl_eval.erl:449: :erl_eval.expr/5
##[error]    (stdlib) erl_eval.erl:126: :erl_eval.exprs/5
##[error]    (stdlib) erl_eval.erl:888: :erl_eval.expr_list/6
##[error]    (stdlib) erl_eval.erl:411: :erl_eval.expr/5
##[error]    (stdlib) erl_eval.erl:126: :erl_eval.exprs/5
##[error]    (ash) /home/runner/work/ash/ash/test/actions/create_test.exs:5: Ash.Resource.__before_compile__/1
##[error]    (elixir) lib/code.ex:767: Code.require_file/2
##[error]    (elixir) lib/kernel/parallel_compiler.ex:211: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

And OTP earlier than 22 complain about `persistent_term` not being available, leaving Elixir 1.10, with OTP 23 and 22 as the only two viable options with the current codebase.

**Comment by zachdaniel** [comment]
One annoying thing: there are a bunch of repos in the ash organization, so we probably want to extend this and the last few changes to those repos. Don't feel obligated to do that though. I can periodically check to make sure those other (and less important aside from ash_postgres) repos are up to date with core.

**Comment by zachdaniel** [comment]
persistent_term is non-negotiable, but the sort function can absolutely be reworked.

**Comment by zachdaniel** [comment]
Speaking of that sort, I think transformer sorting is actually broken/bad, so I need to figure out a more efficient way to do it. Its a pretty bad bit of code :)

**Comment by TheFirstAvenger** [comment]
@zachdaniel with those 5 PRs in, is there anything else you would like to see to wrap up this ticket?

**Comment by zachdaniel** [comment]
Nope, I think you blew this one out of the water 😀
