### ISSUE TITLE
Add error message for page option in `read/2` with pagination not enabled 

### ISSUE THREAD

**Issue by minibikini** [ash-project/ash#505]
**Is your feature request related to a problem? Please describe.**

When pagination is not explicitly enabled in a resource, calling `MyApp.MyAPI.read!(MyResource, page: [limit: 1])` returns all the records instead of just one. This can lead to confusion and unexpected behavior.

**Describe the solution you'd like**

To address this problem, I propose that when the `page` option is present, but pagination is not enabled in a resource, `read/2` should return an error with clear information about how to set up pagination in the resource.

**Comment by kevinam99** [comment]
I could try working on this. Would appreciate any help with where to get started. I've been perusing the code base for some time but I haven't found that what needs to be updated. Thanks!

**Comment by zachdaniel** [comment]
Hey there! pagination is enabled if `action.pagination` is not `nil` or `false`. A great place to check this would be right here: 
https://github.com/ash-project/ash/blob/main/lib/ash/api/api.ex#L1007

Where we have the options they've provided and the action itself. Something like `Keyword.has_key?(opts, :page) && !action.pagination`
