### ISSUE TITLE
Change `first` aggregate behavior (in v3)

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#506]
At the moment, the `:first` aggregate always returns the first related value, even if it is `nil`. I think it would be more useful if it returned, by default, the first non-nil attribute. And if it does that, then `AshPostgres` can use the `FIRST_VALUE` aggregate, instead of the hacky `ARRAY_AGG(value)[0]` pattern that it uses now.

**Comment by jimsynz** [comment]
Will this cause issues with other data layers?

**Comment by zachdaniel** [comment]
It shouldn't. We'll have to update their beheavior too

**Comment by totaltrash** [comment]
Not that i need the feature, but might moving away from `array_agg` make `first` aggregates on `{:array, ...}` possible? https://github.com/ash-project/ash_postgres/issues/120

**Comment by zachdaniel** [comment]
Yep! It would indeed :)

**Comment by zachdaniel** [comment]
Good call

**Comment by zachdaniel** [comment]
This has been completed in 3.0 for ash core, still needs to be handled in AshPostgres.
