### ISSUE TITLE
A policy using `relates_to_actor_via()` fails if `require_actor? true` in API authorization when using the `ETS` DataLayer.

### ISSUE THREAD

**Issue by arjunbajaj** [ash-project/ash#513]
When using an `Ash.Resource` with the `ETS` data layer, if a policy uses `relates_to_actor_via([...])`, it may fail. This happens when `require_actor? true` is set on the `authorization` block in the API module.

The following error happens when trying to execute a `read!` on the resource (stacktrace below):
```
** (Ash.Error.Forbidden.ApiRequiresActor) The api API requires that an actor is provided at all times and none was provided.
```

**To Reproduce**

```elixir
# in api.ex

defmodule API do
  use Ash.Api

  ...

  authorization do
    authorize :always
    require_actor? true
  end
end
```

```elixir
# in resource.ex

defmodule TodoList do
  use Ash.Resource,
    data_layer: Ash.DataLayer.Ets,
    authorizers: [Ash.Policy.Authorizer]

  policies do
    policy always() do
      authorize_if always()
    end

    policy action_type(:read) do
      authorize_if relates_to_actor_via([:project, :user])
    end
  end

  attributes ...
  relationships ...

  actions do
    defaults [:read]
  end

  code_interface ... # defined for the read action
end
```

```
# in iex

# create the User, Project, and TodoList instances.
# then try to read `TodoList`

iex> TodoList.read!(%{}, [actor: user])

** (Ash.Error.Forbidden.ApiRequiresActor) The api API requires that an actor is provided at all times and none was provided.
    (ash 2.6.5) lib/ash/actions/helpers.ex:109: Ash.Actions.Helpers.add_actor/2
    (ash 2.6.5) lib/ash/actions/helpers.ex:67: Ash.Actions.Helpers.add_process_context/3
    (ash 2.6.5) lib/ash/actions/read.ex:72: Ash.Actions.Read.run/3
    (exp 0.1.0) lib/api.ex:11: API.load/3
    (ash 2.6.5) lib/ash/filter/runtime.ex:61: Ash.Filter.Runtime.filter_matches/4
    (ash 2.6.5) lib/ash/data_layer/ets/ets.ex:335: Ash.DataLayer.Ets.run_query/2
    (ash 2.6.5) lib/ash/actions/read.ex:1575: Ash.Actions.Read.run_query/6
    iex:16: (file)
```

**Expected behavior**

Expected behaviour is that the read query should succeed when `require_actor? true` is set in the API authorization block.

The `actor` should be passed down to all resources when executing relationship lookups. 

**Runtime**
 - Elixir 1.14.3
 - Erlang 25 `[erts-13.1.4]`
 - OS: macOS 13.1
 - Ash version: `~> 2.6.3`

**Additional context**

Discussion on Discord which led to this issue being discovered:
https://discordapp.com/channels/711271361523351632/955933117573652563/1075570420465549342

**Comment by arjunbajaj** [comment]
I have somewhat isolated the issue. I am not entirely sure if this bug is in the `DataLayer.ETS` module, or in `Actions.Read`.

I added a few `IO.inspect` calls in both of them, and as I see it, `DataLayer.ETS.run_query()` is called with two arguments, both don't contain the `actor`.

However, [this particular `Actions.Read.run_query` function](https://github.com/ash-project/ash/blob/fa0927263d93ffa0d7ab807cae3c55915d0025a0/lib/ash/actions/read.ex#L1563-L1579) calls the `DataLayer.run_query` callback.

This `Actions.Read.run_query` receives a `context`, which is currently ignored. The `actor` is only set in this `context` map.

I am not sure how to pass the `actor` to the data layer, and further, however, I noticed the [`Actions.Helpers.add_actor` function](https://github.com/ash-project/ash/blob/fa0927263d93ffa0d7ab807cae3c55915d0025a0/lib/ash/actions/helpers.ex#L93-L118) also checks the Process dictionary for the actor.

If I set the `actor` to the Process dictionary in `Actions.Read.run_query` function, the query does succeed. This confirms that the issue is that the actor is getting lost through the layers.


Below is the updated `Actions.Read.run_query()` function which works:

```elixir
# lib/ash/actions/read.ex line: 1563 in Ash 2.6.5
defp run_query(
        %{resource: resource, action: %{manual: nil}} = ash_query,
        query,
        context,
        load_attributes?,
        _aggregates_if_runtime,
        _calculations_if_runtime
    ) do

    if context[:actor] do
      Process.put(:ash_actor, {:actor, context[:actor]})
    end

    if ash_query.limit == 0 do
        {:ok, []}
    else
        query
        |> Ash.DataLayer.run_query(resource)
        |> Helpers.select(ash_query)
        |> Helpers.load_runtime_types(ash_query, load_attributes?)
    end
end
```

I hope this helps.

Also, I wonder why does it work in Postgres then? (I haven't tested personally, but I'm sure it must have come up by now if it didn't work).

**Comment by zachdaniel** [comment]
So the main reason it works in postgres is because postgres doesn't need to run additional queries to fetch related data, whereas ETS does. In postgres it simply joins to the tables, its handling it at a lower layer. So what we basically need to do is to set some private context on the quer that we're running in this case that its a "system query" and to not require that an actor be set.

**Comment by arjunbajaj** [comment]
The "system query" differentiator concept could be really powerful!

**Comment by arjunbajaj** [comment]
I would like to point out another problem that most likely arises from this same issue of the actor not getting passed through.

Assume that we have a `User`, `Project`, and `TodoList` resource. User has many projects, Project has many todo lists.

If a policy is set on the `TodoList` to authorize `relates_to_actor_via([:project, :user])`, if `require_actor? false` is set in the API, a `read` query does succeed.

However, if you also set a policy on `Project` which states `relates_to_actor_via([:user])`, then the `read` query on the `TodoList` will say its forbidden, as the actor is not passed through to the `Project` read query.

**Comment by zachdaniel** [comment]
Yep! Basically any internal reads done this way are going to need to have an option to not specify the actor. I haven't gotten around to this, but for now the ETS data layer just can't be used with `require_actor?` because it expects to be able to make queries to determine filter status (i.e not joining in the data layer).

**Comment by arjunbajaj** [comment]
Perhaps, in the meantime, a warning could be added to the documentation about not using relationships and policies with ETS, as they'll probably run into the same issue. Maybe even the getting started guide should just use Postgres instead of ETS?

I think that would avoid a lot of confusion for newcomers to Ash, like me.

**Comment by zachdaniel** [comment]
Relationship policies are fine with ets, the only thing that you can't do is use `require_actor?` with ETS. I'll fix it in the next few days, so probably not going to update the docs to account for it :D

**Comment by arjunbajaj** [comment]
That's amazing! 🚀
