### ISSUE TITLE
Rename `Ash.DataLayer.Simple` to `Ash.DataLayer.Ephemeral`

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#535]
`Ash.DataLayer.Simple` is not a good/descriptive name.

**Comment by zimt28** [comment]
Ephemeral sounds like this data layer still stores values somehow. We might want to call it something like `Ash.DataLayer.Struct` instead.

**Comment by zachdaniel** [comment]
Ultimately, this change is likely not worth the squeeze, as a name that is sufficiently better hasn't been found.
