### ISSUE TITLE
Using `:struct` in flow arguments is too strict

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash#543]
**Describe the bug**

The struct type in a flow argument should allow anything that is a struct (ie `is_struct/1` returns `true`), however it only matches arguments for which an `instance_of` constraint is present.
I noticed this while working on #541

**To Reproduce**
Remove `constraint instance_of: ...` lines from `Ash.Actions.Flows.Read` and call `Ash.Actions.Flows.Read.run(%Ash.Query{}, %Ash.Resource.Actions.Read{}, [])` and it will return an invalid flow result.

**Expected behavior**
it should return `{:ok, []}`

**Runtime**
 - Elixir version 1.14.3
 - Erlang version 25.2.2
 - OS macOS Ventura 13.2.1 (22D68)
 - Ash version `improvement/ash-read-flow-stub`
 - any related extension versions

**Comment by zachdaniel** [comment]
Fixed in [bacd54a](https://github.com/ash-project/ash/commit/bacd54a01bf516233e09427403d8e82ad5e2777d)
