### ISSUE TITLE
bug: Reading tenant resources fails with attribute multi-tenancy

### ISSUE THREAD

**Issue by georgevanderson** [ash-project/ash#567]
**Describe the bug**
Presently, storing a resource with attribute tenancy for ETS happens by creating an ETS table for each tenant <> resource combo. When reading it back, tenant is not set, which means we attempt to read from the plain module named ETS table. From a conversation in discord, we may want to change it so that attribute multi-tenancy does not create extra tables.

**To Reproduce**
A minimal set of resource definitions and calls that can reproduce the bug.

**Expected behavior**

**Runtime**
 - Elixir version
 - Erlang version
 - OS
 - Ash version
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Thanks for the report! Mind checking `main` to see if it resolves your issue?

**Comment by zachdaniel** [comment]
I'll reopen if not.

**Comment by georgevanderson** [comment]
Resolved! Thanks
