### ISSUE TITLE
Support descriptions at every level of the DSL

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#58]
We want to make sure that everything supports text descriptions, which can be used when scaffolding front end layers and building documentation.

- [x] actions
- [x] relationships
- [x] identities
- [x] validations
- [x] calculations
- [x] aggregates

**Comment by mario-mazo** [comment]
Hello I will start adding `description` to: 

- https://github.com/ash-project/ash/tree/master/lib/ash/resource/actions
- https://github.com/ash-project/ash/tree/master/lib/ash/resource/relationships

since those already have test coverage

**Comment by zachdaniel** [comment]
Remaining things to add descriptions to:

**Comment by zachdaniel** [comment]
Great work!
