### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by xln7** [ash-project/ash#590]
https://ash-hq.org/docs/guides/ash/latest/topics/security#d-ash-api-dsl-authorization-authorize

The http://ash-hq.org/docs/dsl/ash/latest/ash-api/dsl/authorization#authorize link leads to 'Not found'. The 'dsl' is also not capitalized and in general maybe change the title of this and the above segment to something more descriptive than just the library name?

**Comment by zachdaniel** [comment]
Alright, the broken link is fixed in the latest version of Ash, will be fixed on the next release. I've also fixed some stuff in `ash_hq` to properly display the specific option being linked to, not just the section.

**Comment by zachdaniel** [comment]
Thanks for the report!
