### ISSUE TITLE
Calculations can't access attributes of parent in multi-tenant context

### ISSUE THREAD

**Issue by oco-adam** [ash-project/ash#605]
**Describe the bug**

I'm trying to upgrade to the latest version of Ash (2.9.21) and my tests are failing after the upgrade.

In particular, I have code like this:

MyApi.load!(record, :some_calculation, tenant: t)

which previously worked, but now is giving an error of the form:

%Ash.Error.Invalid{
  errors: [%Ash.Error.Invalid.TenantRequired{
    resource: MyApi.MyParentResource, changeset: nil, query: nil, error_context: [], vars: [], path: [], stacktrace: #Stacktrace<>, class: :invalid}], stacktraces?: true, changeset: nil, query: #Ash.Query<resource: MyApi.MyChildResource, tenant: "org_tenant-id", calculations: %{some_calculation: #MyApi.Resources.MyChildResource.Calculations.SomeCalculation<[]>}, errors: [%Ash.Error.Invalid{errors: [%Ash.Error.Invalid.TenantRequired{resource: MyApi.MyParentResource, changeset: nil, query: nil, error_context: [], vars: [], path: [], stacktrace: #Stacktrace<>, class: :invalid}], stacktraces?: true, changeset: nil, query: #Ash.Query<resource: MyApi.MyParentResource, filter: #Ash.Filter<id == "02a8b6ac-140c-456e-b4a2-c4d5287bbbe3">, errors: [%Ash.Error.Invalid.TenantRequired{resource: MyApi.MyParentResource, changeset: nil, query: nil, error_context: [], vars: [], path: [], stacktrace: #Stacktrace<>, class: :invalid}], select: [:id, :inserted_at, :updated_at, ... :MyParentResource_type, ...]>, error_context: [], vars: [], path: [], stacktrace: #Stacktrace<>, class: :invalid}, %Ash.Error.Invalid.TenantRequired{resource: MyApi.MyParentResource, changeset: nil, query: nil, error_context: [], vars: [], path: [], stacktrace: #Stacktrace<>, class: :invalid}]>, error_context: [nil], vars: [], path: [], stacktrace: #Stacktrace<>, class: :invalid}

**To Reproduce**
See attached pull request for failing test

**Additional context**
discord support query: https://discordapp.com/channels/711271361523351632/1115573014155755520

**Comment by zachdaniel** [comment]
Fixed in dfe8bbf5f0466e3c5ea28cea4d1e32883fe9dd4a

Thank you for the reproduction!
