### ISSUE TITLE
Feat: Add option `sortable?` on attribute/calculate/aggregations in resource DSL

### ISSUE THREAD

**Issue by frankdugan3** [ash-project/ash#607]
**Is your feature request related to a problem? Please describe.**

Ash already provides a `filterable?` option to disable filtering, but it doesn't have an option to disable sorting. This is a similar performance concern, and it would be nice to be able to safeguard against slow or otherwise undesirable sorts.

**Describe the solution you'd like**

Add a `sortable?` boolean option (defaulting to `true`) to attributes, aggregates and calculations in the resource DSL. 

This option should also be respected by extensions like `AshGraphql`.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

For example

```elixir
  attributes do
    attribute :foo, :integer, sortable?: false # <- Adding `sortable?: false` here would prevent sorting
  end
```

**Comment by rgraff** [comment]
I could also use this but I would default to false. Nice to have: generate relevant migrations.

**Comment by zachdaniel** [comment]
Defaulting to false would be a breaking change unfortunately.

**Comment by rgraff** [comment]
Unfortunately, it would. I'm in favor of more opt-in in general

**Comment by zachdaniel** [comment]
I've added this feature, but it is still defaulting to `true` and I think that is the best default for now.
