### ISSUE TITLE
bulk_create ignores `upsert_identity` if set directly in the action

### ISSUE THREAD

**Issue by sezaru** [ash-project/ash#613]
**Describe the bug**
Setting a `upsert_identity` to the action will be ignored by a `bulk_create` function call.

**To Reproduce**
Just add a `upsert_identity` to a `create` action and then try to run `bulk_create`.

For example:

```elixir
    create :create do
      ...

      upsert? true
      upsert_identity :unique_uid
      upsert_fields [...]
    end
```

**Expected behavior**
`bulk_create` should use the action defined `upsert_identity` when defining the `on conflict` part of the query.

**Runtime**

   - Elixir version 1.14.4
   - Erlang version 25
   - OS Fedora 38
   - Ash version 2.9.27
   - any related extension versions ash_postgres: 1.3.30

**Additional context**
There is a discussion about this but in discord here: https://discord.com/channels/711271361523351632/1117271962532720761

**Comment by zachdaniel** [comment]
@sezaru I believe this should now be resolved in main. Please let me know :)

**Comment by sezaru** [comment]
Yep, working great!
