### ISSUE TITLE
many_to_many manage_relationship peculiarities 

### ISSUE THREAD

**Issue by kernel-io** [ash-project/ash#627]
I have a Tag resource that belongs in the Organization API, I have a Transaction resource that belongs in the Transactions API, there is a join resource between them called TransactionTag that is in the Transaction API registry. 

I am unable to manage_relationship :remove a Tag from a Transaction resource unless I also include the TransactionTag resource in the Organization registry. (I get a ResourceNotAllowed error on the Organization API otherwise),

Is this expected behaviour?

**Comment by dildayal** [comment]
Hello

**Comment by zachdaniel** [comment]
@kernel-io is there a stack trace associated with this error? I found a place that looks suspect, but don't have time to test it out, and it seems like it would result in the opposite behavior almost. I've pushed a branch you can try it out on: `many-to-many-manage-relationship-fix`

**Comment by zachdaniel** [comment]
Interesting...so you should actually be getting an error about this at compile time. When you use the `api SomeOtherApi` option on a `many_to_many` relationship, it also sets that for the underlying `has_many` relationship. So what you'd need to  do is split it up yourself:

```elixir
has_many :join_things, JoinThing

many_to_many :many_to_manyThings, ManyToManyThings do
  ...
  api DestinationApi
  join_relationship :join_things
end
```

The real issue is why you aren't getting compile time errors. If you're not on latest can you try upgrading?

**Comment by kernel-io** [comment]
nope for main, I've already got the join resource defined, I think the core of my issue is I think the join resource should be defined on the 'Transactions' API, but it only works if it is defined on the 'Organizations' API.

(Transaction (Transactions) -> TransactionTag (Transactions) -> Tag (Organization)

**Comment by zachdaniel** [comment]
Hm…I’d triple check that third case if possible, like aliases/things like that.if neither of those two cases worked(1 or 3) basically nobody could have cross api many to many relationships and I know that they do. Strange that #1 isn’t an error though…

**Comment by kernel-io** [comment]
transaction.ex
```elixir
    many_to_many :tags, VMX.Organizations.Tag,
      api: VMX.Organizations,
      through: VMX.Transactions.TransactionTag,
      source_attribute_on_join_resource: :transaction_id,
      destination_attribute_on_join_resource: :tag_id,
      join_relationship: :tags_join_assoc
```

transaction_tag.ex
```elixir
  relationships do
    belongs_to :tag, VMX.Organizations.Tag, api: VMX.Organizations, allow_nil?: false

    belongs_to :transaction, VMX.Transactions.Transaction,
      api: VMX.Transactions,
      allow_nil?: false
  end
  ```
  
  tag.ex
  ```elixir
    relationships do
    belongs_to :organization, VMX.Organizations.Organization

    many_to_many :transactions, VMX.Transactions.Transaction,
      api: VMX.Transactions,
      through: VMX.Transactions.TransactionTag,
      source_attribute_on_join_resource: :transaction_id,
      destination_attribute_on_join_resource: :tag_id,
      join_relationship: :tags_join_assoc
  end
  ```

I've checked and there's no aliases etc 🤔

**Comment by zachdaniel** [comment]
I was thinking of aliases in the registries where you included them, i.e in scenario #3 where you said you added them to the source registry but still got an error about it.

**Comment by kernel-io** [comment]
registries are bare with no aliases either, scenario 3 is when I have the transactiontag in solely the Organizations Registry

**Comment by zachdaniel** [comment]
oh, but for scenario #3 you also need to define the join relationship yourself and configure its api.
