### ISSUE TITLE
Better documentation for custom validations

### ISSUE THREAD

**Issue by DaniruKun** [ash-project/ash#631]
**Is your feature request related to a problem? Please describe.**
I don't think there is a single resource or guide out there how to add custom validations. The only demonstration is this part: https://ash-hq.org/docs/module/ash/latest/ash-resource-validation

**Describe the solution you'd like**
A real world example of implementing your own `Validation`, including how to use the `init/1` and `validate/2` callbacks, and an example of returning both a pass and an error.

**Describe alternatives you've considered**
I've tried searching online and in the docs, but there aren't really any end-to-end guides on this, just how to use the built-in validations.

**Additional context**
First mentioned in the Discord: https://discord.com/channels/269508806759809042/828361963826184252/1122518418030071901

**Comment by zachdaniel** [comment]
I've added a new guide for this.
