### ISSUE TITLE
`%Ash.NotSelected{}`

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#634]
Currently when a field is not selected, we fill it in with a `nil` value. This is unideal and uncommunicative. We should instead fill them in with `%Ash.NotSelected{}`.

**Comment by barnabasJ** [comment]
Maybe something like `%Ash.NotProvided` would also be nice when using embedded types as input arguments and not all values were provided. Right now, it is impossible to distinguish between a field that should be set to null and a value that was not provided.

**Comment by ghalestrilo** [comment]
I'm looking into this one - there are multiple levels in the callback stack where this `nil` could be changed. Is [`Ash.Actions.Read:1471`](https://github.com/ash-project/ash/blob/d09c6941327082ca42c569ee45d9fe7781d80cf8/lib/ash/actions/read.ex#L1471) the best place to hook this logic or does it belong somewhere else?

**Comment by zachdaniel** [comment]
I think the most concise place to put it would be here:
https://github.com/ash-project/ash/blob/d09c6941327082ca42c569ee45d9fe7781d80cf8/lib/ash/actions/helpers.ex#L656

We're going to need to flag this feature behind 3.0, as there will certainly be some places to adjust this logic and various downstream effects that need to be handled.

**Comment by zachdaniel** [comment]
This has been merged into the 3.0 branch.
