### ISSUE TITLE
Bug in the example code for Idiomatic Actions

### ISSUE THREAD

**Issue by hanrelan** [ash-project/ash#635]
**Describe the bug**
The [documentation for idiomatic actions](https://ash-hq.org/docs/guides/ash/latest/topics/actions#idiomatic-actions) includes a bug. 
It has this action:
```elixir

code_interface do
  define_for Helpdesk.Support

  define :top, args: [:user_id]
end

read :top do
  argument :user_id, :uuid do
    allow_nil? false
  end

  prepare build(limit: 10, sort: [opened_at: :desc])

  filter expr(priority in [:medium, :high] and representative_id == ^arg(:user_id) and status == :open)
end
```

with this example usage:
```elixir
Ticket
|> Ash.Query.for_read(:top)
|> Ash.Query.filter(opened_at > ago(10, :minute))
|> Helpdesk.Support.read!()
```

But the `top` action takes a `user_id` which isn't being passed in in the example.

**To Reproduce**
N/A

**Expected behavior**
The user id is passed in in the example

**Runtime**
Live as of June 28 2023 on https://ash-hq.org/

**Comment by franckstifler** [comment]
WIP

**Comment by franckstifler** [comment]
https://github.com/franckstifler/ash/pull/2

**Comment by juhalehtonen** [comment]
This seems to have been fixed, per https://ash-hq.org/docs/guides/ash/latest/topics/actions#idiomatic-actions

**Comment by zachdaniel** [comment]
Thanks for pointing that out :D
