### ISSUE TITLE
Rename `define_for` in code interface.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash#638]
The `define_for` option in the code interface DSL section is confusing to many (including me when I started). For Ash 3.0 let's deprecate it and replace it with `define_for_api` or `default_api`.

**Comment by zachdaniel** [comment]
Good idea. Maybe we should make it required, and call it `api`

**Comment by joshprice** [comment]
@Theosaurus-Rex just ran into the issue where `define_for` was missing and no functions were generated with no warning. I'm looking at how to improve this in #691 

At a minimum it should be required, since no functions are generated without it.

**Comment by zachdaniel** [comment]
I know I mentioned it couple maybe be required in my other comment but that doesn't actually work with all setups. There are two different ways to use the code interface, only one of which involves the `define_for` option (which is why it's not required)

**Comment by vonagam** [comment]
Why not introduce a single top level `api` on a resource? 

There is `define_for` in `code_interface` and `api` in `authentication`. It can be useful for other potential extensions to avoid repetition too.

As for `code_interface`, two ways to use it and potential confusion - here is a possible solution to resolve this in ash 3:

- Validate that top level `api` is present if `code_interface` is used. Even for `define_interface` use case it will still need the api. Right now it is provided through an argument there. Instead make it accept only a resource and lookup api on it. 
- To allow skipping defining methods on a resource add new boolean property (with name completely up to you). With methods being defined by default.

**Comment by zachdaniel** [comment]
I think we can do this, yes. It would essentially act as a default for any api-related options. Something like:

```elixir
use Ash.Resource, api: YourApi
```

Actually...if we do it this way, we could introduce it without requiring 3.0. It would be opt-in. Would anyone be interested in tackling this? We could also include a verifier (not a transformer) that verifies that the resource is accepted by that api.

**Comment by vonagam** [comment]
> Instead make it accept only a resource and lookup api on it.

After thinking, this part might be a little problematic in a sense that it might be impossible to do at compile time and so the api lookup (even thought it will be fast) will need happen on every call.

Crazy idea, not attached to it, but if Ash had an enforced convention of naming between an Api and its Resources then there will be no need to specify those Apis at all (in mentioned places and in relationships and in flows). As I see it there is a clear candidate for such convention (which can be found in "real world" project) - `Api.Resource`. So for resource `Realworld.Articles.Favorite` the api is `Realworld.Articles`.

It will definitely simplify things (for example right now I am writing `many_to_many` relationship and a through resource and a destination one live in different apis, but there is only one `api` option on the relationship, so I have to write a join relathionship). What do you think about such convention?

**Comment by zachdaniel** [comment]
I'd (strongly) prefer to stay away from any file-name/module-name based being used in core. Looking up an api given a resource wouldn't be problematic, as the resource would have it explicitly i.e `api: Api`. We could also then add `Ash.create(...)` and friends, that only work with resources that have an explicit api configured, and will pass through to the underlying api. Then you don't have to call the specific Api module anymore. Only when using resources that *might* appear in multiple APIs. I'm actually quite interested in this approach, and it could be done before 3.0 and would likely significantly increase the quality of life for many users.

**Comment by jimsynz** [comment]
I'm gonna be the guy that asks the question: can we get rid of APIs altogether? I'm not 100% sure that they bring enough to the table.

Things I know that they do:

- Maintain a list of resources for introspection
- Allow extensions to apply defaults across a group of resources
- Play some role in actions but TBH I'm not sure what. 

What else are they doing in the system?

**Comment by zachdaniel** [comment]
They enforce context boundaries, i.e you have to explicitly pass them to relate or talk to another api. I think we need them. They provide things like security configuration across your resources.

**Comment by jimsynz** [comment]
Asked and answered. Keen to have a default API option for resources. Let's make it so.

**Comment by zachdaniel** [comment]
`code_interface.define_for` has been changed to `code_interface.api` in the 3.0 branch (and will be further changed to `code_interface.domain` when that change is made)

**Comment by jimsynz** [comment]
We can make it optional too if the `api` option is present.

**Comment by zachdaniel** [comment]
yep! It is already.
