### ISSUE TITLE
Policy Breakdown can't handle FieldPolicies

### ISSUE THREAD

**Issue by barnabasJ** [ash-project/ash#648]
**Describe the bug**
If a field policy fails and the breakdown should be logged, there is an exception.

**To Reproduce**
add the following line in the config and run the field policy tests
```
config :ash, :policies, show_policy_breakdowns?: true, log_policy_breakdowns: :error
```

**Expected behavior**
Policy Breakdown is logged to the console

**Runtime**
 - Elixir version 1.14.3
 - Erlang version 25.2.1
 - OS Ubuntu 22.04
 - Ash version 7deaa7c1ebe4d183f90ea205ea0511eb254227d8
 - any related extension versions

**Comment by zachdaniel** [comment]
Fixed in main
