### ISSUE TITLE
Ash.Changeset.manage_relationship raises Invalid Input when the identity/key is a ci_string

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash#656]
**Describe the bug**
Related to this [discussion in discord](https://discord.com/channels/711271361523351632/1129194710058139648/1129194710058139648), when using `Ash.Changeset.manage_relationship` an identity/key that is a `:ci_string`, the key is being validated because it is a struct and raising an error as invalid input. It should only be validated when it is a resource, not simply a struct.

**To Reproduce**
Given a relation that uses a ci_string (not uuid):
```elixir
    belongs_to :feature, MyApi.Feature do
      allow_nil? false
      source_attribute :feature_name
      attribute_type :ci_string
      destination_attribute :name
    end
```

I would expect this change to work using value_is_key option:
```elixir
      argument :feature_name, :ci_string, allow_nil?: false
      change manage_relationship(:feature_name, :feature,
               type: :append,
               value_is_key: :name,
               use_identities: [:name]
             )
```

But it gives me this error, but I thought the purpose of value_is_key is to not provide a struct:
```elixir
     ** (Ash.Error.Invalid) Input Invalid
     * Invalid value provided for feature: cannot provide structs that don't match the destination.
```

For reference, this more verbose change  does work:
```elixir
      argument :feature_name, :ci_string, allow_nil?: false

      change fn changeset, _ ->
        case Ash.Changeset.get_argument(changeset, :feature_name) do
          nil ->
            changeset

          feature_name ->
            Ash.Changeset.manage_relationship(
              changeset,
              :feature,
              %{name: feature_name},
              type: :append,
              use_identities: [:name]
            )
        end
      end
```

**Expected behavior**
The manage_relationship function should raise Ash.Error.Invalid

**Runtime**
- Latest Ash version

**Additional context**
I believe this is the line that needs to be changed: https://github.com/ash-project/ash/blob/216755b2759ded1ed24eab877f76ac0e384c638a/lib/ash/changeset/changeset.ex#L2796

**Comment by rgraff** [comment]
FWIW: I would skip this check if using the `value_is_key` but otherwise check the validity of all structs.

**Comment by zachdaniel** [comment]
There is actually an implicit `value_is_key: <the_primary_key>` if a non-resource value is passed, so we'll have to do it each time.

**Comment by zachdaniel** [comment]
This should be fixed in main
