### ISSUE TITLE
Code interface-generated functions should check the type of their first argument and return an expressive error

### ISSUE THREAD

**Issue by rellen** [ash-project/ash#679]
**Is your feature request related to a problem? Please describe.**
We’ve run into an issue that I think could be solved with some explicit argument checking so that the error returned could be a more specific Ash error.  When calling a function defined by a code interface element on a resource, if the first argument is not an instance of the resource, a `FunctionClauseError` is returned.   This error does not make it clear why there was no match.

```elixir
  MyApp.MyResource.accidentally_get_an_array_of_records_instead_of_just_one(...)
  |> MyApp.MyResource.some_update(params, opts)

  * (FunctionClauseError) no function clause matching in MyApp.MyResource."-inlined-some_update/3-"/3
```

**Describe the solution you'd like**
It seems like the type of the first argument of such functions could be checked in the generated function and a more expressive error be returned.  This could be an Ash error, possibly based off the `Invalid` class.

**Describe alternatives you've considered**
N/A

**Comment by src-r-r** [comment]
Thanks, @rellen, I'm working on this issue!
