### ISSUE TITLE
Remove Earmark warning on `Ash.Resource.Dsl`

### ISSUE THREAD

**Issue by joshprice** [ash-project/ash#690]
**Describe the bug**

Running `mix docs` produces the following warnings:

```sh
$ mix docs
Compiling 125 files (.ex)
Generating docs...
warning: ExDoc.Markdown.Earmark (error) lib/ash/resource/dsl.ex:3140 Fenced Code Block opened with ``` not closed at end of input

View "html" docs at "doc/index.html"
warning: ExDoc.Markdown.Earmark (error) lib/ash/resource/dsl.ex:3140 Fenced Code Block opened with ``` not closed at end of input

View "epub" docs at "doc/ash.epub"
```

It does not however seem to affect the output of the docs. It's also not caused by any of the explicit triple backtick code blocks defined in the file, so must occur in generated code blocks (from examples etc)

**To Reproduce**

Run `mix docs`

**Expected behavior**

No warnings should be produced.

**Runtime**

- elixir  1.15.4
- erlang 26.0.2
- ash main (2.14.11)

**Comment by zachdaniel** [comment]
Been trying to figure out where this comes from for ages :)

**Comment by joshprice** [comment]
Removing all the triple backtick blocks in https://github.com/ash-project/ash/commit/cedcda903fc2f11ed85f3746cc64cd3810738ed6 did not remove the warning... Suspect it's generated from other blocks or it could be an earmark issue?

**Comment by zachdaniel** [comment]
Yeah, in that file we show every DSL doc for all of the resource DSL.

**Comment by juhalehtonen** [comment]
Has this been fixed, or am I missing some steps? 

```
juha@2080:~/projects/elixir/ash$ mix docs
Generating docs...
View "html" docs at "doc/index.html"
View "epub" docs at "doc/ash.epub"
```

I couldn't reproduce this using the following:

* Elixir 1.15.5 (compiled with Erlang/OTP 26)
* Erlang/OTP 26.1
* Ash main / 2.14.20

The issue doesn't reproduce for me even on cedcda9 referred to by @joshprice above.

I see earmark and earmark_parser have received some recent updates, but mix.lock doesn't point to them.

I tested this on Ubuntu22.04@WSL2, although I can't see why that would affect the results.

**Comment by zachdaniel** [comment]
I'm pretty sure we got this taken care of, yes. We changed up our strategy around DSL docs in hex which effectively eliminated this issue.
