### ISSUE TITLE
Error messages are duplicated on nested form for union resources

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#692]
**Describe the bug**

I noticed this one today - error messages being duplicated in our UI on form submission.

<img width="659" alt="Screenshot 2023-09-13 at 3 19 49 pm" src="https://github.com/ash-project/ash/assets/543859/9a9c9d80-b1aa-42f4-9564-5b234456c5e3">

#### Resource setup

This is a form for a Vendor resource that has an embedded AccessInfo resource (which is a union type), and `api_key` is a field on one of AccessInfo union types.

The `submit_errors` on the form for the nested `access_info` look like:

```
      submit_errors: [
        api_key: {"is required", []},
        api_key: {"argument api_key is required",
         [field: "api_key", message: "argument api_key is required"]}
      ],
```

The parent form for the vendor has an empty `submit_errors` on it.

This bug was introduced when upgrading Ash from [2.14.1 to 2.14.2](https://github.com/ash-project/ash/compare/v2.14.1...v2.14.2) - I suspect in the commit about union errors.

**Expected behavior**

Before Ash 2.14.2, this rendered a single error - the "is required" error.

**Runtime (at time of error introduction)**
 - Elixir version: 1.14.3-otp-25
 - Erlang version: 25.3.2
 - OS: macOS Ventura
 - Ash version: 2.14.2
 - any related extension versions: AshPhoenix 1.2.16 (maybe related?)

**Comment by zachdaniel** [comment]
Got this reproduced 👍
