### ISSUE TITLE
Reference to `ash_postgres` guides in the relationship guides.

### ISSUE THREAD

**Issue by franckstifler** [ash-project/ash#695]
In the Ash relationships guides, we should link to the `ash_postgres` guides about the `references` macro. This would clarify how actions such as `destroy` impacts related resources.

A text such as "Your data layer may enforce foreign key constraints, see the following guides for more information" should do the trick.

**Comment by fcapovilla** [comment]
I've create a small pull request adding the link in the documentation.

I wasn't sure if adding a new subsection on this subject was necessary, so I added the link in the `Managing related data` subsection.
