### ISSUE TITLE
Rename utc_datetime to datetime

### ISSUE THREAD

**Issue by pragdave** [ash-project/ash#704]
In the API we have 

https://ash-hq.org/docs/module/ash/latest/ash-type-date
https://ash-hq.org/docs/module/ash/latest/ash-type-time
https://ash-hq.org/docs/module/ash/latest/ash-type-utcdatetime

It looks as if both :date and :time default to UTC/ISO calendar, so I got a little confused by the naming.

I wonder: is the fact it's UTC actually part of the type? Or might it make sense just to have :date, :time, and :datetime, and specify that the representation of these is in UTC/ISO, in the same way that :string specifies the type and UTF-8 is the representation?

**Possible solution**
* Rename `utc_datetime` to `datetime`
* Possibly add `timezone` as a constraint.

**Comment by zachdaniel** [comment]
I've added this to `main`. `:utc_datetime` and `:utc_datetime_usec` have been redefined as `Ash.Type.NewType`s that configure the `:datetime` type

```elixir
defmodule Ash.Type.UtcDatetime do
  @moduledoc """
  Represents a utc datetime. A wrapper around `:datetime` for backwards compatibility.
  """
  use Ash.Type.NewType, subtype_of: :datetime, constraints: [precision: :second]
end
```

For example. I've added a `timezone` constraint, however it currently defaults to `:utc` and *only* allows `:utc`. I've added it as a signal for future design.

**Comment by zachdaniel** [comment]
I'll have to see how this affects extensions that derive types for interfaces, they may need to handle these type changes, it depends :)

**Comment by pragdave** [comment]
I don't think I've ever seen a suggestion got from idea to closed this quickly, particularly one that not particularly critical.

A tip o' the hat, sir.
