### ISSUE TITLE
`ash_graphql` cannot query related things due to the query engine.

### ISSUE THREAD

**Issue by tunchamroeun** [ash-project/ash#717]
**Describe the bug**
cannot query related things in `ash_graphql`
[discussion link](https://discord.com/channels/711271361523351632/712035333432147989/1158214213261606973)

**To Reproduce**
#### - Calculations
```elixir
calculate :ilike, :boolean, expr(ilike(ref(^arg(:field)), ^arg(:term))) do
    argument :field, :atom, constraints: [one_of: [:name, :latin]], allow_nil?: false
    argument :term, :string, allow_nil?: false
end
```
#### GraphQL
```gql
{
  listInvoices{
    count
    pageInfo{
      hasNextPage
      hasPreviousPage
      endCursor
    }
    edges{
      cursor
      node{
        id
        student{
          ilike(field: LATIN, term: "TUN CHAM ROEUN") # <- here
          id
          name
          latin
          profile
          insertedAt
          updatedAt
        }
        invoiceDate
        insertedAt
        updatedAt
      }
    }
  }
}
```
#### - Errors
![Error](https://media.discordapp.net/attachments/712035333432147989/1158214884547379300/Screenshot_2023-10-02_at_8.32.01_in_the_morning.png)

**Expected behavior**
Getting `invoices`'s result related to `students`.

**Comment by zachdaniel** [comment]
Hey @tunchamroeun, thanks for the report! I think this bug is actually in ash core. I've just pushed something up to `main` that should resolve the issue.
