### ISSUE TITLE
Use attribute/argument descriptions in code interface for better documentation.

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#720]
Right now we don't document what each argument means and what attributes are available. This would be a huge QOL improvement without being an immense amount of work.

**Comment by rellen** [comment]
I have a draft PR for this feature. https://github.com/ash-project/ash/pull/721

I am not sure what format and particular details we think might be useful, so very happy to receive suggestions.

**Comment by zachdaniel** [comment]
Completed in 3.0. Sorry @rellen I didn't realize there was draft work for this! 🙇

**Comment by rellen** [comment]
All good.  I forgot that I was part way through this.
