### ISSUE TITLE
Boolean (false) argument in read action translate to nil

### ISSUE THREAD

**Issue by tellesleandro** [ash-project/ash#722]
**Describe the bug**
I have a read action with the argument :voucher, :boolean, allow_nil?: false.
If I call the action passing the argument as true, the genereated query receives the value true for the :voucher argument. If I call the action passing the argument as false, the genereated query receives the value nil for the :voucher argument. I’ve already tried to remove the allow_nil? false and the result is the same.

**To Reproduce**
Define in code_interface a read action with args: [:arg]:
```elixir
code_interface do
    define :for_something, args: [:arg], action: :for_something
end

actions do
    read :for_something do
      argument :arg, :boolean, allow_nil?: false

      filter expr([
               field: args(:arg)
             ])
    end
end
```

Call the action: Resource.for_somethind(false)

**Expected behavior**
Query returns all records where field == false

**Runtime**
Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]
Elixir 1.15.4 (compiled with Erlang/OTP 24)
Linux XPS 6.0.0-1021-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep 7 14:25:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ash": {:hex, :ash, "2.15.7"
ash_authentication": {:hex, :ash_authentication, "3.11.15"
ash_authentication_phoenix": {:hex, :ash_authentication_phoenix, "1.8.4"
ash_phoenix": {:hex, :ash_phoenix, "1.2.19"
ash_postgres": {:hex, :ash_postgres, "1.3.52"

**Comment by zachdaniel** [comment]
```elixir
code_interface do
    define :for_something, args: [:arg], action: :for_something
end

actions do
    read :for_something do
      argument :arg, :boolean, allow_nil?: false

      filter expr([field: ^arg(:arg)])
    end
end
```
It should be `arg/1`, not `args/1` Is that a typo in your example? Also you need to use the `^`.

**Comment by zachdaniel** [comment]
oh, wow. Good find :) Will fix in a sec.

**Comment by zachdaniel** [comment]
Fix will be available in `v2.15.8` when it is done deploying

**Comment by tellesleandro** [comment]
Sorry. It's a type.  Fixes. If I change filter expr([field: arg(:arg)]) to filter expr([field: ^arg(:arg)]), I receive an error:

error: misplaced operator ^arg(:arg)

The pin operator ^ is supported only inside matches or inside custom macros. Make sure you are inside a match or all necessary macros have been required

**Comment by zachdaniel** [comment]
Yeah, you're right, in the keyword list syntax like that it's not used. My bad.

**Comment by 5avage** [comment]
Seeing the same thing today with boolean Flow arguments, when `true` passed it's `true`, when `false` passed they become `nil` in the step inputs.

**Comment by zachdaniel** [comment]
I think its the exact same bug but somewhere else.

**Comment by zachdaniel** [comment]
Okay @5avage could you try `main`? It should be fixed now :)

**Comment by 5avage** [comment]
Verified, thanks!
