### ISSUE TITLE
Keyset pagination does not work when resource is ordered by a timestamp with time zone field and the time zone is different from UTC

### ISSUE THREAD

**Issue by tellesleandro** [ash-project/ash#726]
**Describe the bug**

Keyset pagination does not work when resource is ordered by a timestamp with time zone field and the time zone is different from UTC.

**To Reproduce**

1. Define a resource with an attribute of type utc_datetime_usec and with a preparation to shift the time zone of the attribute to any other than UTC.
2. Query the resource:
```elixir
page = Resource |> Ash.Query.for_read(:read_action) |> Ash.Query.sort([:utc_datetime_usec_field]) |> Api.read!(page: [limit: 1])
```
3. Get the first record and set the before_key:
```elixir
first_record = List.first(page.results)
before_key = first_record.__metadata__.keyset
```
4. Query the resource again, passing the before_key:
```elixir
page = Resource |> Ash.Query.for_read(:read_action) |> Ash.Query.sort([:utc_datetime_usec_field]) |> Api.read!(page: [limit: 1, before: before_key])
```
The result is the same as in the first read call.

**Expected behavior**

The result is empty.

**Runtime**

Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]
Elixir 1.15.4 (compiled with Erlang/OTP 24)
Linux XPS 6.0.0-1021-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep 7 14:25:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ash": {:hex, :ash, "2.15.7"
ash_authentication": {:hex, :ash_authentication, "3.11.15"
ash_authentication_phoenix": {:hex, :ash_authentication_phoenix, "1.8.4"
ash_phoenix": {:hex, :ash_phoenix, "1.2.19"
ash_postgres": {:hex, :ash_postgres, "1.3.52"

**Additional context**

- Postgres time zone is set to America/Sao_Paulo (GMT-03).
- If I run the second Ash's query manually on PG and change the field's type from "timestamp" to "timestamp with time zone", the result is correct.
- Although Ash's type utc_datetime_usec is meant to work on UTC data, systems around the world have to work on time zones others than UTC. One way to do it is at query level, so the resource's attributes have always the correct value. 
- Two possible solutions are: chage the field type when building the query from "timestamp" to "timestamp with time zone"; or shift zone of all utc_datetime_usec fields to UTC before build the query.

**Comment by zachdaniel** [comment]
Can I see the preparation that shifts the time zone? I think the issue here is that we're building the keyset based off of the transformed data but it should always be based on the underlying data.

**Comment by zachdaniel** [comment]
This actually may be a problem in general when overwriting attribute values. I'm thinking that the strategy of updating the value of the datetime in a preparation is actually what is causing the issue, and instead you'd want a custom type here.

**Comment by tellesleandro** [comment]
Hi Zach,

I apologize for the delay, but I've been busy today.

I'll provide as much information as possible, while keeping it as simple as I can.

## Table structure

```postgres
CREATE TABLE public.estadias (
	id uuid NOT NULL,
	inserted_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	entrada_confirmada_em timestamptz NULL,
	CONSTRAINT estadias_pkey PRIMARY KEY (id)
);
```

## Resource

```elixir
defmodule Estadia do
  use Ash.Resource, data_layer: AshPostgres.DataLayer
  use TimeZone, [:entrada_confirmada_em]

  preparations do
    prepare fn query, _ ->
      Ash.Query.after_action(query, fn query, results ->
        time_zone = "America/Sao_Paulo"

        results =
          __MODULE__.shift_zone(results, time_zone)

        {:ok, results}
      end)
    end
  end

  code_interface do
    define_for Garagem.Operacional
    define :list, action: :list
  end

  actions do
    read :list do
      pagination keyset?: true, default_limit: 20, countable: true
    end
  end
end
```

## TimeZone module

```elixir
defmodule TimeZone do
  defmacro __using__(fields) do
    quote do
      def shift_zone([], _), do: []

      def shift_zone([%{} | _] = structs, time_zone) do
        shift_zone(structs, time_zone, unquote(fields))
      end

      defp shift_zone([%{} | _] = structs, time_zone, fields) do
        Enum.map(structs, fn struct ->
          shift_zone(struct, time_zone, fields)
        end)
      end

      defp shift_zone(%{} = struct, time_zone, fields) do
        Enum.reduce(fields, struct, fn
          field, acc ->
            new_value =
              case Map.get(acc, field) do
                %DateTime{} = value ->
                  case DateTime.shift_zone(value, time_zone) do
                    {:ok, value} -> value
                    {:error, _} -> value
                  end
              end

            Map.put(acc, field, new_value)
        end)
      end
    end
  end
end
```

## First query (w/o pagination)

```elixir
%{results: results, count: count} =
  Estadia
  |> Ash.Query.for_read(:list)
  |> Ash.Query.sort([:entrada_confirmada_em])
  |> Api.read!(page: [limit: 1])
```

## Gets first and last records

```elixir
first_record = List.first(results)
last_record = List.last(results)
```

## Second query (w/ pagination)

```elixir
%{results: results, count: count} =
  Estadia
  |> Ash.Query.for_read(:list)
  |> Ash.Query.sort([:entrada_confirmada_em])
  |> Api.read!(page: [limit: 1, before: first_record.__metadata__.keyset])
```

or

```elixir
%{results: results, count: count} =
  Estadia
  |> Ash.Query.for_read(:list)
  |> Ash.Query.sort([:entrada_confirmada_em])
  |> Api.read!(page: [limit: 1, after: last_record.__metadata__.keyset])
```

The second query returns the same (1) record that was returned in the first query.

If you need any further information, such as the queries sent to PG, please let me know, and I'll reproduce all these steps.

**Comment by zachdaniel** [comment]
Can you please try against `ash` `main`?

**Comment by tellesleandro** [comment]
I didn't work.

Let me try to add more information.

The following 3 statements are the queries that I (Ash) run in sequence before I render a (html) table. I have to do it because I need to know, before I render the table, if there's or there's not previous and next pages. I'm not sure if this strategy is the best one. If you have any advice on that, I'd like to hear.

## Main query (to get records to show on table)

```postgres
SELECT e0."id", e0."inserted_at", e0."updated_at", e0."entrada_solicitada_em FROM "estadias" AS e0 ORDER BY e0."entrada_solicitada_em" DESC, e0."id" LIMIT 251;
```

## Returned rows (there is only 5 records on the table)

```text
id                                  |inserted_at                  |updated_at                   |entrada_solicitada_em        |
------------------------------------+-----------------------------+-----------------------------+-----------------------------+
4bf0af5d-c0ce-4bdd-9f47-8dbfa6f2bc92|2023-10-03 02:02:40.169 -0300|2023-10-03 02:02:40.169 -0300|2023-10-03 02:02:39.637 -0300|
683c6936-9572-4d60-b001-175dfd30cfc5|2023-10-03 02:02:40.158 -0300|2023-10-03 02:02:40.158 -0300|2023-10-03 02:02:39.637 -0300|
7ffeaa31-e6b5-4bce-ac60-4b28ea163d61|2023-10-03 02:02:40.189 -0300|2023-10-03 02:02:40.189 -0300|2023-10-03 02:02:39.637 -0300|
a11a7f81-648b-42d0-bf9b-66449dd1b759|2023-10-03 02:02:40.179 -0300|2023-10-03 02:02:40.179 -0300|2023-10-03 02:02:39.637 -0300|
ef775036-7461-4bce-8de7-7f21e5f79740|2023-10-03 02:02:40.165 -0300|2023-10-03 02:02:40.165 -0300|2023-10-03 02:02:39.637 -0300|
```

## Query to discover if there's a previous page

```postgres
SELECT e0."id", e0."inserted_at", e0."updated_at", e0."entrada_solicitada_em" FROM "estadias" AS e0 WHERE (((e0."entrada_solicitada_em"::timestamp = '2023-10-03 05:02:39.637908Z'::timestamp) AND (e0."id"::uuid < '4bf0af5d-c0ce-4bdd-9f47-8dbfa6f2bc92'::uuid)) OR (e0."entrada_solicitada_em"::timestamp > '2023-10-03 05:02:39.637908Z'::timestamp)) ORDER BY e0."entrada_solicitada_em", e0."id" DESC LIMIT 251;
```

## Returned rows

```text
id|inserted_at|updated_at|entrada_solicitada_em|
--+-----------+----------+---------------------+
```

## Query to discover if there's a next page

```postgres
SELECT e0."id", e0."inserted_at", e0."updated_at", e0."entrada_solicitada_em" FROM "estadias" AS e0 WHERE (((e0."entrada_solicitada_em"::timestamp = '2023-10-03 05:02:39.637908Z'::timestamp) AND (e0."id"::uuid > 'ef775036-7461-4bce-8de7-7f21e5f79740'::uuid)) OR (e0."entrada_solicitada_em"::timestamp < '2023-10-03 05:02:39.637908Z'::timestamp)) ORDER BY e0."entrada_solicitada_em" DESC, e0."id" LIMIT 251;
```

## Returned rows

```text
id                                  |inserted_at                  |updated_at                   |entrada_solicitada_em        |
------------------------------------+-----------------------------+-----------------------------+-----------------------------+
4bf0af5d-c0ce-4bdd-9f47-8dbfa6f2bc92|2023-10-03 02:02:40.169 -0300|2023-10-03 02:02:40.169 -0300|2023-10-03 02:02:39.637 -0300|
683c6936-9572-4d60-b001-175dfd30cfc5|2023-10-03 02:02:40.158 -0300|2023-10-03 02:02:40.158 -0300|2023-10-03 02:02:39.637 -0300|
7ffeaa31-e6b5-4bce-ac60-4b28ea163d61|2023-10-03 02:02:40.189 -0300|2023-10-03 02:02:40.189 -0300|2023-10-03 02:02:39.637 -0300|
a11a7f81-648b-42d0-bf9b-66449dd1b759|2023-10-03 02:02:40.179 -0300|2023-10-03 02:02:40.179 -0300|2023-10-03 02:02:39.637 -0300|
ef775036-7461-4bce-8de7-7f21e5f79740|2023-10-03 02:02:40.165 -0300|2023-10-03 02:02:40.165 -0300|2023-10-03 02:02:39.637 -0300|
```

The third query (to get the next page) should return zero rows. The problem is related to the time zone. When Ash builds the query, it casts the field (entrada_solicitada_em) to 'timestamp' and removes information about the timezone, thus, '2023-10-03 02:02:39.637 -0300' becomes '2023-10-03 02:02:39.637'. But the where clause is "entrada_solicitada_em"::timestamp < '2023-10-03 05:02:39.637908Z'::timestamp, which translates (for the first row) into '2023-10-03 02:02:39.637' < '2023-10-03 05:02:39.637908', which is true.

If I change the where clause on the third query from "entrada_solicitada_em"::timestamp < '2023-10-03 05:02:39.637908Z'::timestamp to "entrada_solicitada_em"::timestamp with time zone < '2023-10-03 05:02:39.637908Z'::timestamp with time zone, the query works fine. That's why I think the problem is related to the fact that PG is in a different time zone than UTC and the resource attirbutes too.

**Comment by zachdaniel** [comment]
Oh, sorry, just realized that you meant the actual database is not in UTC. I don't know if you can use the utc date time types in that case. The values would be different in elixir-land as they would be in the database and certain operations would effectively always be wrong. I think you need a custom type for your date time that handles the shifting at the type level.

**Comment by zachdaniel** [comment]
And honestly I’d try to avoid having the database not in UTC. It is best practice to have your database use UTC and make your application handle time zone conversion where necessary.

**Comment by tellesleandro** [comment]
Ok @zachdaniel, I'll keep investigating/testing different configurations to be sure what the problem really is. I let you know as soon as I get some conclusions. Thanks.

**Comment by zachdaniel** [comment]
Closing until we have a reproduction.
