### ISSUE TITLE
Support UUID generation for version 7

### ISSUE THREAD

**Issue by hartmeyer** [ash-project/ash#727]
Ash uses Ecto to generate new UUIDs.  These are generated by the database and limited to version 4.  Version 7 has the benefit of being ordered chronologically, which is both useful for some use cases and may improve database performance.  Consider adding a capability to generate version 7 UUIDs within Ash.

Since almost every call to UUID.generate() in Ash already uses Ash.UUID, this is a natural place to add this functionality.  A global "use v7 everywhere" setting would be sufficient to my need.

Implementation options are many but the following are good representations.
- [AshUUID](https://github.com/zoonect-oss/ash_uuid#ashuuid) (uses DB)
- [TypeID Elixir](https://github.com/sloanelybutsurely/typeid-elixir#typeid-elixir) (uses Elixir)

Alternatives:
- We tried implementing a new Ash type for Type ID (second link above).  We ran into issues when we wanted to use this as a logical UUID primary key.  Various Ash functions including important key functionality like Ash Authentication expect a `uuid_primary_key` which specifically includes Ash.UUID.generate() for defaults, so UUID version turns out to be a rather fundamental part of Ash at present.  Here is the Ash Type ID we did: [Ash Type ID](https://github.com/integralthread/ash_typeid). 

References:
- [Buildkite Goodbye to sequential integers, hello UUIDv7](https://buildkite.com/blog/goodbye-integers-hello-uuids)

**Comment by zachdaniel** [comment]
Interesting, I'm very surprised that there are things that require `uuid_primary_key` to be used. In fact, that is actually transparent to underlying extensions, all they see is an attribute with `primary_key? true, type: Ash.Type.UUID, primary_key?: true, ...etc`. Anywhere that you find yourself blocked by something requiring a uuid primary key I would consider a bug. Please open issues for those if at all possible.

I'm also surprised that `AshUUID` uses the database to generate uuids, but I haven't looked deeply into that library TBH. As for supporting it in ash core, I'm open to it. I think what we would likely do is add a constraint to `Ash.Type.UUID`, i.e `version: 7` or something along those lines, and then add those as options to `UUID.generate` as well. Then we could make the default pass those options to `UUID.generate`. The benefit of this is that you could then do this everywhere:

```elixir
uuid_primary_key :id, constraints: [version: 7]
```

Or, you could do something like this:

```elixir
defmodule MyApp.UUIDv7 do
  use Ash.Type.NewType, subtype_of: :uuid, constraints: [version: 7]
end
```

And use that everywhere, but we'd also retain backwards compatibility. That plus a config for setting the default uuid constraints, and you'd be golden. It's still not necessarily a small task, but I think implementing it that way would also allow us to default to `version: 7` for 3.0 if we wanted.

Ultimately I could imagine both the prefix options and v7 being brought from the packages you mentioned into core.

**Comment by zachdaniel** [comment]
Can't guarantee this would happen, but I think it makes sense to do for 3.0. Also would very much like to see what blocked you from using your custom uuid type. Thanks for the high quality proposal :)

**Comment by meantheory** [comment]
The custom type works with our basic tests but fails to integrate with ash_authentication. The id is passed to the custom type but calls our wrapped library directly. It isn't immediately clear to us why this happens. Large is the stack trace. This is probably a poor implementation on our part. Need to find time to dissect it more to understand how ash/ash_authentication use the type.

**Comment by jimsynz** [comment]
If there is a spot in AshAuthentication that forces the use of `uuid_primary_key` please raise an issue because I want to fix it.

**Comment by zachdaniel** [comment]
After careful consideration, I don't believe that Ash *core* should implement UUIDv7. UUIDv7 is more than just a simple unique identifier, and there is some level of conflation/complexity in combining a unique identifier with a timestamp that I'm not personally sold on. UUIDv7 can be implemented in packages, and those packages can support generating both in the data layer and in elixir.
