### ISSUE TITLE
Generated Livebook uses H1 for Resources, but Livebook warns that there should only be a single H1

### ISSUE THREAD

**Issue by arosenb2** [ash-project/ash#740]
A warning is shown after generating a Livebook from Ash APIs that says there are N Heading 1 and they should be down-converted (presumably to Heading 2).

It doesn't particularly impact functionality, but seeing easily avoidable warnings is (at least IMO) bad DX.

**Comment by fcapovilla** [comment]
I'll work on this issue.

**Comment by fcapovilla** [comment]
I've created a pull request to add a single root H1 and moved all section headings by one level.
