### ISSUE TITLE
The name of the `authorize?` option

### ISSUE THREAD

**Issue by pierrelegall** [ash-project/ash#758]
To force authorization checks in `Ash.Api.read` and more, we can set the option `authorize?` to `true`. However, the use of the verb "authorize" makes things ambiguous to me, like if `authorize?: true` will give access to data without restrictions.

Maybe the `authorize?` option could be deprecated in favor something more explicit, e.g. `apply_policies?`.

**Comment by zachdaniel** [comment]
Interesting point that I hadn't considered :) it's unlikely to change anytime soon though, as changing it would break massive amounts of code.

**Comment by pierrelegall** [comment]
Is there a way to add option aliases with Spark avoiding code breaks?

**Comment by zachdaniel** [comment]
We could add an alias, but that also increases overall complexity. I.e you'd have to know both options exist and what they do. Makes code harder to read and maintain.
