### ISSUE TITLE
Actor option ignored/overwritten.

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash#769]
It seems that when you provide the `actor` option to code interfaces or API action functions it is ignored, and only setting it with `Ash.Changeset.for_(create|read|update)` works.  Maybe not always?

See https://elixirforum.com/t/relate-actor-results-in-could-not-relate-to-actor-as-no-actor-was-found-and-allow-nil-is-false/59534/3

**Comment by zachdaniel** [comment]
I don't think this is an issue. We run changes on the creation of the changeset, so if you need an actor in your changes, you have to specify it when making the changeset. Specifying it after when calling the action won't retroactively be able to provide the actor to already run changes.
