### ISSUE TITLE
Calculation involving a relationship cannot be called from another deeply nested resource.

### ISSUE THREAD

**Issue by puruzio** [ash-project/ash#771]
**Describe the bug**
As a background, my resource relationship structure is as follows:
Task
 has_many Keydate
 belongs_to Assigned_by

Keydate
 has_many TaskInstance
-------------------------------
An error occurs running this statement.
```elixir
TaskInstance
|> Ash.Query.for_read(:read)
|> Ash.Query.filter(exists(keydate.task, test_calculation_relationship(user_id: current_user.id)))
|> Tasks.read(actor: current_user)
```
---------------------------------------
The error message is
** (KeyError) key :destination not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (ash_postgres 1.3.52) lib/expr.ex:1080: AshPostgres.Expr.do_dynamic_expr/5
    (ash_postgres 1.3.52) lib/expr.ex:1004: anonymous fn/6 in AshPostgres.Expr.do_dynamic_expr/5
    (ecto 3.10.3) lib/ecto/query/builder/dynamic.ex:76: Ecto.Query.Builder.Dynamic.expand/3
    (stdlib 5.0.2) lists.erl:1706: :lists.mapfoldl_1/3
    (elixir 1.15.5) lib/macro.ex:653: Macro.do_traverse/4
    (ecto 3.10.3) lib/ecto/query/builder/dynamic.ex:46: Ecto.Query.Builder.Dynamic.fully_expand/2
    (ecto 3.10.3) lib/ecto/query/builder/filter.ex:133: Ecto.Query.Builder.Filter.filter!/7
    (elixir 1.15.5) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash_postgres 1.3.52) lib/data_layer.ex:2372: AshPostgres.DataLayer.filter/4
    (ash_postgres 1.3.52) lib/expr.ex:1131: AshPostgres.Expr.do_dynamic_expr/5
    (ash_postgres 1.3.52) lib/data_layer.ex:2446: anonymous fn/2 in AshPostgres.DataLayer.add_filter_expression/2
    (elixir 1.15.5) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash_postgres 1.3.52) lib/data_layer.ex:2372: AshPostgres.DataLayer.filter/4
    (ash 2.15.1) lib/ash/actions/read.ex:1393: anonymous fn/4 in Ash.Actions.Read.data_field/3
    (ash 2.15.1) lib/ash/engine/engine.ex:537: anonymous fn/2 in Ash.Engine.run_iteration/1
    (ash 2.15.1) lib/ash/engine/engine.ex:558: anonymous fn/4 in Ash.Engine.async/2
    (elixir 1.15.5) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.5) lib/task/supervised.ex:36: Task.Supervised.reply/4
    (ash 2.15.1) lib/ash/engine/engine.ex:552: Ash.Engine.async/2

------------------------------------------
No error occurs with these statements.

```elixir
Task
|> Ash.Query.for_read(:read)
|> Ash.Query.filter(test_calculation_relationship(user_id: current_user.id))
|> Tasks.read(actor: current_user)
```

or

```elixir
Keydate
|> Ash.Query.for_read(:read)
|> Ash.Query.filter(exists(task, test_calculation_relationship(user_id: current_user.id)))
|> Tasks.read(actor: current_user)
```

or even

```elixir
TaskInstance
|> Ash.Query.for_read(:read)
|> Ash.Query.filter(**keydate.exists**(task, test_calculation_relationship(user_id: current_user.id)))
|> Tasks.read(actor: current_user)
```
----------------------------------------------------
test_calculation_relationship is defined as follows:
The error occurs with any relationship used in `exists(relationship,...`

```elixir
    calculate :test_calculation_relationship,
              :boolean,
              expr(exists(assigned_by, id == ^arg(:user_id))) do
      argument :user_id, :uuid do
        allow_nil? false
      end
    end
```
------------------------------
The error disappears if the calculation does not use a relationship. For example, this works just fine.

```elixir
    calculate :test_calculation_relationship,
              :boolean,
              expr(assigned_by_id == ^arg(:user_id))) do
      argument :user_id, :uuid do
        allow_nil? false
      end
    end
```

----------------------------
**To Reproduce**
See above.

**Expected behavior**
(exists(**keydate.task**, test_calculation_relationship(user_id: current_user.id))) should work.

**Runtime**
 - Elixir version 1.15.5
 - Erlang version 26
 - OS Windows 11
 - Ash version
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Having some trouble reproducing this. Would it be possible to add a failing test? It will be very easy for me to address it with something I can run to reproduce.

**Comment by puruzio** [comment]
Thanks for looking into this. Let me try to put it together and post here.

**Comment by lifeofdan** [comment]
I think I am running into a related issue. I am trying to use an actor from a calculation and then use that calculation in an aggregate on another resource. I have created a test to showcase this issue. https://github.com/lifeofdan/ash

**Comment by zachdaniel** [comment]
@lifeofdan yeah, that should work, but it is a separate issue. Can you open a new issue for that and make a PR with the failing test as well? I'll investigate.

**Comment by lifeofdan** [comment]
Absolutely, tyvm.

**Comment by zachdaniel** [comment]
I believe this has been sorted. We can reopen if not.
