### ISSUE TITLE
Strange interaction between `expr_sort` that uses `parent` and `on_lookup` in a `many_to_many` relationship

### ISSUE THREAD

**Issue by rbino** [ash-project/ash#780]
**Describe the bug**
It seems that adding a sort expression referencing the parent in a `many_to_many` relationship, like
```elixir
sort [Ash.Sort.expr_sort(parent(post_tags.position))]
```
messes with the `on_lookup` behaviour of `manage_relationship`.

**To Reproduce**
I've opened a [PR](https://github.com/ash-project/ash_postgres/pull/183) with a set of resources and a minimal failing test that reproduces this.

**Expected behavior**
I expect to be able to normally manage the relationship with `manage_relationship` even when using `expr_sort` in it.

**Runtime**
 - Elixir version: 1.15.4
 - Erlang version: 26.0.2
 - OS: Debian Trixie
 - Ash version: 2.17.3
 - any related extension versions: Ash Postgres 1.3.62

**Comment by zachdaniel** [comment]
Fixed in `main`.

**Comment by rbino** [comment]
Can confirm it's now working, thanks!
