### ISSUE TITLE
Ash runtime error on action argument of own type

### ISSUE THREAD

**Issue by mrdotb** [ash-project/ash#782]
**Describe the bug**
It seems not possible to pass an argument of own type in action.

**To Reproduce**
I made a [livebook]( https://gist.github.com/mrdotb/7dfa85edb84dd3512f6cff938593ef2e) the second section trigger the runetime error
```
** (RuntimeError) {:array, User} is not a valid type.

Valid types include any custom types, or the following short codes (alongside the types they map to):
...
```

**Expected behavior**
It's possible to pass other module so I expected this to work.

**Comment by zachdaniel** [comment]
This is unfortunately not something we can overcome at the moment...but I can add a warning that will explain the issue, at a minimum.

**Comment by zachdaniel** [comment]
Actually, I think I can solve it :)

**Comment by zachdaniel** [comment]
So, I've actually made this behavior *forbidden*. The error will explain what you should do instead :)
