### ISSUE TITLE
Configure CI pipeline (and testing) for Ash 3.0

### ISSUE THREAD

**Issue by ghalestrilo** [ash-project/ash#809]
**Is your feature request related to a problem? Please describe.**
The current Ash pipeline is unable to run tests for Ash 3, which makes it harder to guarantee correctness for the new release.

**Describe the solution you'd like**
A simple (and somewhat naive) solution is to duplicate the entire pipeline (`ash-ci.yml`) into a new file.

Reasoning: Tests for 3.0.0 require the environment variable `FLAG_ASH_THREE` to be set to `true` at compile-time. Hence, any test action for Ash 3 requires its own preceding build action under the same flag. Setting that flag will break some Ash 2 tests, so they have to be run as separate actions.

**Describe alternatives you've considered**
I considered creating new stages within the same workflow (`ash-ci.yml`). The constraints above require duplicating almost everything, so it seemed worth exploring the described approach as an MVP.

**Comment by zachdaniel** [comment]
I've added it to the matrix of the CI run so it should now be included in CI 👍
