### ISSUE TITLE
The `:on_match` clause leads to unexpected behavior when modifying the join table for many_to_many relationships

### ISSUE THREAD

**Issue by ibarakaiev** [ash-project/ash#814]
**Describe the bug**
It appears that `on_match` for many-to-many relationship doesn't execute the action on a join table when provided, and `:on_match` gets executed even if a destination record doesn't exist in the relationship yet.

**To reproduce**
Reproducible repo: https://github.com/ibarakaiev/ash-many-to-many-manage-relationship-example. The test there is setup to throw an error since quantity is expected to be 2 but the functionality is not yet implemented. However, the debug statements are shown, and it is easy to see the below unexpected behavior.

The setup is as follows: there are two main schemas, `Cart` and `Product`, as well as a many-to-many relationship between them through `CartItem` with `:quantity`. I want to have an update action on `Cart`, named `:add_to_cart`, that would either a) add a `cart_item` with a given cart and product with quantity 1 or b) increment the quantity on an existing relevant `cart_item`. In other words, running the following must end up with a `cart_item` with quantity 2:

```elixir
cart = Cart.create!()
product = Product.create!(%{sku: "example"})

cart |> Ash.Changeset.for_update(:add_to_cart, product: product) |> Orders.update!()
cart |> Ash.Changeset.for_update(:add_to_cart, product: product) |> Orders.update!()
```

I tried adding the following update action to `Cart`:

```elixir
update :add_to_cart do
  description "Adds a product to cart or increments its quantity by 1"

  argument :product, :map, allow_nil?: false

  # - `:on_lookup` checks if the record (product) already exists using the
  # `:read` action on the product and adds a join table row for it using the
  # `create` action on the join table unless this row already exists
  # - `:on_no_match` is invoked when no product exists, in which case `add_to_cart`
  # should fail
  # - `:on_match` checks if the record already exists in the relationship (i.e.
  # if a join row already exists for the product) and, if so, increments its quantity by 1
  # - `:on_missing` checks for records that exist in the join table but not in the input
  change manage_relationship(:product, :products,
            on_lookup: {:relate_and_update, :create, :read, :all},
            on_no_match: :error,
            on_match: {:update, :update_in_cart, :increment_quantity, []},
            on_missing: :ignore,
            use_identities: [:unique_sku]
          )
end
```

`:update_in_cart` is supposed to be a dummy action on `Product` since Ash doesn't have an option to only modify the join table via `:on_match` yet:

```elixir
update :update_in_cart do
  accept []

  change &debug/2
end
```

where `debug/2` is the following just to see when it gets executed:

```elixir
defp debug(changeset, _) do
  Ash.Changeset.before_action(changeset, fn changeset ->
    dbg(changeset)
  end)
end
```

Similarly, `:increment_quantity` is an update action on the `CartItem` join table, currently also just printing a `dbg` statement:

```elixir
update :increment_quantity do
  change &increment_quantity/2
end
```

```elixir
defp increment_quantity(changeset, _) do
  Ash.Changeset.before_action(changeset, fn changeset ->
    dbg(changeset)
  end)
end
```

**Expected behavior**
With the above setup, I expect the following to happen:

1. On the first `cart |> Ash.Changeset.for_update(:add_to_cart, product: product) |> Orders.update!()` call, the `:on_lookup` clause should get executed and nothing else.
2. On the second identical call, the `:on_match` clause should get executed and nothing else. There `:increment_quantity` should be called as well as `:update_in_cart`.

What I'm seeing instead is that, on both calls, `:update_in_cart` action gets called and `:increment_quantity` never gets called.

**Runtime**
 - Elixir version: 1.15.2
 - Erlang version: 26.0.2
 - OS: MacOS 14.2
 - Ash version: 2.17.11
 - Ash postgres: 1.3.64

**Comment by zachdaniel** [comment]
So, I just happened along the fix, I believe. I haven't tested it with your reproduction. Can you try latest `main` out and let me know? Please reopen the issue if it persists.

**Comment by ibarakaiev** [comment]
So `:increment_quantity` gets called now, so that got sorted out — thanks for fixing it! I do see though that `:increment_quantity` got called both when adding it for the first time and the second time; similarly, `:update_in_cart` got invoked both times. My understanding is that the first time only `:on_lookup` would get called, and second time only `:on_match` would get called, is that incorrect?

**Comment by zachdaniel** [comment]
I think the issue there is `            on_lookup: {:relate_and_update, :create, :read, :all}`

`:relate_and_update` will call the update described in the `on_match` action. You want just `on_lookup: {:relate, ...`
