### ISSUE TITLE
Support for `sensitive` in calculations/aggregates/relationships

### ISSUE THREAD

**Issue by vonagam** [ash-project/ash#825]
Right now only attributes have `sensitive?` modifier. Other types of fields do not have such option.

Since calculations/aggregates can work on sensitive attributes and some relationships add their own attributes it makes sense to support sensitivity for them too.

**Comment by zachdaniel** [comment]
I've done everything except relationships. In that case folks can define the attribute manually and use `define_attribute? false`.

**Comment by zachdaniel** [comment]
(this change has been made in 3.0)
