### ISSUE TITLE
Allow turning off the tenant option in identity

### ISSUE THREAD

**Issue by nallwhy** [ash-project/ash#831]
**Is your feature request related to a problem? Please describe.**

 I want to support global uniqueness even for identities within a tenancy.

**Describe the solution you'd like**

Allow turning off the tenant option in identity

**Describe alternatives you've considered**

- 

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

```elixir
  identities do
    identity :unique_in_global, [:field0, :field1], tenant?: false
  end
```

**Additional context**

-

**Comment by zachdaniel** [comment]
👍 This should be relatively simple, but the main change that needs to happen here is in `ash_postgres`. There is a bit where we decide if it needs to be unique across the tenant, and we'll need to add this check there. Adding the DSL should also be simple. I won't have time to do this soon, but PRs welcome!

**Comment by zachdaniel** [comment]
I've added the option `all_tenants?` to `ash` `main`. I will need to adjust the migration generator in ash_postgres to use it next.

**Comment by zachdaniel** [comment]
This is completed as of the most recent release of ash and ash_postgres

**Comment by nallwhy** [comment]
Thanks a lot!
