### ISSUE TITLE
Error messages no longer shown on authentication failure

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#837]
**Describe the bug**

Okay so while this is authentication-related, I think the issue may come from somewhere in Ash itself, because it does NOT occur in Ash 2.18.2 but DOES occur on commit c48cb08026cf56b1ac33209203bc9c00061b40b8 (the commit of the big read refactor). 

Maybe AshAuthentication was relying on some quirk of the old behaviour, though?

**To Reproduce**

I have AshAuthentication and AshAuthenticationPhoenix set up in my app, with a standard setup.

When an invalid username/password is entered on the sign-in form, no error message is displayed - the submit button changes while the submission is processing then it clears. See video:

https://github.com/ash-project/ash/assets/543859/0335a5f9-fd16-4d9e-91a0-47e44bede316

**Expected behavior**

When an invalid username/password is entered on the sign-in form, an error message should display.

<img width="426" alt="Screenshot 2024-01-21 at 4 30 17 pm" src="https://github.com/ash-project/ash/assets/543859/4f830b09-f443-4719-a2f9-da415467d8c5">

**Runtime**
 - Elixir version 1.15.7-otp-26
 - Erlang version 26.1.2
 - OS 
 - Ash version main, commit c48cb08026cf56b1ac33209203bc9c00061b40b8
 - AshAuthentication 3.12.0, AshAuthenticationPhoenix 1.9.0

**Comment by zachdaniel** [comment]
Thanks for the heads up!
