### ISSUE TITLE
Game crash after 1 hour

### ISSUE THREAD

**Issue by furyyyyyyyyyyyy** [ash-project/ash#840]
After entering in any server everything goes smooth for 1 hour after that my packetloss goes high then it kicks me out of the game. Need Help!!

![image](https://github.com/ash-project/ash/assets/157386986/fb6572e5-cf92-4b88-904c-da0f2d551fd3)

![image](https://github.com/ash-project/ash/assets/157386986/cc9d5b15-90eb-4e42-9610-2238a6164991)
 
![image](https://github.com/ash-project/ash/assets/157386986/4e73f8b4-a3e5-44b6-9356-240bfc329d2c)

**Comment by zachdaniel** [comment]
Hello! I'm
Not sure what you're looking for, but this project isn't the place. This is Ash Framework, a tool for building applications with the Elixir programming language. I assume you're looking for a game called Ash? Or something along those lines? Good luck fixing your issue!
