### ISSUE TITLE
Filter a map attribute using user input

### ISSUE THREAD

**Issue by lardcanoe** [ash-project/ash#862]
Source: https://elixirforum.com/t/ash-resource-filtering-embedded-map-with-user-input/61359

Maybe this is a feature request?

`Ash.Filter.parse_input(resource, statement)` does not support fields of a `:map` attribute (that has no embedded resource type).

Given:

```
    attribute :data, :map do
      default %{}
      allow_nil? false
    end
```

Parsing a filter statement:

```
    statement = %{
      person: %{parent: %{name: "Daniels"}},
      data: %{size: "Big"}
    }

    # This will blow up with the above
    {:ok, filter} = Ash.Filter.parse_input(resource, statement)

    %Ash.Error.Query.NoSuchFilterPredicate{message: nil, value: nil, key: "size", resource: MyApp.MyResource, changeset: nil, query: nil, error_context: [], vars: [], path: [], stacktrace: #Stacktrace<>, class: :invalid}

```

From Zach:

> I think this is actually something missing from Ash.Filter, specifically when given a nested map like that we should check for embedded resources and allow you to apply that kind of filter. Could you open an issue for it in Ash?

As always, thank you for helping out! Just trying to push Ash to its limits and beyond :-)

**Comment by lardcanoe** [comment]
Sorry, turns out what you did only works if there is an embedded resource defined.

Your new code worked because the attribute in the test resource is defined as 

`attribute :embedded_bio, EmbeddedBio`

and not

`attribute :embedded_bio, :map`

**Comment by zachdaniel** [comment]
This is now supported with an `at_path: [...list]` key that can be used along with a predicate. For example:

```elixir
    statement = %{
      person: %{parent: %{name: "Daniels"}},
      data: %{at_path: ["size"], eq: "Big"}
    }
```
