### ISSUE TITLE
`:*` vs `:all`

### ISSUE THREAD

**Issue by vonagam** [ash-project/ash#878]
`:*` and `:all` are used in different places to mean the same thing.

Does it not make sense to pick one and use only it?

Note: Those two lines ([1](https://github.com/ash-project/ash/blob/0229a894abb9daf6cc18985c51590ecefb5ceabd/lib/ash/filter/filter.ex#L988) and [2](https://github.com/ash-project/ash/blob/0229a894abb9daf6cc18985c51590ecefb5ceabd/lib/ash/filter/filter.ex#L1010)) close to each other feel like a bug but because of inconsistency, I am not 100% sure.

**Comment by zachdaniel** [comment]
It's not a bug in that case, but it's definitely silly. I'll make the change in the 3.0 branch when it gets cut.

**Comment by zachdaniel** [comment]
This has been completed in the 3.0 branch

**Comment by vonagam** [comment]
What about [join keys](https://github.com/ash-project/ash/blob/a24e1d9bdfe774d71b40b99cdbbf4a70fd4783d2/lib/ash/actions/managed_relationships.ex#L1454) in `manage_relationship`? It supports passing `:all` instead of a list. Maybe it makes sense to convert it to `:*` also.

**Comment by vonagam** [comment]
But I still [see it](https://github.com/ash-project/ash/blob/00cf4bac217b6dca0cb1acad990c58f82ffb7c77/lib/ash/actions/managed_relationships.ex#L1499) on `3.0` branch.

**Comment by zachdaniel** [comment]
oh, then I must have missed it. Will reopen this and fix.

**Comment by zachdaniel** [comment]
I could have sworn I made that change

**Comment by zachdaniel** [comment]
Fixed :) We still use `:all` in certain places, but any time we are referring to a list of fields, `:*` is how we prefer to mean "all fields".
