### ISSUE TITLE
Hook after_transaction does not run after failure

### ISSUE THREAD

**Issue by carlgleisner** [ash-project/ash#880]
**Describe the bug**
The `after_transaction` hook does not run in the event of failure despite that it should run on success as well as failure according to [the documentation](https://hexdocs.pm/ash/Ash.Changeset.html#after_transaction/3):

> after_transaction hooks differ from after_action hooks in that they are run on success and failure of the action or some previous hook.

**To Reproduce**
This is not minimal perhaps, sorry.

```elixir
changes do
  change after_transaction(fn
            changeset, {:ok, result} ->
              IO.inspect("Got {:ok, result}", label: "after_transaction")
              {:ok, result}

            changeset, {:error, error} ->
              message = Exception.message(error)
              IO.inspect(message, label: "after_transaction")

              changeset.data
              |> Ash.Changeset.for_update(:error, %{
                error: message,
                error_state: changeset.data.state
              })
              |> Statepoc.Support.update()
          end),
          on: [:update]
end
```

In this case an illegal state change using some of the `update` actions, which causes the action to fail, will not trigger the inspection `IO.inspect(message, label: "after_transaction")`.

**Expected behavior**
That the `after_transaction` hook would run and execute `IO.inspect(message, label: "after_transaction")` in this case.

See this [reference repo](https://github.com/carlgleisner/statepoc).

**Runtime**
 - Elixir 1.16.0 (compiled with Erlang/OTP 26)
 - Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
 - Darwin [hostname redacted] 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103 arm64
 - Ash 2.18.2

**Additional context**
The [assessment](https://elixirforum.com/t/ashadmin-and-catching-illegal-state-transitions-with-after-transaction/61576/2?u=carlgleisner) by @zachdaniel on the forums:

> The reason that the after_action isn’t getting triggered is actually because, in a way, the action is never really being called. We’re returning early from the action with the invalid changeset. However, this to me looks like a bug since after_transaction hooks are meant to be run on both success and failure. What this means is that we need to address our create/update/destroy code that is returning early for changesets w/ errors to properly invoke the after_transaction hook.

**Comment by zachdaniel** [comment]
Thanks for the report! This is fixed in `main`. A release should be cut this week.
