### ISSUE TITLE
Custom delimiter for Pubsub topics

### ISSUE THREAD

**Issue by dimakula** [ash-project/ash#881]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the pubsub extension with RabbitMQ, specifically with topic exchanges. One limitation with the current approach is that `:` is used as a default delimiter for routing keys, which doesn't work with wildcard matching, which requires dots for separators (.e.g. `users.*.created` or `#.created`).

**Describe the solution you'd like**

The ability to pass in a `delimiter` option into the `pubsub` extension.

**Describe alternatives you've considered**

Nothing comes to mind other than writing a custom extension.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

```
  pub_sub do
    prefix "users"
    delimiter "." # New delimiter option

    publish :create, [:id, "created"]
  end
```

**Comment by jimsynz** [comment]
This seems fairly straightforward;

1. Add a `delimeter` option to the [`pub_sub` DSL section](https://github.com/ash-project/ash/blob/main/lib/ash/notifier/pub_sub/pub_sub.ex#L38-L85)
2. Use this option to replace the hard coded colons on [L130](https://github.com/ash-project/ash/blob/main/lib/ash/notifier/pub_sub/pub_sub.ex#L130) and [L197](https://github.com/ash-project/ash/blob/main/lib/ash/notifier/pub_sub/pub_sub.ex#L197)

**Comment by dimakula** [comment]
Yep, I'm about to open up a PR for it momentarily :slightly_smiling_face:
