### ISSUE TITLE
Array of embedded resources are updated in the reverse order

### ISSUE THREAD

**Issue by sezaru** [ash-project/ash#883]
**Describe the bug**
I have a resource that has an array of embedded resources.

When I create them, the order of the array is kept as-is, when I update the resource, the array is reversed.

I found that the bug was introduced in one of these 3 commits:

e5d78ae0742d080de4110df9dc6bed97c8db02b4
23107d061cbbad9c2a7739f7275bb1552c306e8d
3db822d7757677090239b2fa80da38fef5744726

**To Reproduce**
Have a resource that contains an attribute that is an array of embedded resources.

After creating the resource, try to update it, and the array order will change.

**Expected behavior**
The array order should be kept as-is

**Runtime**
 - Elixir version 1.16.0
 - Erlang version 26.2.1
 - OS Fedora Silverblue 39
 - Ash version master

**Comment by sezaru** [comment]
I just tested with commit fe0058ce9836ce35709f6b44c9c5fe44860ad1df but it still reverting the array order

**Comment by zachdaniel** [comment]
Okay, thanks for letting me know. If you have a chance to make a test reproducing the issue that would be excellent. I will look in the morning.

**Comment by drikanius** [comment]
Just to add here.

I just created this silly test using the master

```elixir
defmodule Ash.Test.Resource.ArrayTest do
  @moduledoc false

  use ExUnit.Case, async: true

  defmodule Element do
    use Ash.Resource, data_layer: :embedded

    attributes do
      attribute :element, :string
    end
  end

  defmodule Array do
    use Ash.Resource, data_layer: Ash.DataLayer.Ets

    attributes do
      uuid_primary_key :id
      attribute :elements, {:array, Element}, default: []
    end

    actions do
      defaults [:create, :read, :update, :destroy]
    end
  end

  defmodule Registry do
    @moduledoc false
    use Ash.Registry

    entries do
      entry(Array)
    end
  end

  defmodule Api do
    @moduledoc false
    use Ash.Api

    resources do
      registry Registry
    end
  end

  @tag :wip
  test "it returns the embedded array created as original order" do
    original = [%{element: "a"}, %{element: "b"}, %{element: "c"}, %{element: "d"}]

    {:ok, created_array} =
      Array
      |> Ash.Changeset.new(%{
        elements: original
      })
      |> Api.create()

    created_array = Enum.map(created_array.elements, & &1.element)
    original = Enum.map(original, & &1.element)

    assert original == created_array
  end
end
```

and its failed like:

```elixir
1) test it returns the embedded array created as original order (Ash.Test.Resource.ArrayTest)
     test/resource/array_test.exs:46
     Assertion with == failed
     code:  assert original == created_array
     left:  ["a", "b", "c", "d"]
     right: ["d", "c", "b", "a"]
     stacktrace:
       test/resource/array_test.exs:59: (test)
```
