### ISSUE TITLE
previous_values in pubsub.ex is missing `?` character

### ISSUE THREAD

**Issue by sezaru** [ash-project/ash#884]
**Describe the bug**
Basically in file https://github.com/ash-project/ash/blame/8910e038a57718aaaeec238a1b1065cb78cb4321/lib/ash/notifier/pub_sub/pub_sub.ex#L127C14-L127C14

The line is missing the character `?` in the `previous_values` variable.

**Comment by zachdaniel** [comment]
🙇 thank you
