### ISSUE TITLE
Bug when passing the wrong types of resources to code interface functions

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#909]
**Describe the bug**

Like I'm clearly doing the wrong thing in my code, but Ash is silently behaving unexpectedly and "working".

I have two resources, eg. `Appointment` and `Delivery`. Both define an update action called `reassign` and a code interface of the same name.

If I inadvertently pass the wrong type of resource to a `reassign` function, it doesn't raise an error:

```elixir
iex> Appointment.reassign(delivery, [other args])
# some SQL that clearly comes from the `Delivery.reassign` function
{:ok, #Delivery<stuff>}
```

Rather, it just calls the action on the *other* resource. 

If I rename the action/code interface on the Delivery resource, it then returns an error:

```elixir
iex> Appointment.reassign(delivery, [other args])
** (ArgumentError) No such update action on resource Delivery: :reassign
```

So it's not even attempting to call the action as defined on `Appointment`.

**Expected behavior**

An error if I pass a non-Appointment resource as the first argument into `Appointment.reassign`.

**Runtime**

 - Elixir version 1.15.6-otp-26
 - Erlang version 26.1
 - OS macOS somethingorotherthelatestversion
 - Ash version main at sha f324e7385bffddf43034e606dd96e37b01ee77f5

**Additional context**

Notes from Slack:

> The code interface passes the thing that you give it into `Ash.Changeset.for_update(….)`
>
> and that would happen to work if you gave it a record for the wrong resource that has a matching action name
>
> We should have an up front validation in the code interface code for updates/destroys that says that if you gave it a record, it matches the resource the interface is defined on.

**Comment by zachdaniel** [comment]
fixed in 3.0 :)
