### ISSUE TITLE
Order in tuple for calculation in query sort

### ISSUE THREAD

**Issue by vonagam** [ash-project/ash#919]
A calculation can be used in a query in multiple places - `load`, `filter`, `sort`, `distinct` and `distinct_sort`. If there is a need to pass both calculation arguments and a nested statement then a tuple is used. For `load` and `filter` arguments are provided in the first element of such tuple, while `sort` expects it in the second. 

(Note: `distinct` and `distinct_sort` use the logic from `sort` but for `distinct` there is need for a nested statement so it is not really relevant. I do not see tests for `distinct_sort` with arguments, need to check if it works properly.)

The proposal is to make order of elements in those tuples consistent. Personally, I would prefer for arguments to go first and the nested stuff to be second like in `load` and `filter`.

It is a breaking change (not big though). Maybe it makes sense to do it with Ash 3 release?

**Comment by zachdaniel** [comment]
Yeah, I think this would make sense. I'll look at the design and see what we can do for 3.0.

**Comment by zachdaniel** [comment]
This has been completed in 3.0
