### ISSUE TITLE
Integer, Float, Decimal constraints: :greater_than, :less_than

### ISSUE THREAD

**Issue by rapidfsub** [ash-project/ash#933]
**Is your feature request related to a problem? Please describe.**
I need positive integer, float, decimal type.
Therefore, I need contraints "greater_than" and "less_than".

**Describe the solution you'd like**
```elixir
defmodule PositiveDecimal do
  use Ash.Type.NewType, subtype_of: :decimal, constraints: [greater_than: 0]
end
```

**Describe alternatives you've considered**
I can do this by validation now, but it is not reusable.

**Comment by vonagam** [comment]
All of listed types have `min` and `max` constraints. Hope that helps.

**Comment by rapidfsub** [comment]
@vonagam 
yeah. that's enough for integer, but not enough for decimal and float.
with min, max constraints, you can make non_negative_decimal, but can't make positive_decimal.

**Comment by rapidfsub** [comment]
ok. i'll do it.
