### ISSUE TITLE
A new built-in change function - `touch_related`

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#941]
**Is your feature request related to a problem? Please describe.**

I'd love a way of updating a parent record when a child record is created/updated, similar to `belongs_to :parent, touch: true` in Rails (if you're familiar with it).

My use case is with music, with albums and artists - I want the `updated_at` for the artist to be able to reflect the last time an artist or any of its albums were modified.

I realize it could probably be done with a calculation but it would get nasty, especially if there were multiple layers of nesting (and then if you wanted to sort based on it, which I definitely do)

**Describe the solution you'd like**

A new change function so I can write (for example)

```elixir
relationships do 
  belongs_to :artist, MyApp.Music.Artist
end

actions do 
  create :create do 
    change touch_related(:artist)
  end
end
```

I tried implementing it myself, but ran into no end of problems :(

### Notes

* It would only work for `belongs_to` relationships (or maybe many-many as well??) 
* It would have be to smart enough to read the right field name from the touched resource (ie. not hardcoded `updated_at`)
* Could it cascade? ie. if editing a single Track, that belongs to an Album, that belongs to an Artist - updating a Track updates `updated_at` on the Artist?

**Comment by zachdaniel** [comment]
This makes sense to me. We can use bulk actions in the change as well to ensure we don't get an N+1 issue (instead just N = relationship depth). I think it can work for any arbitrary relationships. The thing that is most concerning to me is that to do this in a way that isn't hacky, is that we need to have an action to cal. I think probably the best way to do this would be to require that a `touch` action exists on the target resource, who's job is to accept no attributes and only touch whatever fields should happen upon being touched.

**Comment by zachdaniel** [comment]
And at that point the action can be called whatever they want, but can default to touch. `change touch(:relationship, action: :action), on: [:update, :destroy]`

**Comment by zachdaniel** [comment]
This can be implemented now with the builtin `cascade_update` change.
