### ISSUE TITLE
Ash 3.0 compatible packages

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash#943]
# Core Packages

- [x] ash_postgres
- [x] ash_phoenix
- [x] ash_graphql
- [x] ash_authentication
- [x] ash_authentication_phoenix
- [x] ash_archival
- [x] ash_json_api
- [x] ash_admin
- [x] ash_state_machine
- [x] ash_appsignal (no changes needed)
- [x] ash_oban
- [x] ash_money (no changes needed)
- [x] ash_double_entry
- [x] ash_paper_trail
- [x] smokestack
- [x] ash_sqlite
- [x] ash_csv
- [x]  ash_cubdb

# Known Community Packages

- [ ] [ash_geo](https://github.com/bcksl/ash_geo)
- [x] [ash_uuid](https://github.com/zoonect-oss/ash_uuid)
- [ ] [ash_query_builder](https://github.com/sezaru/ash_query_builder)
- [x] [ash_rbac](https://github.com/traveltechdeluxe/ash-rbac)
- [x] [ash_pyro](https://github.com/frankdugan3/pyro) (main)
- [x] [ash_pyro_components](https://github.com/frankdugan3/pyro) (main)
- [x] [ash_jason](https://github.com/vonagam/ash_jason)
- [ ] [ash_thrift](https://github.com/arisechurch/ash_thrift)
- [x] [ash_ulid](https://github.com/vonagam/ash_ulid)

If your package is here, please let me know if/when its been updated.

# Example Projects

- [x] [AshHq](https://github.com/ash-project/ash_hq)
- [x] [Realworld](https://github.com/team-alembic/realworld)

**Comment by jimsynz** [comment]
Smokestack has a 3.0 support [PR ready and waiting](https://harton.dev/james/smokestack/pulls/42)

**Comment by jimsynz** [comment]
Ash Authentication has a mostly-working [WIP PR](https://github.com/team-alembic/ash_authentication/pull/599)

**Comment by frankdugan3** [comment]
`ash_pyro` has 3.0 support on `main` branch, and `ash_pyro_components` is WIP.

**Comment by moissela** [comment]
`ash_uuid` 3.0 support ready on [v0.8.0-rc.1](https://hex.pm/packages/ash_uuid/0.8.0-rc.1)

I've noticed that `splode` requires elixir `~> 1.16`, but `ash` v3 which has `splode` as a dependency, only requires `elixir ~> 1.11`.

Should `ash`'s minimum elixir requirement be updated?

**Comment by zachdaniel** [comment]
Actually, splodes version requirement should probably be lowered

**Comment by frankdugan3** [comment]
`ash_pyro_components` has 3.0 support on `main` branch.

Will probably wait on Pyro releases at least until all the core Ash libs have stable 3.0 release.

**Comment by dolfinus** [comment]
Some extensions are still mentioned in Ash [Readme](https://github.com/ash-project/ash/tree/v3.0.0-rc.10?tab=readme-ov-file#extensions-10) as "<1.0", like ash_graphql, ash_json_api. ash_paper_trail is mentioned as "unreleased"

**Comment by zachdaniel** [comment]
Will fix now :)

**Comment by zachdaniel** [comment]
Actually, I'm going to remove that extensions list, because I'm working on a new one as part of the documentation overhaul :)

**Comment by frankdugan3** [comment]
What about `ash_gen_server`, or is that abandoned? I was actually just about to give it a spin. :thinking:

**Comment by zachdaniel** [comment]
Great question! It wasn't ever published on hex AFAIK. I wouldn't say it's abandoned, but it does need to be updated. It should be a relatively simple update though. @jimsynz might have some time to take a stab at it?

**Comment by jimsynz** [comment]
Well it was used for a single internal project which is now archived - and I used it as my way to learn about Ash. Probably should just be archived unless folks actually want it to be a thing.

**Comment by zachdaniel** [comment]
I think it's salvageable :) I'll have a look when I get a chance.

**Comment by vonagam** [comment]
Updated my packages with Ash 3 support - `ash_jason`, `ash_ulid` and `ash_sqids`.

Also `realword` can be marked as done too.

**Comment by moissela** [comment]
Just released `ash_uuid` [v1.0.0](https://hex.pm/packages/ash_uuid/1.0.0) with Ash 3 support 💪🏼
