### ISSUE TITLE
"Updated at" timestamp not updated during atomic update

### ISSUE THREAD

**Issue by m0rt3nlund** [ash-project/ash#949]
**Describe the bug**
The "Updated at" timestamp seems to not get updated during atomic update

**To Reproduce**
```
defmodule Shared.Ash.Support.CRM.Agent do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer

  attributes do
    uuid_primary_key :id do
      generated? true
      default nil
    end

    attribute :status, :string do
      default "idle"
    end

    update_timestamp :updated_at
    create_timestamp :inserted_at
  end
end

Shared.Ash.Support.CRM.Agent
|> Shared.Ash.Support.read_one!()
|> Ash.Changeset.for_update(:update, %{status: status})
|> Shared.Ash.Support.update()
```

**Expected behavior**
Expect the `updated_at` timestamp to update

**Runtime**
 - Elixir version: 1.16
 - Erlang version: OTP 26
 - OS: Windows
 - Ash version: 2.20.2
 - any related extension versions

**Comment by zachdaniel** [comment]
Fixed in latest `main` (and back ported to 2.0)
