### ISSUE TITLE
Ash 3.0 Upgrade guide: make move to domain more prominent

### ISSUE THREAD

**Issue by dmitriid** [ash-project/ash#970]
**Describe the bug**

[The announcement](https://hexdocs.pm/ash/3.0.0-rc.7/upgrade.html) says:

> It is very important that you read and follow the [upgrade guide](https://hexdocs.pm/ash/3.0.0-rc.7/upgrade.html)

However, the instruction to remove `Registry` and move everything into domain comes much earlier than the description of the `Api->Domain` change.

People who might not have followed the development of 3.0 will probably be confused. I know I was, and I knew about this :)

**Proposed solution**

Move the section `Ash.Api is now Ash.Domain`, and just this section before `DSL Changes`

**Comment by zachdaniel** [comment]
Good call. Would you want to PR this change?

**Comment by dmitriid** [comment]
@zachdaniel I forgot I could do that :) Opened #971
