### ISSUE TITLE
Ash.Type.Enum does not allow String values any more

### ISSUE THREAD

**Issue by barnabasJ** [ash-project/ash#980]
**Describe the bug**

Before it was possible to specify Strings as values in 

```elixir
use Ash.Type.Enum, values: ["STRING1", "STRING2"]
```

Now i get a compile error saying only `:atom` or `{:atom, string}` is allowed

**To Reproduce**
A minimal set of resource definitions and calls that can reproduce the bug.

**Expected behavior**

**Runtime**
 - Elixir version 1.16
 - Erlang version 26
 - OS Ubuntu
 - Ash version `main`
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Fixed in `main` and back ported to 2.0
