### ISSUE TITLE
Missing Resource DSL docs

### ISSUE THREAD

**Issue by andyleclair** [ash-project/ash#985]
**Describe the bug**
https://hexdocs.pm/ash/3.0.0-rc.14/dsl-ash-resource.html is missing as of `rc-14`

**Comment by zachdaniel** [comment]
I've pushed fixed documentation. The documentation is currently under review, so some guides show under the "Under Review" section, which isn't ideal, but it is still technically a release candidate, so I guess its not a huge deal?
