### ISSUE TITLE
bulk_update action has a bug when returning error

### ISSUE THREAD

**Issue by nallwhy** [ash-project/ash#994]
**Describe the bug**

https://github.com/ash-project/ash/blob/915fc03565dd9c7b9d9f99eb5c78a2a70bec370d/lib/ash/actions/update/bulk.ex#L15

This function takes action as **atom**.

But when to returns error, it tries to access `action.name`.

https://github.com/ash-project/ash/blob/915fc03565dd9c7b9d9f99eb5c78a2a70bec370d/lib/ash/actions/update/bulk.ex#L70-L85

**To Reproduce**

Run `bulk_update` with not streamable query

**Expected behavior**

Returns error well

**Runtime**
 - Elixir version: 1.16.0
 - Erlang version: 26.0
 - OS: Mac
 - Ash version: 2.21.9
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Fixed in 6d3b00f77f99b9913e45e4b840ff8db5b542634d
